AcademySoftwareFoundation/OpenCue

- cuegui/cuegui/FrameMonitorTree.py
Add a function to get the frame state as a string instead of returning the index of enum.
Issue #160
> issue #160 - enum in frame monitor view display state as string

- rqd/rqd/rqcore.py
- rqd/rqd/rqdservicers.py
Issue #168 
RQD no longer throws an exception if the frame is not currently running when `killFrame` is called.
> Stopping RQD killframe exception when frame is not running

- cuegui/cuegui/FrameMonitorTree.py
The frame updates in the Job Details view weren't working after the grpc migration.
> Fixing frame updates in FrameMonitorTree

- cuegui/cuegui/AbstractWidgetItem.py
- cuegui/cuegui/FrameMonitorTree.py
Column sorting was silently failing, and always reporting False. 
Fixed sort lambda call, and if it fails in the future, a warning message is displayed and it falls back on doing a text sort.
> Fixing column sorting in job monitor and host monitor view

- cuegui/cuegui/Utils.py
Fixes Issue #179 
Priority for the log view editor is as follows:
* EDITOR env variable
* If not defined use the Constants.DEFAULT_EDITOR variable
This change also will handle errors in launching the editor by displaying an error message to the user.
> Add ability to use EDITOR env var as log view text editor 

- cuegui/cuegui/ServiceDialog.py
- cuesubmit/cuesubmit/Submission.py
Related to issue #183.
The service dialog was still using the raw grpc object for the update method. I've switched this to use the api wrapper instead.
Also, the submission tool wasn't correctly setting the service. This has been fixed in `cuesubmit.Submission.py`.
> Switching service dialog update to use service wrapper

- pycue/opencue/wrappers/host.py
- rqd/rqd/rqmachine.py
Ensure that the frames list is empty before generating frame info for host report.
> Clear the frames list in the host report before each report is generated

- cuebot/src/main/resources/log4j.properties
This change allows for the cuebot logs to be visible from `docker logs`, full logs are still written to logs/spcue.log.
> Configure cuebot logs to write WARN and ERROR messages to stdout

- cuebot/src/main/java/com/imageworks/spcue/service/EmailSupport.java
The images used by EmailSupport were not being found in the jar due to the incorrect path.
Correcting this to cleanup the error messages we see at cuebot startup.
> Cuebot: fix image path to clean up missing png errors at startup.

- cuebot/src/main/java/com/imageworks/common/spring/remoting/CueServerInterceptor.java
- cuebot/src/main/java/com/imageworks/common/spring/remoting/GrpcServer.java
- pycue/opencue/util.py
Issue #59 
Adding a global server interceptor that takes care of access logging and passes back useful exceptions to the clients. This assumes all clients are trusted.
Format for access logs:
"""
gRPC [/127.0.0.1:33070]: job.JobInterface/GetJob
Request Data: id: "testjob"
"""
> Add interceptor to do access logging and global exception passing

- pycue/opencue/cuebot.py
Fixes Issue #220.
The gRPC channel was not being updated when `setHosts` or `setFacility` was being called on the Cuebot object.
> Reset channel in pycue when setting host or facility

- cuebot/src/main/java/com/imageworks/spcue/util/JobLogUtil.java
- cuebot/src/main/resources/opencue.properties
- cuebot/src/test/java/com/imageworks/spcue/test/util/JobLogUtilTests.java
Issue #180 
Move configuration of the job log directory to the properties files, allowing log directory location to be configured in the file or set on the command line.
> Make job log directory location be configurable in opencue.properties

- cuesubmit/cuesubmit/ui/Submit.py
Fixes Issue #232 
Update Cuesubmit to use the beginReadArray/beginWriteArray instead of storing lists directly. This method is supported on all platforms.
> Have Cuesubmit QSettings use Read/WriteArray

- pycue/opencue/cuebot.py
- rqd/rqd/rqnetwork.py
Issue #229 
Randomize the order of selected cuebots for pycue and rqd.
> Randomize order of configured cuebot hosts when establishing a channel

- cuesubmit/cuesubmit/Submission.py
When a layer is submitted from cuesubmit with 2 or more threads specified, tag the layer as threadable. We may want to expose a toggle in the future for this, but this seems like the most common expected behavior.
> If job is submitted with 2 or more threads, set it to be threadable

- cuegui/cuegui/Utils.py
Convert `NestedJob` types to `Job` objects when counting job types. This is to support both the Monitor Jobs and Monitor Cue views.
> Make sure that the data is a Job when counting types

- cuesubmit/cuesubmit/Config.py
- cuesubmit/cuesubmit/Constants.py
- cuesubmit/cuesubmit_config.example.yaml
Adding an optional cuesubmit config file referenced by the environment variable `CUESUBMIT_CONFIG_FILE`, if it exists the `Constants.py` reads in the values 
Issue #256
> Adding ability to override constants with config values for cuesubmit

- cuebot/src/main/java/com/imageworks/common/spring/remoting/GrpcServer.java
- cuebot/src/main/resources/conf/spring/applicationContext-grpcServer.xml
- cuebot/src/main/resources/opencue.properties
- cuebot/src/test/resources/conf/spring/applicationContext-grpcServer.xml
- cuebot/src/test/resources/opencue.properties
- pycue/opencue/cuebot.py
- pycue/opencue/default.yaml
Increasing the grpc max message size to 100MB for cuebot and pycue to more closely match the original ice implementation.
> Increase max message size to 100MB

- cuebot/src/main/java/com/imageworks/spcue/dao/oracle/NestedWhiteboardDaoJdbc.java
- cuebot/src/main/java/com/imageworks/spcue/dao/postgres/NestedWhiteboardDaoJdbc.java
- cuegui/cuegui/CueJobMonitorTree.py
- cuegui/cuegui/GroupDialog.py
- proto/job.proto
To keep the response from getJobWhiteboard to a reasonable size, it will only return the groups and the nested job ids instead of the job objects themselves. The Job objects can be fetched in subsequent calls.
> getJobWhiteboard returns groups only and a list of job ids

- cuegui/cuegui/DarkPalette.py
- cuegui/cuegui/ItemDelegate.py
Keep item fonts consistent. Set alignment to center on selection instead of right to make it less jarring.
> Cuegui linux style updates

- cuebot/src/main/java/com/imageworks/spcue/LayerStats.java
- cuebot/src/main/java/com/imageworks/spcue/dao/oracle/WhiteboardDaoJdbc.java
- cuebot/src/main/java/com/imageworks/spcue/dao/postgres/WhiteboardDaoJdbc.java
- cuebot/src/main/java/com/imageworks/spcue/service/EmailSupport.java
- cuebot/src/main/java/com/imageworks/spcue/util/Convert.java
- cuebot/src/main/java/com/imageworks/spcue/util/CueUtil.java
Issue #266 
This forces the evaluation of float decimal separators as a `.`
> When formatting floats as strings, use root locale

- cuegui/cuegui/FrameMonitorTree.py
Fixes https://github.com/imageworks/OpenCue/issues/278
This seems to happen on every job completion or close to that, so WARNING is far too high. DEBUG is more appropriate since it indicates normal functioning of the system.
> Change log level for message when job completes.

- rqd/rqd/rqconstants.py
#271 enchancement.
Allowed...
* RQD_USE_IP_AS_HOSTNAME
* DEFAULT_FACILITY
* LAUNCH_FRAME_USER_GID
...to be overriden in rqd.conf
-C
> Allow more rqconstants to be overwritten by config

- cuegui/cuegui/plugins/MonitorJobsPlugin.py
Fixes #276.
Added a "Load Finished" checkbox, which triggers the `include_finished=True` parameter on `api.getJobs()`.
Checkbox defaults to unchecked.
When said checkbox's state is changed to "checked", it triggers a load of finished jobs.
Snuck in a regex change to `substring` too - added `_` to the 'show' section of the pattern.
-C
> add support for viewing archived jobs

- cuegui/cuegui/Constants.py
- cuegui/cuegui/Main.py
#285 enhancement.
Updated Main.py in cuegui to check for CUEGUI_DEFAULT_INI_PATH environment variable before defaulting to Constants.DEFAULT_INI_PATH when creating config.ini for first-time launches of CueGUI.
> Allow for override of cuegui.Constants.DEFAULT_INI_PATH

- cuebot/src/main/java/com/imageworks/spcue/DispatchJob.java
- cuebot/src/main/java/com/imageworks/spcue/dao/DispatcherDao.java
- cuebot/src/main/java/com/imageworks/spcue/dao/oracle/DispatchQuery.java
- cuebot/src/main/java/com/imageworks/spcue/dao/oracle/DispatcherDaoJdbc.java
- cuebot/src/main/java/com/imageworks/spcue/dao/postgres/DispatchQuery.java
- cuebot/src/main/java/com/imageworks/spcue/dao/postgres/DispatcherDaoJdbc.java
- cuebot/src/main/java/com/imageworks/spcue/dispatcher/DispatchSupport.java
- cuebot/src/main/java/com/imageworks/spcue/dispatcher/DispatchSupportService.java
- cuebot/src/main/java/com/imageworks/spcue/dispatcher/Dispatcher.java
- cuebot/src/main/java/com/imageworks/spcue/dispatcher/FrameCompleteHandler.java
- cuebot/src/main/java/com/imageworks/spcue/dispatcher/HostReportHandler.java
- cuebot/src/test/java/com/imageworks/spcue/test/dao/oracle/DispatcherDaoTests.java
- cuebot/src/test/java/com/imageworks/spcue/test/dao/postgres/DispatcherDaoTests.java
Issue #298 
Update the dispatcher behavior to the following:
On Frame completion:
1. Check if any job is under it's `min_cores` setting, if there are dispatch those jobs
2. Check if any job is a higher priority, if so dispatch the highest priority job
3. Attempt to dispatch proc to same job.
On HostReport (no job currently running on the host):
1. Dispatch to a job under it's `min_core` setting.
2. Dispatch to the highest priority job if all jobs have hit their `min_core` target.
> Respect job priorities in the dispatcher

- pyoutline/outline/config.py
- pyoutline/tests/backend/cue_test.py
- pyoutline/tests/backend/local_test.py
- requirements.txt
Related to #228 
The `home` and `user_dir` variables of the `outline.cfg` should be specified by the user. If they are not this change provides some defaults.
> Adding default pyoutline home and user directories to the config

- cuebot/src/main/resources/conf/spring/applicationContext-criteria.xml
- cuebot/src/main/resources/conf/spring/applicationContext-dao-oracle.xml
- cuebot/src/main/resources/conf/spring/applicationContext-dao-postgres.xml
- cuebot/src/main/resources/conf/spring/applicationContext-dbEngine.xml
- cuebot/src/main/resources/conf/spring/applicationContext-grpc.xml
- cuebot/src/main/resources/conf/spring/applicationContext-grpcServer.xml
- cuebot/src/main/resources/conf/spring/applicationContext-jms.xml
- cuebot/src/main/resources/conf/spring/applicationContext-service.xml
- cuebot/src/main/resources/conf/spring/applicationContext-trackit.xml
- cuebot/src/main/resources/conf/spring/jobLaunchServlet-servlet.xml
- cuebot/src/test/resources/conf/spring/applicationContext-assumptions.xml
- cuebot/src/test/resources/conf/spring/applicationContext-grpcServer.xml
- cuebot/src/test/resources/conf/spring/applicationContext-oracle-datasource.xml
- cuebot/src/test/resources/conf/spring/applicationContext-postgres-datasource.xml
Lock all xml schemas to 2.5 until we upgrade spring versions #235.
As part of moving to spring 5.1 we should remove the schema version from the urls.
> Cleanup spring xml files to all use schema definitions.

- cuebot/src/main/java/com/imageworks/spcue/servant/ManageHost.java
- cuegui/cuegui/MenuActions.py
- proto/host.proto
- pycue/opencue/wrappers/group.py
- pycue/opencue/wrappers/host.py
- pycue/tests/wrappers/group_test.py
- pycue/tests/wrappers/host_test.py
Adding unittests for group and host wrappers.
NestedGroup asGroup function now returns a Group wrapper object.
Correctly labeling allocation id as id in Host SetAllocation call.
> Adding unittests for group and host wrappers.

- cuegui/cuegui/CueJobMonitorTree.py
- cuegui/cuegui/ItemDelegate.py
- pycue/opencue/wrappers/job.py
- pycue/tests/wrappers/job_test.py
The progress bar colors in CueGui were essentially random due to reliance on the order of a set.  This change uses a dictionary instead of a set to store the frame states and fixes the color lookup.
Fixes #327. Make frameStateTotals return a dictionary so order does not matter.
> Fix CueGui progress bar colors

- cuegui/cuegui/Constants.py
Add CueGUI constants to address https://github.com/imageworks/OpenCue/issues/309
We'll need to update `URL_SUGGESTION` and `URL_BUG` if the repo URL changes.
>  Add CueGUI help constants

- pycue/opencue/api.py
- pycue/opencue/wrappers/deed.py
- pycue/opencue/wrappers/owner.py
- pycue/tests/api_test.py
- pycue/tests/wrappers/deed_test.py
- pycue/tests/wrappers/owner_test.py
SPI reported these wrappers were missing and causing problems for them with pyoutline. 
Main change is `api.getOwner` now returns an owner wrapper. Calling methods were already expecting the wrapper.
> Adding owner and deed wrappers

- cuebot/README.md
- pycue/opencue/wrappers/layer.py
- pycue/tests/wrappers/layer_test.py
The protos defined the RegisterOutputPath function but it was not exposed in the Layer pycue wrapper.
> Adding missing wrapper function for RegisterOutputPath

- pyoutline/outline/backend/cue.py
Fix for job submit error on jobs with dependencies:
```bash
Failed to parse job spec XML, org.jdom.input.JDOMParseException: Error on line 1: Attribute value "b'False'" of type NMTOKEN must be a name token.
```
Resulting in bad 'anyframe' value:
```xml
<depends>
<depend anyframe="b'False'" type="LAYER_ON_LAYER">
<depjob>b858be71-6467-4e00-997a-824b32fb0e0c</depjob
<deplayer>MyTaskNameTwoB</deplayer>
<onjob>b858be71-6467-4e00-997a-824b32fb0e0c</onjob>
<onlayer>MyTaskNameOneA</onlayer>
</depend>
</depends>
```
> Ensure ElementTree.SubElement receives a str #368

- pycue/opencue/api.py
- pycue/opencue/search.py
- pycue/tests/search_test.py
Fixes #371 
Bring `HostSearch` in line with our current policy of converting gRPC responses to wrapper classes as soon as possible on reception.
Host searching is used in two places:
1. CueAdmin, when using the `-host` flag. This code appears to already have expected wrapped classes (see bug report in linked bug). Unit tests were passing because the mocked response from `HostSearch` assumed this as well.
1. CueGUI, in the Monitor Hosts panel. In this case the search was happening by way of `opencue.api.getHosts`, which was wrapping the response itself. This downstream wrapping is no longer needed.
> Update HostSearch to return wrapped objects instead of Response class.

- cuesubmit/cuesubmit/Constants.py
- cuesubmit/cuesubmit/JobTypes.py
- cuesubmit/cuesubmit/Submission.py
- cuesubmit/cuesubmit/ui/SettingsWidgets.py
Basic solution for #312.
This adds "Blender" as an option in the cuesubmit job types dropdown. It does not include a dedicated Blender plugin.  Available options include, setting blender file name, setting output name and format.
> Add Blender as an option to cuesubmit

- azure-pipelines.yml
- ci/extract_artifacts.sh
- ci/extract_schema.sh
- ci/generate_version_number.sh
- ci/templates/build_docker.yml
- cueadmin/Dockerfile
- cuebot/Dockerfile
- cuegui/Dockerfile
- cuesubmit/Dockerfile
- pycue/Dockerfile
- pyoutline/Dockerfile
- rqd/Dockerfile
A few related changes to speed up our build pipeline runtime.
In my tests these changes bring our baseline build time from 27min -> 14min (better, but more work is needed).
- Use Docker Hub as an external cache.
- Push images there as they're built.
- Use a new `opencuebuild` repo to keep these mostly-ephemeral images from polluting the release-quality, published images.
- Tag the pushed images with branch name and `latest` to enable images to be reused between subsequent builds in the same branch and to some extent between branches.
- Break the Docker image build process out into a separate template YAML file to reduce repetition.
- Reformat `Dockerfile`s
- Ditch most of the stages, they're not used anymore.
- We still need two stages -- one for build and one for runtime -- because build …
> Build pipeline improvements

- azure-pipelines.yml
- ci/extract_artifacts.sh
This will make it easier to fetch a build's full version number downstream.
> Publish the VERSION file as a build artifact.

- azure-pipelines.yml
To clarify between separate accounts for build and release pipelines.
> New name of Docker Hub build account

- cuebot/src/main/java/com/imageworks/spcue/servant/ManageSubscription.java
Fixes #399 
Removes an unnecessary conversion step when editing subscription size and burst size.  This conversion causes the value input into the GUI to not be the value stored which leads to confusion.
> Remove unnecessary conversion step when editing subscription size

- CONTRIBUTING.md
Also, move the CLA section underneath the PR section to better reflect the current workflow.
> Add CONTRIBUTING section on GitHub issues.

- cuebot/build.gradle
- sonar-cloud-pipeline.yml
#396 
Add JaCoCo into our Gradle config for generation of test coverage reports. SonarCloud picks these reports up automatically as long as they exist; run the `jacocoTestReport` task as part of the SonarCloud pipeline.
> Wire up Cuebot test coverage.

- .gitignore
- ci/python_coverage_report.sh
- pycue/tests/__init__.py
- rqd/rqd/__init__.py
- rqd/rqd/compiled_proto/__init__.py
- rqd/setup.py
- sonar-cloud-pipeline.yml
- sonar-project.properties
#396 
Update pipeline to run all Python tests, collect coverage into a single report, and send the report to SonarCloud.
I've also split the Cuebot and Python coverage tasks into separate pipeline jobs, because I wanted to use the ASWF VFX reference platform image for the python environment but it turns out that image is not quite JDK-friendly yet.
> Wire up Python component test coverage.

- cuebot/src/main/java/com/imageworks/spcue/servant/ManageAllocation.java
- cuebot/src/main/java/com/imageworks/spcue/servant/ManageDepend.java
- cuebot/src/main/java/com/imageworks/spcue/servant/ManageFacility.java
- cuebot/src/main/java/com/imageworks/spcue/servant/ManageFilter.java
- cuebot/src/main/java/com/imageworks/spcue/servant/ManageFrame.java
- cuebot/src/main/java/com/imageworks/spcue/servant/ManageGroup.java
- cuebot/src/main/java/com/imageworks/spcue/servant/ManageHost.java
- cuebot/src/main/java/com/imageworks/spcue/servant/ManageJob.java
- cuebot/src/main/java/com/imageworks/spcue/servant/ManageLayer.java
- cuebot/src/main/java/com/imageworks/spcue/servant/ManageOwner.java
- cuebot/src/main/java/com/imageworks/spcue/servant/ManageShow.java
- cuebot/src/main/java/com/imageworks/spcue/servant/ManageSubscription.java
- pycue/tests/util_test.py
Issue #401 
The existing code does not follow any standards when returning error codes from `find` and `get` calls. As a standard these should raise an `EntityNotFoundException` in pycue not a `CueInternalErrorException`.
I've decided to open this PR without tests of the cuebot servants as this should be addressed in #396 and is going to take a bit more wiring up. I have added tests for the pycue exception parser.
> Find and get methods should raise EntityNotFoundException in pycue

- rqd/Dockerfile
Issue #390 
Start bash before running starting rqd to prevent leaving defunct children processes. See https://blog.phusion.nl/2015/01/20/docker-and-the-pid-1-zombie-reaping-problem/ for a description of the problem. 
This solution causes rqd to forcefully exit, but I don't believe this should be a great concern, since cuebot should handle failing tasks due to lost connectivity.
> Start bash before rqd to prevent zombie processes from being pid 1.

- cuegui/Dockerfile
- cuegui/cuegui/FrameMonitorTree.py
- cuegui/tests/FrameMonitorTree_tests.py
#396 
Tests for FrameMonitorTree and the related FrameWidgetItem classes.
This necessitated splitting the context menu out into a new class that subclasses `QMenu`. This allows us to properly mock our own class, in order to avoid triggering GUI code.
> Add tests for FrameMonitorTree.

- cuegui/cuegui/Utils.py
Small bug fix to ensure a log path was passed in when launching log view.
> Make sure log path is not empty when poping up log view

- cuegui/cuegui/LayerDialog.py
Fixes #419 
`opencue.wrappers.layer.Layer().setMin/MaxCores`  takes a percentage of core values where 100 = 1 core, so values must be multiplied by 100.
> CueGui Layer.setMinCores should be passed a percentage value 

- cuegui/cuegui/ServiceDialog.py
Fixes #416 
The same code path is used when updating an existing service and creating a new one. When creating a new service, there is no existing one and we shouldn't add an `id`, so only do that when an existing service is supplied.
Also cleans up the variable names to clarify when dealing with the wrapper object.
> Fix create new service bug in cuegui.

- cuebot/src/main/java/com/imageworks/spcue/dispatcher/HostReportHandler.java
- cuebot/src/main/java/com/imageworks/spcue/rqd/RqdClient.java
- cuebot/src/main/java/com/imageworks/spcue/rqd/RqdClientGrpc.java
- cuebot/src/main/java/com/imageworks/spcue/servant/ManageHost.java
- cuebot/src/main/java/com/imageworks/spcue/service/HostManagerService.java
- cuebot/src/test/java/com/imageworks/spcue/test/dispatcher/HostReportHandlerTests.java
- cuegui/cuegui/HostMonitorTree.py
- cuegui/cuegui/Utils.py
- rqd/rqd/rqcore.py
- rqd/rqd/rqmachine.py
Fixes #431 
(Un)Locking cores in cuegui was not working because it was never calling out to the rqd instance to lock the cores. (Un)Locking cores via `cuerqd.py` did not work reliably because rqd never updated the lock state in the cuebot database.
This PR addresses these problems by making sure the locks are checked in the host report and that api calls to lock a host also communicate that lock to the rqd instance.
> RQD lock and unlock behavior

- rqd/rqd/rqmachine.py
Per https://github.com/AcademySoftwareFoundation/OpenCue/issues/433
> Fix spelling of getRecentPgoutRate method call #433

- cuebot/src/main/java/com/imageworks/spcue/dispatcher/DispatchSupportService.java
- cuebot/src/main/java/com/imageworks/spcue/util/FrameSet.java
- cuebot/src/test/java/com/imageworks/spcue/test/util/FrameSetTests.java
Submitted as a WIP because:
- I'm not very confident in Java
- You guys probably have your own ideas about how to approach this
But - it works well enough for me that I can proceed with testing.
This update allows me to submit a command like this:
```bash
/bin/true -f #FRAMESPEC#
```
And the rqd daemon is assigned something like this (depending on framerange/chunk size):
```bash
/bin/true -f 12-24x2
```
The logic is ported directly from [FileSeq](https://github.com/sqlboy/fileseq/blob/68872035e72626707c954dbb6f3b661ae157ccb3/src/fileseq/frameset.py#L1081).
> WIP: Add getChunk method to FrameSet and substitute its result into commands

- ci/python_coverage_report.sh
- ci/run-with-xvfb.sh
- cuegui/Dockerfile
- sonar-cloud-pipeline.yml
Fixes #442 
https://github.com/AcademySoftwareFoundation/aswf-docker/pull/15 creates the first version of our `ci-opencue` Docker image; start to use it with our SonarCloud pipeline.
I also remove a few things from the pipeline + associated scripts that aren't needed anymore as those pieces are installed directly in the CI image now.
> Use ci-opencue Docker image for SonarCloud pipeline.

- cuebot/src/main/java/com/imageworks/spcue/servant/ManageLayer.java
- proto/job.proto
- pycue/opencue/search.py
Fixes #446 
This change fixes 2 problems.
1. The Layer wrapper object now allows a user to specify a `limit` when calling `getFrames` and the `FrameSeachCriteria` values are correctly set.
2. Cuebot no longer performs an unnecessary cleaning of the `FrameSeachCriteria` that was erroring out.
> Fixes for Layer.getFrames

- cuegui/cuegui/CreatorDialog.py
- cuegui/cuegui/CueJobMonitorTree.py
- cuegui/cuegui/Cuedepend.py
- cuegui/cuegui/DependWizard.py
- cuegui/cuegui/plugins/AllocationsPlugin.py
- pycue/opencue/wrappers/allocation.py
- pycue/opencue/wrappers/deed.py
- pycue/opencue/wrappers/filter.py
- pycue/opencue/wrappers/frame.py
- pycue/opencue/wrappers/group.py
- pycue/opencue/wrappers/host.py
- pycue/opencue/wrappers/job.py
- pycue/opencue/wrappers/layer.py
- pycue/opencue/wrappers/owner.py
- pycue/opencue/wrappers/proc.py
- pycue/opencue/wrappers/show.py
- pycue/tests/wrappers/allocation_test.py
- pycue/tests/wrappers/filter_test.py
- pycue/tests/wrappers/frame_test.py
- pycue/tests/wrappers/group_test.py
- pycue/tests/wrappers/job_test.py
- pycue/tests/wrappers/layer_test.py
- pycue/tests/wrappers/show_test.py
Cleaning up wrapper methods so that no protobuf objects are passed in or returned. Some protobuf enums are still passed around but that is intentional. Also changes update docstrings to further clarify object types.
Fixes #448
> Cleaning up wrapper methods 

- pycue/opencue/wrappers/layer.py
- pycue/tests/wrappers/layer_test.py
Fixes #453 
`CreateFrameByFrameDepend` should be `CreateFrameByFrameDependency`
See `proto/job.proto` line 271.
> Fix createFrameByFrameDependency grpc method 

- cuegui/cuegui/ItemDelegate.py
Fixes #480 
When selecting an item in CueGui the alignment should stay to the left.
> Left alignment should not change on selection.

- cuegui/cuegui/FrameMonitor.py
- cuegui/cuegui/plugins/MonitorJobDetailsPlugin.py
- cuesubmit/cuesubmit/ui/Submit.py
Fixes #474 
Directly hook up double click in layers view to frames filter call.
Also cleans up cuesubmit, to make sure the default "empty" values for services and limits are not sent on job submission
> Double clicking layer in cuegui should filter the frames view

- rqd/rqd/cuerqd.py
- rqd/tests/cuerqd_tests.py
#396 
Brings file coverage up to 93%, RQD coverage up to 68%.
> Add unit tests for cuerqd.py.

- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
Currently the PR template and `CONTRIBUTING` doc duplicate some content. Plus it's annoying to select and delete that PR checklist every time.
Merge the two together and link to `CONTRIBUTING` from the PR template.
> Merge PR template content into CONTRIBUTING.

- cuegui/cuegui/MenuActions.py
- cuegui/tests/MenuActions_tests.py
- pycue/opencue/api.py
- pycue/opencue/search.py
- pycue/tests/search_test.py
Fixes #485 
Adds type information to docstrings and validates list type to prevent strings from being treated as lists.
> Raise exception when search args are not passed the correct type

- samples/rqd/blender/blender2.79-docker/Dockerfile
Signed-off-by: Sharif Salah <sharifsalah@google.com>
Fixes https://github.com/AcademySoftwareFoundation/OpenCue/issues/495
Add a simple Dockerfile to illustrate how to customize the base RQD image on Docker Hub for the latest release using Blender 2.79. Please see the issue for additional context.
Will compliment a how-to guide to be published on opencue.io.
> Add Blender 2.79 on RQD Dockerfile sample

- cuebot/src/main/java/com/imageworks/spcue/dao/oracle/FrameDaoJdbc.java
- cuebot/src/main/java/com/imageworks/spcue/dao/oracle/LayerDaoJdbc.java
There is a syntax error on:
GROUP BY limit_record.pk_limit_record) AS sum_running
It should be:
GROUP BY limit_record.pk_limit_record) sum_running
Also there is a dangling comma on the select statement in the GET_LIMIT_NAMES on LayerDaoJdbc.
> Fixing a couple syntax bugs with the oracle queries.

- pycue/opencue/wrappers/layer.py
- pycue/tests/wrappers/layer_test.py
Fixes #497
Fix typos in `opencue.wrappers.layer.Layer` that prevent creating Layer dependencies through API.
> fix: Layer dependency creation API typos

- cuegui/cuegui/MenuActions.py
Closes https://github.com/AcademySoftwareFoundation/OpenCue/issues/509
When marking a layer with a single frame as done the functions have
likely been renamed.
> Fix incorrect function calls

- cuegui/cuegui/plugins/MonitorCuePlugin.py
Fixes #526
Add "Select All" and "Clear" show filters to Monitor Cue Plugin for convenience.
> feat: Add extra show filter options to MonitorCue

- pycue/opencue/cuebot.py
- pycue/opencue/default.yaml
- pycue/opencue/exception.py
- pycue/opencue/util.py
- pycue/tests/util_test.py
Fixes #534 
Adds a new `ConnectionException` type and allows for retryable exceptions. `ConnectionException` errors will retry 3 times with a 0.5 second backoff by default.
> Add a connection exception and retries to the pycue grpc decorator

- ci/packaging-pipeline.yml
- ci/run_python_tests.sh
- ci/testing-pipeline.yml
#487 
- The testing pipeline is based on the SonarCloud pipeline, which uses the ci-opencue docker image instead of building all Docker images separately. This will become the main pipeline run for all PR commits.
- The packaging pipeline is based on the existing test pipeline, which builds all Docker images and other artifacts. It contains almost no changes, except it will only run on commits that are merged into master.
Once these are in place and confirmed working, I'll send a followup PR to remove the old pipeline and will remove it from Azure as well.
> Add separate pipelines for tests and packaging.

- rqd/tests/rqnimby_tests.py
If the thread isn't joined, sometimes the mocked method hasn't been called yet.
> Fix race condition in one of the RqNimby tests.

- ci/python_coverage_report.sh
- ci/run_python_tests.sh
- cuegui/Dockerfile
We're getting sporadic test flakes from `xvfb-run`:
```
test_getCores (tests.FrameMonitorTree_tests.FrameMonitorTreeTests) ... qt.qpa.screen: QXcbConnection: Could not connect to display :99
Could not connect to any X display.
```
This PR adds the `-d` switch to all uses of `xvfb-run`.
```
-d        --auto-display            use the X server to find a display number
automatically
```
So far in tests on Azure this has resolved the problem, but it's hard to know for sure.
> Attempt to fix xvfb-run flake.

- sandbox/docker-compose.yml
Fixes https://github.com/AcademySoftwareFoundation/OpenCue/issues/532
Add a volume to the sandbox environment to store input and output files for RQD nodes at /tmp/rqd/shots/
This will help provide more real-world usage examples in the docs and for live demos or screencasts that use rendering software on RQD nodes, such as Blender or ImageMagick
Note: After approval, I'll aim to wait to merge this when I've also updated the quick start to add the mount point for the volume on the sandbox host.
> Add a shots volume to the sandbox

- cuebot/src/main/resources/application.properties
After updating spring boot, the static content began being served at the root instead of being prefixed with `/spcue/`. The xml schema are hosted with this path, this change fixes the urls to behave as they did before.
> Fix static content url in cuebot

- cuegui/cuegui/DarkPalette.py
#61 
The default theme on Windows is high-contrast and unreadable.  The default Qt5 theme, Fusion, looks much better.
> Use dark stylesheet for Windows too

- cuegui/setup.py
This allows (for example) PyCharm to correctly configure the project when opening the directory directly, rather than installing everything in the repo-wide `requirements.txt`.
> Add install_requires packages for CueGUI

- cuebot/deploy/systemd/opencue-cuebot.service
Reported in #503 .
Update command line flags for cuebot to match new style argument names.
> Update cuebot service definition to match new command line flags.

- CODE_OF_CONDUCT.md
The TSC can definitely add to this as needed, but wanted to link in what's used by default.
> Add CODE_OF_CONDUCT - default version for LF projects

- docs/README.md
- docs/modules/FileSequence.rst
- docs/modules/modules.rst
- docs/modules/opencue.compiled_proto.rst
- docs/modules/opencue.rst
- docs/modules/opencue.wrappers.rst
https://github.com/AcademySoftwareFoundation/OpenCue/issues/559
Updates Sphinx configuration to add support for generating reference docs of `FileSequence` and `opencue` packages. This compliments the existing configuration for the `outline` package.
To review or test the generated output, see the accompanying README.md file, which I've updated in this PR.
The generated docs need a lot of work, but I think that's better addressed in separate PRs as it means updating the Python source code. 
Also, Sphinx produces some warnings (such as `Unexpected indentation.`) that again need to be fixed by updating the Python source code.
> Add PyCue packages and modules docs

- ci/run_python_tests.sh
- ci/testing-pipeline.yml
Fixes #557 
VFX Reference Platform CY2020 uses Python 3 as its default interpreter, so this in effect runs all tests in a Python 3 environment.
Keeping CY2019 as we want to keep testing against Python 2 for the foreseeable future.
Cuebot tests included as well just to test compatibility.
> Run testing pipeline against CY 2020.

- cuesubmit/cuesubmit/Validators.py
- cuesubmit/tests/Validators_tests.py
#396
Added first tests for Validators
Updated comment for one function in Validators.py based on test result
Validators.py didn't have any test coverage yet
> Add test for cuesubmit - Validators.py

- cuegui/cuegui/AbstractTreeWidget.py
Fixes #595 
Use the close event on abstract widgets to stop and delete the timer attached to widgets to prevent error messages, crashes and hangs.
> Stop and delete timer objects when attempting to close the a window

- rqd/rqd/rqutil.py
#364 
It appears the condition to downgrade permissions has a typo and checks GID twice, instead of GID and UID.
The issue includes a query for @jrray - are you able to confirm the history here?
> Fix the permission check to include GID and UID.

- cuebot/src/main/java/com/imageworks/spcue/dispatcher/DispatchSupportService.java
https://github.com/AcademySoftwareFoundation/OpenCue/issues/83
https://github.com/AcademySoftwareFoundation/OpenCue/issues/104
This is to better support frame chunks in the layers.
Frame chunks are really valuable for software packages like Nuke and Houdini
> Add #OFRAME# (outframe) to DispatchSupportService to support chunks

- cuebot/src/main/java/com/imageworks/spcue/service/JobManager.java
- cuebot/src/main/java/com/imageworks/spcue/service/JobManagerService.java
- cuebot/src/main/java/com/imageworks/spcue/service/JobManagerSupport.java
Closes https://github.com/AcademySoftwareFoundation/OpenCue/issues/463
If a job has succeeded it will never restart frames even if requested.
Change the job's status to pending to force the scheduler to pick it up.
> Set job back to pending in case if retry

- cuegui/cuegui/GarbageCollector.py
- cuegui/cuegui/Main.py
Fixes #473
- Handle garbage collection in the main GUI thread to prevent qtimer stopped in wrong thread which results in segfault.  
- Have tried actions which typically caused crashes and has since been stable.
This work is based on this [thread](https://www.riverbankcomputing.com/pipermail/pyqt/2011-August/030378.html) which might explain why the intermittent crashes were happening.  
Essentially, there are likely cyclic references to various tree widgets, as a result Python's Garbage Collector is clearing them, but Python's GC isn't necessarily running in the correct thread hence `“QObject::killTimer: Timers cannot be stopped from another thread`
This is quite a significant change, to alter the standard …
> Stop qtimer wrong thread segfault (#473)

- rqd/Dockerfile
Master build is currently broken -- the ancient setuptools that's the default on CentOS 7 doesn't support the `platform_system` notation we recently added to the RQD `Dockerfile`.
> Upgrade setuptools in RQD docker.

- rqd/rqd/rqutil.py
This looks like it has been authored incorrectly; group ID is being compared against user ID.
> Fix what appears to be a typo bug in __becomeRoot

- cuebot/src/main/java/com/imageworks/spcue/VirtualProc.java
- cuebot/src/test/java/com/imageworks/spcue/test/util/CoreSaturationTests.java
When the Arnold service is found on a frame it uses all available cores
on the host.
Removing this in favour of default min/max core behaviour.
Closes #549
> Remove arnold specific override

- cuegui/cuegui/Constants.py
- cuegui/cuegui/Utils.py
Fixes an outstanding issue in #61.
Default the Cuegui logview editor to Notepad on Windows.
> Make Cuegui logview work on Windows by default

- cuebot/src/main/resources/conf/ddl/postgres/migrations/V5__Increase_environment_variable_length.sql
Fixes #553 
Increase maximum env var name length to match maximum env var value length (2048).
> Increase max environment variable name length

- cuegui/cuegui/MenuActions.py
- cuegui/tests/MenuActions_tests.py
#396 
A lot of new code in `MenuAction_tests.py` but it's all very boring. The menu actions are all basically just pass-through code between the UI elements and the wrapper classes so the tests are very simple.
- File coverage 66% -> 94%
- CueGUI overall coverage 27% -> 31%
> Add more unit tests for the MenuActions module.

- cuebot/src/main/java/com/imageworks/spcue/dao/JobDao.java
- cuebot/src/main/java/com/imageworks/spcue/dao/oracle/JobDaoJdbc.java
- cuebot/src/main/java/com/imageworks/spcue/dao/postgres/JobDaoJdbc.java
- cuebot/src/main/java/com/imageworks/spcue/service/JobManagerService.java
- cuebot/src/main/java/com/imageworks/spcue/util/JobLogUtil.java
- cuebot/src/main/resources/conf/spring/applicationContext-service.xml
- cuebot/src/main/resources/opencue.properties
- cuebot/src/test/java/com/imageworks/spcue/test/dao/oracle/JobDaoTests.java
- cuebot/src/test/java/com/imageworks/spcue/test/dao/oracle/LayerDaoTests.java
- cuebot/src/test/java/com/imageworks/spcue/test/dao/postgres/JobDaoTests.java
- cuebot/src/test/java/com/imageworks/spcue/test/dao/postgres/LayerDaoTests.java
- cuebot/src/test/java/com/imageworks/spcue/test/util/JobLogUtilTests.java
- cuebot/src/test/resources/opencue.properties
#626 
Refactor JobLogUtils into a non-static class. This allows us to autowire environment information into the class. This in turn allows the `log.frame-log-root` to be overridden via command line flag -- when using the `Value` annotation on a static class as we're doing now, the value is only overridden by environment variable or modify the `.properties` file directly.
This brings the usage and naming of the `frame-log-root` setting in line with e.g. the datasource properties for configuring database access. This should make for a more consistent user experience around modifying these settings.
> Allow log root directory to be specified via command line flag.

- pyoutline/bin/pycuerun
Script is in the `bin/` subdir so I missed it when I was migrating `pyoutline` originally.
> Make pycuerun Python 3 compatible.

- cuegui/cuegui/Utils.py
- pycue/opencue/wrappers/group.py
Didn't catch this during initial testing because unit tests covering this code were added in a separate PR, which I only just merged.
This code was failing for non-`NestedGroup`s because the `parent` field doesn't exist at all for those groups. So, expand the check to cover both types of objects.
`hasParent` is a bit ambiguous because the standard `Group` object does have a `parent_id` field, which I thought was confusing. So I renamed that method as well.
> Fix root group check to handle standard groups.

- rqd/rqd/rqutil.py
Related to #193 
Skip user switching on macOS as we do for Windows. macOS isn't currently supported, but this change at least allows macOS-based developers to run the program without it crashing outright.
> Disable user switching for macOS.

- pycue/opencue/default.yaml
Default to `local` facility and `localhost` hostname.
This is intended to simplify our setup and development guides by removing the need to modify the file or specify `CUEBOT_HOSTS`.
I don't expect anyone is actually using these defaults as their real Cuebot hostnames, so impact should be minimal.
> Update default Cuebot host in Python.

- cuegui/tests/images/__init__.py
- cuegui/tests/images/images_tests.py
This doesn't actually increase test coverage, but in some parts of the SonarCloud UI it's showing these files as 0% covered, which throws line count estimates off by 10k's of lines.
> Workaround for SonarCloud coverage bug.

- cuesubmit/cuesubmit/ui/Submit.py
The `message` field isn't defined, at least for the failure I was getting. `str()` should be safer.
> Fix error dialog on submission failure.

- cuegui/cuegui/Utils.py
- cuegui/tests/Utils_tests.py
Fixes #522 
Underscores are allowed in job names, particularly the show and shot name; fix the regex to match.
This change resolves the leftover comments in #523: preserves `.` as an allowed character and adds some tests for `Utils.findJob`.
> Fix regex to allow underscores in job name.

- cuegui/cuegui/Utils.py
- cuegui/tests/Utils_tests.py
For some reason CI tests didn't run for #640, so I missed this.
String type-checking wasn't working in Python 3, and there was a mock missing.
> Fix a bug in findJob and fix its test.

- cuesubmit/cuesubmit/ui/Style.py
- cuesubmit/cuesubmit/ui/Widgets.py
Associated Issue: #275 
Change summary: 
QCompleter on the LineEdit for CueSubmit widgets was rendering white text over a white background and hence seemed like blank suggestions.
Added a background specifically for the popup listview in the style.py and used it to set the style of the completer pop up list view. 
Why this change? 
This maintains the look of the widget and helps solve the blank suggestion bug
> Fixing blank submission dropdown for LineEdit in CueSubmit

- cuebot/src/main/java/com/imageworks/spcue/servant/ManageAllocation.java
Fixes #655 
Cuebot wasn't constructing the expected response, causing any calling gRPC clients to hang indefinitely waiting for one.
> Fix reparentHosts to correctly construct its gRPC response.

- docs/conf.py
- docs/version_release_fix.py
Fixes #591
[docs/conf.py](https://github.com/AcademySoftwareFoundation/OpenCue/blob/master/docs/conf.py) has two variables, `version` and `release` which is as of now, statically typed. This script changes these two with the current `version` and `release`.
It's also helpful to describe **why** you're making this change.
Doing this manually was not a good solution at all. Having it as an automated process will make it more hassle-free.
> automatically fix version in conf.py

- cuegui/cuegui/MenuActions.py
- cuegui/cuegui/SubscriptionsWidget.py
- cuegui/tests/MenuActions_tests.py
Fixes #639 
Changed the subscriptions display so as to display straight cores instead of cores*100.
> View and Edit Subscriptions in full cores.

- ci/generate_version_number.sh
Also, fix to run on macOS via the gsed command.
> Add documentation to generate_version_number.sh.

- sandbox/setup-database.sh
Fixes #438
- Added a bash script in sandbox/ called `setup-database.sh` – automates the installation and setting up of the database, including applying migrations.
- The steps for installation were taken from the "Getting Started" [Guide](https://www.opencue.io/docs/getting-started/setting-up-the-database/)
- Uses the quick fix referred to in #651 instead of the one in the documentation due to a breaking [change](https://github.com/docker-library/postgres/issues/681) in docker-library's postgres image.
It's also helpful to describe **why** you're making this change.
> When installing and setting up the database, there are numerous steps that can go wrong. It would be nice to have an installer script to guide …
> Added support for a database installer script. (#438)

- cuegui/cuegui/HostMonitor.py
- cuegui/cuegui/config/darkpalette.qss
Fixes #672 by properly aligning the dropdown arrows with the text in Allocation and HardwareState filter in monitor hosts panel in CueGUI.
> fix filter alignment in monitor host panel

- .gitignore
We already ignore `venv/`, the conventional name for a virtual environment. But I tend to have multiple virtual environments going at once -- Python 2/3, one for testing a new release, and so on -- all named with a `venv` prefix.
Not sure if others are working this way or not but this change will help keep my Git status clean.
> Ignore all venv directories.

- cueadmin/cueadmin/common.py
- cueadmin/tests/common_tests.py
Fixes #653 
Pretty straightforward. `setAllocation` wants the wrapper object, not the underlying protobuf data.
> Fix moving hosts between allocs in cueadmin.

- cuebot/README.md
Deployment instructions were pointing to the old Wiki link, and development setup info isn't needed here anymore as we have a much more extensive guide in our Contributing section now.
> Update links in the Cuebot README.

- cuebot/src/main/java/com/imageworks/spcue/util/FrameSet.java
- cuebot/src/test/java/com/imageworks/spcue/test/util/FrameSetTests.java
#685 
`ImmutableList.subList`'s end index is exclusive, so in cases where the chunk size runs past the end of the list, we would return the rest of the list except for the final frame.
This fixes the bug and makes the `subList` call more explicit, always adding `1` to hopefully make it more obvious what's going on there. I added a unit test to test this behavior.
I also went through and updated the unit tests to the preferred "should" naming pattern.
> Fix FrameSet bug where last frame of range would not be included.

- cuegui/cuegui/CueJobMonitorTree.py
- cuegui/cuegui/Redirect.py
- cuegui/tests/CueJobMonitorTree_tests.py
- cuegui/tests/Redirect_tests.py
#396 
No real test logic, but sets up the widgets and some basic data. The aim here is two-fold:
1. Get a cheap boost to our code coverage. Even though we're not validating results this at least ensures the file syntax and basic setup is functional.
2. Make it easier for folks to add tests in the future -- adding one or two tests is easy enough if the basic widget/mock structure is already in place, but starting that from scratch is a high enough barrier to entry to discourage test writing.
This brings CueGUI coverage 33% -> 38%.
I hope to bring this approach to other parts of the codebase in followup PRs.
> Unit test scaffolding for CueJobMonitorTree and Redirect.

- cuegui/cuegui/HostMonitor.py
#694 
I think the `if` in this handler is a bit off. From my reading, it's trying to accomplish two things:
1. If the regex is blank, set a special "blank" value into the search object -- in this case an empty array.
2. If the search term has changed, refresh the widget so the host filtering can occur.
But there are two problems with the way it's currently written:
1. If the search term has not changed, a blank value will be stored in search object, regardless of the contents of the search box. This causes #694. 
2. The widget is outside the `if/else` block, so it's always refreshed, even if the search term hasn't changed, so (2) above is not accomplished.
The reason this doesn't crop up more often is …
> Fix bug with host search where search text would be ignored.

- pycue/opencue/wrappers/frame.py
- pycue/opencue/wrappers/job.py
- pycue/opencue/wrappers/layer.py
The new method only exposes an existing feature from job_pb2 to api users in the job, frame and
layer wrappers.
> Add method addRenderPartition to api wrappers

- cuegui/cuegui/CueJobMonitorTree.py
Closing a tab that has jobs on a treeView causes the updated function to
access a non-existing object
> Protect job updates to avoid accessing closed views

- cuebot/src/main/java/com/imageworks/spcue/servant/ManageFrame.java
- cuebot/src/main/java/com/imageworks/spcue/servant/ManageJob.java
Add a `try catch` block to protect the method from being called with
non-existing frames and fix a logic problem on addRenderPartition that
would always return error.
> Protect getRenderPartition call

- ci/build_sphinx_docs.sh
- ci/run_python_tests.sh
- cueadmin/Dockerfile
- cuegui/Dockerfile
- cuesubmit/Dockerfile
- pycue/Dockerfile
- pyoutline/Dockerfile
- requirements.txt
- rqd/Dockerfile
As mentioned in PR #669 
a fresh build that replaces sed hack with 2to3 everywhere, fixes #660
Replaced sed imports with the usage of 2to3 tool everywhere, the changes were mostly in the dockerfiles but there were 1-2 shell scripts too
Added 2to3 in the requrements too
> fixed sed hack with 2to3 

- .github/workflows/packaging-pipeline.yml
- .github/workflows/testing-pipeline.yml
- ci/generate_version_number.sh
https://github.com/AcademySoftwareFoundation/OpenCue/issues/715
The version number isn't being generated correctly when Github Actions runs against the master branch, and I need some additional debugging info to figure out why.
This also fixes an issue I had on my local workstation where an incorrect version number would be generated when the current branch was `master`. Using `git branch --show-current` fixes this, but that method isn't available when using Github Actions on a PR branch, so we need to use the current method as a fallback still.
> Add some debugging info to generate_version_number.sh.

- pyoutline/bin/cuerunbase.py
- pyoutline/outline/backend/cue.py
- pyoutline/outline/util.py
- rqd/rqd/__main__.py
- rqd/rqd/rqcore.py
Handle issues with rqd and pyoutline running on windows environments.
Errors fixed by this PR:
- UnboundLocalError: local variable 'commandFile' referenced before assignment
- AttributeError: 'RunningFrame' object has no attribute 'forkedCommand'
- RuntimeError: Unable to rotate previous log file due to [Error 32]
- com.imageworks.spcue.rqd.RqdClientException: failed to launch frame
Details of the implementation:
- Although Windows lacks an uid, the backend is not prepared to handle jobs without uid. For now we're returning and arbitrary number, which will not impact the job execution down the line.
- SysLogHandler is specific for linux based systems. 
- Windows doesn't implement SIGBUS
- Windows handles file access exceptions under OSError
> Handle Windows compatibility issues

- .github/workflows/packaging-pipeline.yml
- .github/workflows/testing-pipeline.yml
- ci/generate_version_number.sh
- ci/testing-pipeline.yml
#715 
By default, Github's `checkout` action only fetches the last commit. If you're just working with the code that's fine, but if you're querying Git info within the workflow you end up getting some unexpected results. The most important problem was that version numbers were being generated incorrectly, as the version number is determined based on the full Git history (number of commits in master).
> Fetch full Git history in packaging pipeline.

- cuegui/cuegui/FilterDialog.py
Fix FilterDialog create action issue
The call getInteger was renamed to 'getInt' in pyside2, this update fixes the call to work with pyside2
> The call getInteger was renamed to getInt in pyside2

- cuegui/cuegui/CueJobMonitorTree.py
Handle empty groups on CueMonitorTree
In `_getUpdate`, appending IDs for empty groups causes an empty list to be added to the list of job IDs to be processed in the next `_processUpdate` call, which breaks the update and raises the TypeError
> Handle empty groups

- cueadmin/Dockerfile
- cuegui/Dockerfile
- cuesubmit/Dockerfile
- pycue/Dockerfile
- pyoutline/Dockerfile
- rqd/Dockerfile
- rqd/setup.py
Fixes #745 
The base CentOS image uses an old version of `pip`, which can cause errors when trying to upgrade `setuptools`. Upgrade pip in all Docker images to fix this.
This exposes an issue with the dual-Python setup we're using. We rely on calling `pip` directly from the shell, which is not a stable symlink. Upgrading pip from either Python 2 or 3 creates a new symlink and it becomes non-obvious which version you're then operating in. To fix this we switch all images to use `python -m pip` instead of `pip`, which always gives us a version-appropriate pip version.
> Upgrade pip in all Docker images.

- cuegui/cuegui/PreviewWidget.py
#730 
Fix data access to use the wrapper method, which already properly access gRPC object data as needed. I've also cleaned up some of the styling in the surrounding code and added a docstring to the class to make it clear the data types being used.
> Fix incorrect frame data access in Preview widget.

- cuebot/Dockerfile
Fixes #751 
Updating dockerfile for cuebot build to include permissions for VERSION. Fixes issue where build fails on certain systems due to access/permissions issues.
> Cuebot: dockerfile update to set permissions for VERSION file (#751)

- cueadmin/cueadmin/common.py
- pycue/opencue/wrappers/subscription.py
Fix typecast error on -burst option
When % sign was not being provided on the request the api would pass a string to the server, which expects int. Also updated the option description to better explain its format.
> Fix burst typecast

- .github/workflows/release-pipeline.yml
#715 
Adds the job to upload Docker images, switches to pull artifacts from S3 (as added in #753), and amends the Github release to attach those actions.
Having to specify all of the artifacts serially is annoying, but it's the best way I've found so far. We need to have the "create release" and "attach artifacts" steps in the same job so we can access the "create release" step's outputs, and we don't want to create multiple releases, so we can't use a matrix for that job like we do for the Docker image jobs. Hopefully we'll be able to improve on this as Github Actions matures.
> Finish migrating release pipeline to Github Actions.

- .github/workflows/release-pipeline.yml
#715 
Under the new release process, the "last tag" is actually *the release that's currently running*, causing an empty changelog to be generated. So we need to go back one tag further.
Explanation of flags:
- `--skip=1` lets us skip the current tag, displaying the last tag i.e. the last released version.
- `--abbrev=0` provides the plain tag name. Without it you get the tag name plus some other information e.g. `0.4.14-40-g113a57f`. This extra info breaks the `git log` call later. This only happens on tags before the latest one, which is why we didn't need it before.
- `--reverse` to `git log` just reverses the list. IMO the changelog makes more sense when read from oldest to newest.
> Fix bug with changelog generation in release pipeline.

- rqd/rqd/rqutil.py
rqutil.py -- Lines 148 through 153 work on Linux and Windows, however fails on mac. 
Since we can grab IP on Windows & Linux easily we should use that when RQD_USE_IP_AS_HOSTNAME = TRUE
https://github.com/AcademySoftwareFoundation/OpenCue/issues/738
> Updaing Socket code to support Windows.

- cuegui/cuegui/CueJobMonitorTree.py
Fixes an issue on CueJobMonitorTree that would cause selections and collapsed trees to be refreshed in the job's update loop.
> Maintain Selection after update

- cuegui/cuegui/Redirect.py
Fixes the following issue reported by an spi user:
> The redirect cores pane does not appear to do much of anything, the 'include 
> groups' dropdown does not update,  and when changing the show you get this error: 
> ""v1.exception.EntityNotFoundException: Object does not exist. Incorrect result 
> size: expected 1, actual 0"" and it never returns any cores to redirect
> "
> 
> the view should allow us to search for jobs to steal cores from and let us 
> redirect cores to specific jobs. Expected behavior is like cuecommander3
> 
> 1. launch opencuecommander
> 2. select views/plugins > cuecommander >  redirect
> 3. redirect view/pane does not do anything, dropdown lists of show groups does 
> not update, errors are printed in terminal if launched from there.
> Fix Redirect GUI

- .gitignore
Following a pattern I've used in other projects, I've dropped my common environment settings into a `.env` file for easier sourcing in a new shell. Ignore this file so it won't get accidentally committed.
> Ignore top-level .env file.

- README.md
[OpenTimelineIO](https://github.com/PixarAnimationStudios/OpenTimelineIO#opentimelineio) has these neat badges, adding them for OpenCue as well.
> Add badges showing officially supported VFX Reference Platform and Python versions.

- cuebot/src/main/java/com/imageworks/spcue/util/Convert.java
#790 
`BigDecimal` rounding modes have been deprecated and replaced by the `RoundingMode` module. This resolves a `deprecated` warning from the Java compiler.
> Use a non-deprecated rounding mode.

- cuegui/cuegui/AbstractTreeWidget.py
- cuegui/cuegui/FrameMonitor.py
- cuegui/cuegui/HostMonitor.py
- cuegui/cuegui/LimitsWidget.py
- cuegui/cuegui/ProcMonitor.py
- cuegui/cuegui/SubscriptionsWidget.py
- cuegui/cuegui/plugins/AllocationsPlugin.py
- cuegui/cuegui/plugins/LimitsPlugin.py
- cuegui/cuegui/plugins/MonitorCuePlugin.py
- cuegui/cuegui/plugins/MonitorHostsPlugin.py
- cuegui/cuegui/plugins/MonitorJobDetailsPlugin.py
- cuegui/cuegui/plugins/MonitorJobsPlugin.py
- cuegui/cuegui/plugins/ShowsPlugin.py
- cuegui/cuegui/plugins/SubscriptionsPlugin.py
Make tree headers movable and save header positions in settings to be used on next load.
This allows users to customize their cuegui layout to their taste.
> feat: Make tree headers movable

- pycue/opencue/wrappers/frame.py
The dropDepend method was implemented on the backend but not in the API
> Implemented missing drop depend method on the api

- cuegui/cuegui/AbstractWidgetItem.py
- cuegui/cuegui/CueJobMonitorTree.py
Calling time.time() for every row was causing segmentation fault erros while trying to sort big TreeWidgets. Also add a protection to avoid calling the lambda sort for NestedGroup types as it's only implemented for Job types
(cherry picked from commit c7057c16d36ca7bb2b1da2fabe1d6a587817251f)
> Avoid calling time.time() for each row

- cuesubmit/setup.py
- pyoutline/outline/loader.py
- requirements.txt
Fixes #789
Remove `simplejson` as a dependency and rely on the standard `json` library shipped with python. One less dependency to worry about.
> refactor: Remove simplejson dependency

- cuebot/src/main/java/com/imageworks/spcue/dao/oracle/GroupDaoJdbc.java
- cuebot/src/main/java/com/imageworks/spcue/dao/postgres/GroupDaoJdbc.java
- cuebot/src/main/java/com/imageworks/spcue/util/SqlUtil.java
- cuebot/src/test/java/com/imageworks/spcue/test/util/SqlUtilTests.java
#790 
This was throwing a `rawtypes` warning about the use of `Collection` without a type. On further inspection, passing the full list isn't necessary here, as we only need to know the number of values. I've updated the argument type, fixed places in the code where this method is called, and added a unit test for this method.
> Change argument type on SqlUtil.buildBindVariableArray.

- cuebot/src/main/java/com/imageworks/spcue/CueGrpcException.java
- cuebot/src/main/java/com/imageworks/spcue/EntityNotFoundException.java
- cuebot/src/main/java/com/imageworks/spcue/Redirect.java
#790 
Add a randomly generated `serialVersionUID` to all serializable classes. This resolves `serial` lint warnings from the compiler.
> Add serialVersionUID to serializable classes.

- cuebot/src/main/java/com/imageworks/spcue/DispatchHost.java
- cuebot/src/main/java/com/imageworks/spcue/LayerStats.java
- cuebot/src/main/java/com/imageworks/spcue/dispatcher/DispatchQueue.java
- cuebot/src/main/java/com/imageworks/spcue/dispatcher/HostReportHandler.java
- cuebot/src/main/java/com/imageworks/spcue/util/Convert.java
- cuebot/src/test/java/com/imageworks/spcue/test/dispatcher/CoreUnitDispatcherGpuJobTests.java
- cuebot/src/test/java/com/imageworks/spcue/test/dispatcher/CoreUnitDispatcherGpuTests.java
#790 
These casts are redundant, and removing them resolves `cast` lint warnings.
> Remove redundant casts.

- cuebot/build.gradle
Fixes #790 
Now that we've resolved any existing warnings, we can turn this option on. Any lint issues or other warnings will cause the build to fail.
This option is required by the CII badge process.
> Enable -Werror for main and test code.

- .github/workflows/packaging-pipeline.yml
- .github/workflows/release-pipeline.yml
The `set-env` command has been deprecated due to a [security issue](https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/). The new preferred method is to use the [Github environment file](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#environment-files).
> Switch to use new Github environment file.

- cuegui/cuegui/FrameMonitor.py
Solves this issue: Jobs with a large number of frames are grouped into pages 
of 1000 for easier viewing. However, the next page button doesn't update the frames even when clicking refresh.
> Update the FrameSearch page option

- cuebot/build.gradle
This PR is addressing to make the Cuebot build artifact exactly the same, byte for byte, no matter when or where is built by continuous integration. It helps Cuebot binary deployment by detecting only when the build artifact is really updated.
https://docs.gradle.org/current/userguide/working_with_files.html#sec:reproducible_archives
> Set reproducible builds for cuebot jar

- rqd/rqd/__main__.py
- rqd/rqd/rqconstants.py
- rqd/rqd/rqcore.py
- rqd/rqd/rqutil.py
This PR allows RQD to run without root privilege.
- quoting #804 
> it needs to run as root. It's not ideal, and something we should address eventually
- With non-NFS use case (like transferring rendered result to distributed storage), RQD process isn't necessary to become the job user. Thus it doesn't need root privilege at all.
> Introduce RQD_BECOME_JOB_USER to allow to not use root privilege

- cuegui/cuegui/Main.py
- cuegui/cuegui/MainWindow.py
Add menu option to reset to default layout option.
Users sometimes remove widgets by accident, this helps to give them a simple way to restore to defaults.
Closes #832
> Add reset to default layout

- cuebot/src/main/java/com/imageworks/spcue/dao/postgres/JobDaoJdbc.java
JobDetail startTime and stopTime are always 0, because GET_JOB_DETAIL doesn't query ts_started and ts_stopped.
> Fix JobDetail startTime and stopTime

- cuegui/cuegui/ItemDelegate.py
Make the progressbar more useful as a key display bar.
Closes #834
> Display key information in the job's progressbar

- rqd/rqd/rqconstants.py
- rqd/rqd/rqutil.py
This PR allows RQD to use specific IPv4/v6 address or hostname by overriding it via configuration. This helps these use cases.
- The RQD machine has multiple network interfaces.
- The RQD container has a dedicated IPv6 address.
- The RQD machine has static IPv6 address aside from a dynamic IPv6 address.
The behavior won't change without `OVERRIDE_HOSTNAME` settings.
#845 is required to use IPv6 address.
> Introduce OVERRIDE_HOSTNAME to override hostname

- cuebot/src/main/java/com/imageworks/spcue/dao/oracle/WhiteboardDaoJdbc.java
- cuebot/src/main/java/com/imageworks/spcue/dao/postgres/WhiteboardDaoJdbc.java
- cuebot/src/main/java/com/imageworks/spcue/util/CueUtil.java
#801 
Flagged by SonarCloud as a bug.
Arithmetic on integers produces integers by default -- when we set them to fields which are `long` we should make the cast explicit.
> Make explicit casts to long.

- cuebot/src/main/java/com/imageworks/spcue/dispatcher/BookingQueue.java
- cuebot/src/main/java/com/imageworks/spcue/dispatcher/DispatchQueue.java
- cuebot/src/main/java/com/imageworks/spcue/dispatcher/HostReportQueue.java
- cuebot/src/main/java/com/imageworks/spcue/service/JobManagerSupport.java
#801 
When catching `InterruptedException`, you should always either a) rethrow the exception, or b) reinterrupt the current thread (as `InterruptedException` clears the interrupted state) so downstream code can deal with it.
In these cases, it looks like it's best to just reinterrupt the threads so Spring can deal with the interruption as needed.
> Reinterrupt current thread after InterruptedException.

- cuebot/src/main/java/com/imageworks/spcue/service/DependManagerService.java
#801 
`@Transactional` is ignored by Spring on private methods.
> Remove Transactional annotations from private methods.

- cuebot/src/main/java/com/imageworks/spcue/service/JobSpec.java
#801 
Use `.equals` instead of `==` for the string comparison.
> Fix username string comparison.

- .dockerignore
Exclude a few other directories as well that are not needed during
docker builds.
Closes #878
> Add dockerignore so that the sandbox env can be run mutliple times.

- rqd/rqd/rqconstants.py
- rqd/rqd/rqmachine.py
- rqd/tests/rqmachine_tests.py
RQD container build script usually knows which tags should be assigned to the RQD container.
This PR allows the build script can generate `rqd.conf` file with `RQD_TAGS` to set the tags to the RQD.
> Introduce RQD_TAGS for setting tags to RQD host

- pyoutline/outline/backend/cue.py
- pyoutline/outline/layer.py
- pyoutline/tests/json/shell.outline
- pyoutline/tests/json_test.py
Fix #547 
- Layer env can be set from JSON, but it doesn't propagate. Serialize it into XML.
- Fix layer get_env.
> Serialize layer env

- cuegui/cuegui/Utils.py
**Two changes**
line 198 -- Fixing cuewho file dir path
- It is easier to track where we create the `cuewho.who` file to get the current cuewho username by changing the path from
`cuewho.who` to `/shots/%s/home/cue/cuewho.who`, and also the `%s` converted all arguments during string formatting
line 217 -- Fixing subprocess call
- to execute a command `phone username` in a new subprocess and return the output as the var `results`. Testing on python 2.7, If using without the `[]`, subprocess would raise an exception
> Fixing cuewho file dir path and subprocess call

- connectors/prometheus_metrics/Dockerfile
- cueadmin/Dockerfile
- cuegui/Dockerfile
- cuesubmit/Dockerfile
- pycue/Dockerfile
- pyoutline/Dockerfile
- rqd/Dockerfile
Closes #882 
This pins `pip` and `setuptools` to the last python 2 compatible versions in the various Dockerfiles.
This fixes building the sandbox environment.
> fix: Pin pip and setuptools to compatible versions

- pyoutline/outline/config.py
- pyoutline/outline/io.py
Suppress warnings by Python 3.7.
config.py:40: DeprecationWarning: The SafeConfigParser class has been renamed to ConfigParser in Python 3.2. This alias will be removed in future versions. Use ConfigParser directly instead.
io.py:43: DeprecationWarning: invalid escape sequence \d
> Suppress warnings

- cuegui/cuegui/ItemDelegate.py
The `cuegui.Progress` module it references doesn't exist and is causing errors as I set up linting for this code.
According to @larsbijl frame progress isn't fully implemented yet so this can be removed for now.
> Remove ProgressDelegate section handling frame progress.

- cuegui/cuegui/HostMonitorTree.py
- cuegui/cuegui/MenuActions.py
- cuegui/setup.py
- cuegui/tests/MenuActions_tests.py
- requirements.txt
These are not used for most users and aren't part of a standard Linux install
> Remove hinv and pexpect

- cuebot/src/main/java/com/imageworks/spcue/service/JobSpec.java
- cuebot/src/main/resources/application.properties
- cuebot/src/test/java/com/imageworks/spcue/test/service/JobSpecTests.java
- cuebot/src/test/resources/conf/jobspec/jobspec_1_10.xml
- cuebot/src/test/resources/conf/jobspec/jobspec_nonexistent_dtd.xml
- sandbox/docker-compose.yml
Cuebot requires to bind TCP 8080 port for providing http access to Job XML DTD (`http://localhost:8080/spcue/dtd/cjsl-1.9.dtd`.) But it isn't necessary because the http request can be redirected to Jar resource file via `EntityResolver`. This allows to disable http server.
> Redirect DTD http request to the resource file

- cuebot/src/main/java/com/imageworks/spcue/service/AdminManagerService.java
- cuebot/src/main/java/com/imageworks/spcue/service/JobSpec.java
- cuebot/src/test/java/com/imageworks/spcue/test/service/AdminManagerTests.java
- cuebot/src/test/java/com/imageworks/spcue/test/service/JobManagerTests.java
- cuebot/src/test/java/com/imageworks/spcue/test/service/JobSpecTests.java
- cuebot/src/test/resources/conf/jobspec/jobspec_invalid_shot.xml
- cuebot/src/test/resources/conf/jobspec/jobspec_nonexistent_show.xml
Fix #900
- Add validation to show and shot since those conformances are critical because these names are used as log file path.
- Enhance unit tests.
> Validate strings

- rqd/rqd/__main__.py
- rqd/rqd/cuerqd.py
- rqd/rqd/rqconstants.py
- rqd/rqd/rqcore.py
- rqd/rqd/rqmachine.py
- rqd/tests/rqcore_tests.py
- Make GRPC ports available in the settings file as an override
- Remove SPI specific facility checks/overrides hardcoded in RQD
- DEFAULT_FACILITY can now be overridden to set the default facility for a RQD client.
> Make GRPC ports avaiable in settings file as override

- rqd/rqd/rqconstants.py
- rqd/tests/rqconstants_tests.py
- `RQD_TAGS` didn't work due to the method (`getint` vs `get`) in the first place :sweat_smile:
- Added unit tests with mocking rqd.conf
> Fix RQD_TAGS

- pyoutline/etc/outline.cfg
- pyoutline/outline/backend/cue.py
- pyoutline/tests/specver_test.py
- requirements.txt
Fix #918
It allows deploying clients (PyOutline) before updating Cuebot, with specifying spec_version in outline.cfg.
> [PyOutline] Add spec_version

- rqd/rqd/rqconstants.py
- rqd/rqd/rqmachine.py
Unless still used by SPI it seems like a special case we should remove.
> Remove special case for playblast

- cuegui/tests/DependWizard_tests.py
#396 
Add a few unit tests for DependWizard -- job-on-layer, layer-on-job, frame-on-frame. This brings file coverage 21% -> 83%, and CueGUI overall coverage 38% -> 41%.
> Add unit tests for DependWizard.

- pyoutline/tests/specver_test.py
`test_after_init_current` changes global `outline.Outline.current`, eventually it affects other tests badly.
For example, #941 doesn't change Python but failed.
https://github.com/AcademySoftwareFoundation/OpenCue/pull/941/checks?check_run_id=2180764941
Ensure to clear the value.
> Fix PyOutline test

- cuebot/src/main/java/com/imageworks/spcue/dao/HostDao.java
- cuebot/src/main/java/com/imageworks/spcue/dao/oracle/HostDaoJdbc.java
- cuebot/src/main/java/com/imageworks/spcue/dao/postgres/HostDaoJdbc.java
- cuebot/src/main/java/com/imageworks/spcue/service/MaintenanceManagerSupport.java
- cuebot/src/main/resources/conf/spring/applicationContext-service.xml
- cuebot/src/main/resources/opencue.properties
- cuebot/src/test/java/com/imageworks/spcue/test/dao/postgres/HostDaoTests.java
Cuebot automatically deletes hosts when
- It detects the down state on the hosts
- And `maintenance.auto_delete_down_hosts` property is set to `true`
This is very useful when RQD hosts are using dynamic IP address or hostname, some hosts will be never connected again.
> Auto-delete the down state hosts

- cuebot/src/main/java/com/imageworks/spcue/dao/postgres/AllocationDaoJdbc.java
- cuebot/src/test/java/com/imageworks/spcue/test/dao/postgres/AllocationDaoTests.java
`setDefaultAllocation` fails due to type mismatch. fix it.
> org.springframework.jdbc.BadSqlGrammarException: StatementCallback; bad SQL grammar [UPDATE alloc SET b_default = 0 WHERE b_default = 1]; nested exception is org.postgresql.util.PSQLException: ERROR: operator does not exist: boolean = integer
Hint: No operator matches the given name and argument type(s). You might need to add explicit type casts.
> Fix AllocationDao

- pyoutline/outline/loader.py
- pyoutline/tests/json/facility.json
- pyoutline/tests/json_test.py
Allow PyOutline to use `facility` in JSON
{
"name": "shell_command",
"facility": "test_facility",
> PyOutline: Add facility support for JSON

- sandbox/install-client-archives.sh
Fix #925 
After downloading and unzipping an OpenCue release `tar.gz` file, it removes all compiled python files fixing `python setup.py install` error. This fix is needed to execute with success OpenCue's quick-start-mac guide from: https://www.opencue.io/docs/quick-starts/quick-start-mac/ - which fails up until release 0.8.8.
Tested on a mac with python-3.7.9.
> Remove compiled python from tar.gz releases.

- docker-compose.yml
- sandbox/docker-compose.monitoring.yml
Place docker-compose at the root of the project.
Remove some of the variable user needed to setup with defaults.
We can assume a person is running this as a test and not in production
with docker-compose.
process to start is now.
`docker-compose up` in the root of the project.
> Simplify docker compose setup.

- pyoutline/outline/backend/cue.py
- pyoutline/tests/backend/cue_test.py
PyOutline uses `threads` to set `cores` to XML job spec layer element. It's confusing. Allow to use `cores` as well.
> PyOutline: Support layer 'cores'

- ci/run_python_tests.sh
- cuegui/Dockerfile
#964 
Based on updates in their [bug tracker](https://bugs.python.org/issue34095#msg360911), Xvfb no longer supports Python 2. CueGUI tests, when running in headless environments like our CI pipelines, require `xvfb-run` to mimic an X Server for PySide to use.
I've gone through all of the past Xvfb versions available through `yum` and they all present the same bug.
Unfortunately that means, for now at least, we'll need to disable CueGUI automated tests using Python 2.
Python 3 tests still appear to run normally.
> Skip tests needing xvfb-run in Python 2.

- .dockerignore
Cuebot should always generate fresh protobuf code from the protos that were copied in at build time. This happens during the `gradle build` process, but if `src/compiled_protobuf` has code in it already, this code may be reused.
Developer machines may already contain this generated code; if copied into the build machine this can produce unexpected results if generated code is stale.
> Ignore compiled protobuf code in Cuebot docker build.

- cuebot/src/main/java/com/imageworks/spcue/servant/ManageAllocation.java
- cuebot/src/test/java/com/imageworks/spcue/test/servant/ManageAllocationTests.java
Use local `findAllocationDetail` function instead of `adminManager.findAllocationDetail` direct call for gRPC API consistency. All other call sites (delete, setBillable, setName, and setTag) already did that.
> Use findAllocationDetail for setDefault

- cuegui/cuegui/Comments.py
User workflow require checking and editing **existing** comments' subject and body, updated `__textEdited` fn to allow users to edit both.
> Enable editing existing comments

- cuegui/cuegui/Utils.py
Fixed bug with check_call input parameters when cmdList appends '&', if user has the environment variable EDITOR set in shell (for example like nedit), it caused the shell out to fail. Once cmdList is changed to string inputs over list, all editors work including custom overrides like nedit.
> Shellout check_call uses string input

- cuegui/cuegui/EmailDialog.py
Fixed bug with email_body, PySide.QEdit.toPlainText() returns a unicode object which threw an attribute error with toAscii(). Also, encoded MIMEText to handle high bit characters (extended ascii table).
> Encode Cuegui email MIMEText with plain utf-8

- cuegui/cuegui/plugins/LogViewPlugin.py
Bug in pressing the clear button for search text, it did not unhighlight the red text causing the log to be filled with unwanted red text. Changed the `self.matches_to_highlight` to **not** discard the positions of the search text before calling clear_search_data.
> Red text unhighlights once search is cleared

- cuegui/cuegui/FrameMonitorTree.py
A common complaint from our users is that their workflow requires single click frame name selection in the `FrameMonitorTree` to copy to the QtGui clipboard, updated to allow users this capability.
> Copy frame name to middle click clipboard

- pycue/opencue/cuebot.py
Not defining the poll strategy generates a warning message on every fork that includes a opencue environment
**why**
Common source of confusion for users was the appearance of the e-poll strategy warning in the logs when forking, opting to handle the strategy to avoid spamming users.
> Add GRPC_POLL_STRATEGY to avoid spamming users

- cuebot/src/test/java/com/imageworks/spcue/test/dao/postgres/JobDaoTests.java
Looks like this was broken in #924. Not sure how it slipped past the testing pipeline but could be related to the other test weirdness we were seeing in that PR.
> Fix JobDao unit test.

- pycue/opencue/cuebot.py
> E0628 ... ev_posix.cc:227]                   No event engine could be initialized from epoll1
cuegui crashes on macOS because macOS doesn't support `GRPC_POLL_STRATEGY=epoll1`. Skip it on macOS(`Darwin`).
> Fix crash on macOS by GRPC_POLL_STRATEGY=epoll1

- .github/workflows/testing-pipeline.yml
- ci/run_python_lint.sh
- ci/run_python_tests.sh
Linting is currently running as part of one of the Python unit test jobs. This is confusing, it makes people think unit tests are failing, and the output of the combined tests / lint is so large it can be difficult to see the actual source of failure.
Also restructures the linting to avoid use of `cd X && lint && cd ..`. In that model, when the lint check fails it is not caught by the bash `set -e` so the script keeps running but from the wrong directory, which would also create confusing results.
> Split Python linting into its own CI job.

- ci/run_python_lint.sh
When lint errors occur, it can be hard to tell which component the errors occurred in as full file paths aren't included in lint output.
> Add some log messages to run_python_lint.

- cuebot/src/main/java/com/imageworks/spcue/util/FrameRange.java
- cuebot/src/test/java/com/imageworks/spcue/test/util/FrameRangeTests.java
- cuebot/src/test/java/com/imageworks/spcue/test/util/FrameSetTests.java
There was a implementation bug with the logic of the start frame 
incrementing after each Nth step iteration, causing the interleaving
to be incorrect because the step was operating on a subset of the 
frame range and not the entire range for each Nth step. The start 
index needs to remain static after each iter for interleaving to work 
correctly on the entire range. Ex, 1-10:5. N=5, results in 
1,6,3,5,7,9,2,4,8,10 1st iter: N=5, [1,6], 2nd iter: N=2, [1,6,3,5,7,9], 
3rd iter: N=1 [1,6,3,5,7,9,2,4,8,10].
> Keep staggerFrames interleaving start frame static

- cuegui/cuegui/AbstractWidgetItem.py
Bug fix `sortLambda` if statement which only worked for `rpcObject` of type "job" (`if sortLambda and isinstance(other.rpcObject, opencue.wrappers.job.Job`) which failed to call the `sortLambda` for the rest of the `rpcObject` types, this caused an issue with numerical sorting (for example it resorted to text sort and would sort numbered columns like 70000, 7, 6000, 5000, 3, 2). Once changed and all the sort lambda functions are called and work correctly (including the numerical sorting for Allocations, Host, Subscription and Show plugins).
> Sortlambda works on all rpcObject types

- cuegui/cuegui/JobMonitorTree.py
A common minor annoyance we heard from our users is that when scrolling through many jobs (500+), as they scrolled down the list and double clicked on a job to see it's layers, the scroll bar would jump back up to the top, forcing the user to re-scroll back down the list if they needed to view the other jobs in that scope, ideally the scroll position should remain in the most recent position.
**Solution:** Changed scroll position using the `setVerticalBar().setRange(...)` and created a small scroll area between scroll position and the number of jobs monitored.
> Fix scroll bar position from jumping back to the top

- cuegui/cuegui/FrameMonitor.py
Fixes #1005 
In a Python 3 environment, this works fine as-is. However in Python 2 you get the error
```
TypeError: 'PySide2.QtWidgets.QAction.setShortcut' called with wrong argument types:
PySide2.QtWidgets.QAction.setShortcut(long)
Supported signatures:
PySide2.QtWidgets.QAction.setShortcut(PySide2.QtGui.QKeySequence)
```
Adding the explicit use of `QKeySequence` gets this working again in both Python 2 and 3.
> Fix bug in Monitor Job Details due to setShortcut arg type.

- .github/workflows/testing-pipeline.yml
- README.md
- cueadmin/setup.py
- cuegui/setup.py
- cuesubmit/setup.py
- pycue/setup.py
- pyoutline/setup.py
- rqd/setup.py
Now that gRPC and PySide dependencies are updated, I've been able to install and test on newer Python versions i.e. 3.9.
- Run testing pipeline against CY2021 images.
- Update README with new supported Python and Reference Platform versions.
- Update all `setup.py` files with the current supported version list.
> Expand supported Python and VFX Reference Platform versions.

- README.md
In my last PR I added `3.9` but missed the ones in between, which are also supported.
> Fix python badge to list all 3.x versions.

- rqd/rqd/rqnetwork.py
- The exact same as #859 but for RQD
- (It might be nice if we could share some code between PyCue and RQD)
- Delete meaningless For-loop
- `for cuebotHostname in cuebots` → `if len(cuebots) > 0: ... cuebots[0]`
> Intercept grpc.StatusCode.UNAVAILABLE and retry

- pycue/opencue/wrappers/allocation.py
To get GPU stats of allocations.
> Add GPU stats to allocation wrapper API

- rqd/rqd/rqnetwork.py
Fix a bug introduced in #924
- rqnetwork.py numGpus is always 0 😞 
- It can just use `runFrame.num_gpus`.
- Because this code block is working correctly https://github.com/AcademySoftwareFoundation/OpenCue/blob/c22fe12721bed24b814184ea78c5e447b3b6a477/rqd/rqd/rqcore.py#L865-L868
> Fix number of GPU units in RunningFrameInfo

- cuebot/src/main/java/com/imageworks/spcue/dao/postgres/NestedWhiteboardDaoJdbc.java
There was a problem where depending on the order of the hashmap
insertion, nested folders would not show up in the GUI. The issue
was caused by using childrenMap.entrySet which doesn't concern
about order.
To solve this issue the map values were encapsulated in a object
that implements the right sorting based on level, making sure
children paths are processed before their parents.
> Make sure nestedJobWhiteboard is processed in order

- cuebot/src/main/java/com/imageworks/spcue/FrameDetail.java
- cuebot/src/main/java/com/imageworks/spcue/dao/postgres/FrameDaoJdbc.java
Max RSS can exceed `int` range.
(Database schema uses already `bigint`, and gRPC proto also uses `int64`)
Caused by: org.springframework.dao.DataIntegrityViolationException: PreparedStatementCallback; SQL [SELECT frame.*, job.pk_facility,job.pk_show FROM frame,layer,job,show WHERE frame.pk_job = job.pk_job AND frame.pk_layer = layer.pk_layer AND job.pk_show = show.pk_show  AND pk_frame=?]; Bad value for type int : 10733502280; nested exception is org.postgresql.util.PSQLException: Bad value for type int : 10733502280
at org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:104)
at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
at …
> Fix FRAME_DETAIL_MAPPER for Max RSS

- rqd/rqd/rqcore.py
PowerShell exit code may exceed int32 range. For example, `4294901760`. It causes `ValueError` exception here.
https://github.com/AcademySoftwareFoundation/OpenCue/blob/21bfbfe158fdb0e730a80db3ec2134efc15e0366/rqd/rqd/rqcore.py#L218
> ValueError: Value out of range: 4294901760
This PR adds an workaround to avoid the exception, with arbitrary exit codes, which is better than nothing.
> Add workaround for PowerShell Exitcode

- cuebot/src/main/java/com/imageworks/spcue/dispatcher/HostReportHandler.java
- rqd/rqd/rqcore.py
1. The RQD log footer always has an extra space on the separator
- <img width="202" alt="Screen Shot 2021-09-09 at 10 24 15 PM" src="https://user-images.githubusercontent.com/81904/132804776-7836e181-1bfb-4371-8538-8022951e18df.png">
2. Out of memory error message has an extra "MB", like `20480MBMB but the machine only has` 
- https://github.com/AcademySoftwareFoundation/OpenCue/blob/21bfbfe158fdb0e730a80db3ec2134efc15e0366/cuebot/src/main/java/com/imageworks/spcue/dispatcher/HostReportHandler.java#L433
- `KbToMb` already prints `MB` https://github.com/AcademySoftwareFoundation/OpenCue/blob/21bfbfe158fdb0e730a80db3ec2134efc15e0366/cuebot/src/main/java/com/imageworks/spcue/util/CueUtil.java#L207
> Minor log fix

- cuebot/src/main/java/com/imageworks/spcue/dao/ProcDao.java
- cuebot/src/main/java/com/imageworks/spcue/dao/postgres/ProcDaoJdbc.java
- cuebot/src/main/java/com/imageworks/spcue/dispatcher/DispatchSupport.java
- cuebot/src/main/java/com/imageworks/spcue/dispatcher/DispatchSupportService.java
- cuebot/src/main/java/com/imageworks/spcue/dispatcher/HostReportHandler.java
- cuebot/src/test/java/com/imageworks/spcue/test/dao/postgres/ProcDaoTests.java
#924 forgot to update VirtualProc GPU memory usage.
> Update GPU memory usage

- cuebot/src/main/java/com/imageworks/spcue/dao/FrameDao.java
- cuebot/src/main/java/com/imageworks/spcue/dao/postgres/FrameDaoJdbc.java
- cuebot/src/main/java/com/imageworks/spcue/dispatcher/DispatchSupport.java
- cuebot/src/main/java/com/imageworks/spcue/dispatcher/DispatchSupportService.java
- cuebot/src/main/java/com/imageworks/spcue/dispatcher/HostReportHandler.java
- cuebot/src/test/java/com/imageworks/spcue/test/dao/criteria/FrameSearchTests.java
- cuebot/src/test/java/com/imageworks/spcue/test/dispatcher/HostReportHandlerTests.java
- cuebot/src/test/resources/conf/jobspec/jobspec_simple.xml
The current code uses two separate for-loops to update the same frames in HostReportHandler.
It looks like it's not significant, but it doubled the database transactions for no particular reasons, specially with multiple running frames.
- Find frame
- Update memory usage
- Find frame (*redundant*)
- Update LLU time (*can be combined with the memory usage UPDATE*)
This PR will combine those to reduce HostReport handling latency and database load which are big deals with a massive render farm.
- Find frame
- Update memory usage and LLU time
Also this PR will establish a way to test Host Report with running job.
> Combine frame update

- pycue/opencue/api.py
- pycue/tests/api_test.py
pycue has already `find` API but it is under `Limit` wrapper.
https://github.com/AcademySoftwareFoundation/OpenCue/blob/847ee50c1732b268d55cd645d1d7c2d9e9e039da/pycue/opencue/wrappers/limit.py#L42-L43
Which means user needs to get `Limit` instance somehow (`getLimits()` or `createLimit()`) first to find a `Limit`. It is not efficient.
> Add FindLimit to pycue API

- rqd/rqd/rqmachine.py
- rqd/tests/rqmachine_tests.py
The nature of `reserveHT` is creating a CPU-list for `taskset -c`, it should work without Hyper-threading.
But it assumes `hyperthreadingMultiplier` is 2.
This PR allows non-HT machine (for example, VM) can use `taskset -c`.
(Probably, we can add an extra logic for `hyperthreadingMultiplier=3` or more, but I think not worth it for now)
> Fix reserveHT

- cuebot/Dockerfile
Closes #1067
Change the tag from openjdk:11-jrd-slim to openjdk:11-jrd-slim-buster, as the original tag is causing errors in the cuebot build.
These community posts mention the same issue and suggest using the buster tag as a work around.
https://github.com/carlossg/docker-maven/issues/221
https://forums.docker.com/t/multiple-projects-stopped-building-on-docker-hub-operation-not-permitted/92570/14
> Use openjdk:11-jre-slim-buster in Cuebot container

- cuegui/cuegui/JobMonitorTree.py
- cuegui/cuegui/plugins/MonitorJobsPlugin.py
Common complaint from our users is that if they added 1000s of jobs to their previous Job Monitor Tree session, opencuetopia would _**take a very long time**_ to load, especially if the jobs were moved to the historical database since their last session (they would also receive many warnings in the shell which further bogs down the app). 
To avoid the restore lag for such scenarios:
* Only restore jobs from config.ini that were added within the last 3 days.
* Add a timestamp to the config.ini file for each monitored job. Uses the timestamp of when the user added the job to monitor over the job's database `startTime()` because a job could be running on the farm for 3+ days or be dependent on other jobs, meaning a job could have a db start time > 3 (and hence not …
> Only restore jobIds added within last 3 days

- requirements.txt
- rqd/rqd/rqmachine.py
- rqd/winps/setup.py
- rqd/winps/winps.cpp
- Implement native module (`winps`) to traverse process tree of each frame to get RSS (`WorkingSetSize`) and %CPU (the same way as Linux with /proc). The code path will be disabled if the native module is not available.
- Factor out same code (`__updateGpuAndLlu`) from Linux and Windows
> Get RSS and %CPU for Windows

- cuebot/src/main/java/com/imageworks/spcue/dispatcher/Dispatcher.java
- cuebot/src/main/java/com/imageworks/spcue/service/JobSpec.java
This PR will address #1026
For example, it blocks to reserve an entire machine which has 40 cores.
> Delete CORE_POINTS_RESERVED_MAX check logic

- cuebot/src/main/java/com/imageworks/spcue/dao/DispatcherDao.java
- cuebot/src/main/java/com/imageworks/spcue/dao/postgres/DispatchQuery.java
- cuebot/src/main/java/com/imageworks/spcue/dao/postgres/DispatcherDaoJdbc.java
- cuebot/src/main/java/com/imageworks/spcue/dispatcher/CoreUnitDispatcher.java
- cuebot/src/main/java/com/imageworks/spcue/dispatcher/DispatchSupport.java
- cuebot/src/main/java/com/imageworks/spcue/dispatcher/DispatchSupportService.java
- cuebot/src/main/resources/opencue.properties
- cuebot/src/test/java/com/imageworks/spcue/test/dao/postgres/DispatcherDaoFifoTests.java
- cuebot/src/test/java/com/imageworks/spcue/test/dao/postgres/DispatcherDaoTests.java
This PR will address #1059 `Frame scheduling` by adding FIFO scheduling capability.
What I mean by `FIFO scheduling` is `the oldest frame will run first if the priority is the same`, which is commonly expected in job scheduling system.
- Inject `Environment` to `DispatcherDaoJdbc` to set `fifoSchedulingEnabled` variable by `dispatcher.fifo_scheduling_enabled` property. The default value is `false`. So the default scheduling behavior will not change.
- Insert `ORDER BY`s to `FIND_JOBS_BY_SHOW/GROUP` to order/sort if `fifoSchedulingEnabled` is `true`, the highest priority job first, the oldest job next.
- Use `List` instead of `Set` to keep the job order in the SQL Query result.
- Add unittests to make sure the default `fifoSchedulingEnabled` is `false` and the scheduling is not FIFO. If it …
> [Cuebot] Add FIFO scheduling capability

- requirements.txt
psutil 5.6.6 fails to install on Windows due to a compile error. This is fixed in 5.6.7.
> Changed psutil to 5.6.7 due to critical compilation error on Windows

- CODEOWNERS
Per our last TSC meeting, promote @splhack to committer status. We will also need to add them to the opencue-committers group, which I'll do once this is merged.
Also remove the old GSOC-specific permissions which are not needed anymore.
> Add new committer and clean up file.

- cuebot/src/main/java/com/imageworks/spcue/dao/postgres/GroupDaoJdbc.java
Group GPU APIs should have not used CPU Cores check logic
(Those codes were copy-and-pasted in #924)
Also GROUP_DETAIL_MAPPER did not get min/max cores/gpus.
> Fix Group GPU APIs

- cuebot/src/main/java/com/imageworks/spcue/dao/criteria/postgres/HostSearch.java
Bug with cueadmin arg handler -lh, it should allow a substring match for the hosts being searched, but user
was trying `-lh PARTIAL_HOST_NAME -alloc location.general`, api.getHosts uses search.HostSearch.byOptions but Criteria.java sql search was not returning any results, substring in HostSearch.java was calling addPhrase which does NOT do a SQL loose match, changed HostSearch.java to use `addLikePhrase`, this will search substrings in sql (just like JobSearch.java which uses addLikePhrase for SQL substring searches.
> Fix HostSearch substring for loose search

- cuebot/build.gradle
- cuebot/src/test/java/com/imageworks/spcue/test/TestDatabaseSetupPostgres.java
Fixes #1086.
The version of the opentable Postgres we were using was not self-contained, and needed files are not available on newer versions of macOS. See https://github.com/AcademySoftwareFoundation/OpenCue/issues/1086#issuecomment-1006886659 for more details.
> [cuebot] Switch to new version of embedded Postgres for unit tests.

- cuebot/src/main/java/com/imageworks/spcue/dispatcher/FrameCompleteHandler.java
- cuebot/src/main/resources/opencue.properties
- cuebot/src/test/java/com/imageworks/spcue/test/dispatcher/FrameCompleteHandlerTests.java
- cuebot/src/test/java/com/imageworks/spcue/test/dispatcher/HistoryControlTests.java
- cuebot/src/test/resources/conf/jobspec/jobspec_gpus_test.xml
Fix #1081
- Introduce `depend.satisfy_only_on_frame_success` property to keep the current behavior by default (`true`)
- Setting `false` to `depend.satisfy_only_on_frame_success` makes Frame and Layer dependency (`*_ON_FRAME` and `*_ON_LAYER`) behavior same with Job dependency (`*_ON_JOB`), satisfies regardless the result, succeeded or failed.
> [Cuebot] Fix inconsistent depend behavior

- rqd/rqd/rqmachine.py
[winps](https://github.com/AcademySoftwareFoundation/OpenCue/tree/master/rqd/winps) stores %CPU to `stat["pcpu"]` in a range of `0.0` to `1.0`.
And `1.0` means that the all of the total CPU cores are 100% busy.
So it is supposed to be multiplied with the number of total CPU cores (x100) to align with the Linux implementation.
E.g. if the number of total cores is 8,  needs to multiply by 800.
> Fix %CPU for Windows

- cuesubmit/cuesubmit/Config.py
- cuesubmit/tests/Config_tests.py
- pycue/tests/config_test.py
Advances #785 
Matches config standardization described in #785. This was implemented for PyCue in #972.
CueSubmit already uses the standard `<COMPONENT>_CONFIG_FILE` format, so this just adds support for automatically loading config from `~/.config/opencue/cuesubmit.yaml` if it exists.
> [cuesubmit] Standardize config env var and paths.

- pyoutline/outline/config.py
- pyoutline/tests/config_test.py
Advances #785 
Matches config standardization described in #785. This was implemented for PyCue in #972.
Add new ways to define config which will be used by the `outline` libarary:
* `OUTLINE_CONFIG_FILE` can be used to point to a custom config file.
* `~/.config/opencue/outline.cfg` is used as a default path for a custom config (this uses `%APPDATA%` on Windows).
* Existing config methods i.e. `OL_CONFIG` are still supported.
This also adds some unit tests for the `outline.config` module.
> [pyoutline] Standardize config env vars and paths.

- sandbox/flyway.Dockerfile
Fixes #1101
Fixes #1066 
Upgrade Flyway to a more recent version. Also fixes an issue using `yum` on more recent versions of CentOS.
> Upgrade Flyway and fix Dockerfile.

- cuebot/src/main/java/com/imageworks/spcue/util/CueUtil.java
- cuebot/src/main/resources/opencue.properties
`CueUtil` used variable for `smtp_host` value which made set up for mailing to be complicated.
Creates `smtp_host` variable in `opencue.properties` in order for mailing to work. This will allow for anyone to set up mailing on any custom system.
> Set smtp_host as env variable

- rqd/rqd/__main__.py
- rqd/rqd/cuerqd.py
- rqd/rqd/rqconstants.py
- rqd/rqd/rqcore.py
- rqd/rqd/rqdservicers.py
- rqd/rqd/rqmachine.py
- rqd/rqd/rqnetwork.py
- rqd/rqd/rqnimby.py
- rqd/rqd/rqswap.py
- rqd/rqd/rqutil.py
- rqd/tests/rqcore_tests.py
- rqd/tests/rqmachine_tests.py
- rqd/tests/rqnimby_tests.py
Refactor Nimby to a Factory, now has two modes, Select and Pynput. Windows hosts will activate the Pynput mode by default. Fixed Nimby lock override, revamped logging removed print statements. 
Nimby lock was reverting irregardless if the user was using the desktop, turning Nimby into a Factory for Windows capability.
> Fix NIMBY lock and refactor Nimby to Factory

- cuebot/src/main/java/com/imageworks/spcue/service/JobSpec.java
Environment variables set to parent jobs can be useful for post job frames.
We have a scenario where post jobs require having access to the same environments from the parent. As post_jobs are use to run postProcess jobs, it's invisible to pyoutline module developers that those layers will be passed to a different job (_post_job_), so they expect to have the same environment as the job they are binding postProcess layers to. 
The change simple copies all environment variables set at the spec level to the postJob object.
> Post jobs should inherit parent environment variables

- cuebot/src/main/java/com/imageworks/spcue/dao/DispatcherDao.java
- cuebot/src/main/java/com/imageworks/spcue/dao/postgres/DispatchQuery.java
- cuebot/src/main/java/com/imageworks/spcue/dao/postgres/DispatcherDaoJdbc.java
- cuebot/src/main/resources/opencue.properties
- cuebot/src/test/java/com/imageworks/spcue/test/dao/postgres/DispatcherDaoFifoTests.java
- cuebot/src/test/java/com/imageworks/spcue/test/dao/postgres/DispatcherDaoTests.java
Large studios with multiple shows and nodes can experience resource starving in smaller shows due to the priority model
Adds a scheduler_mode option to choose between `BALANCED`, `PRIORITY_ONLY` and `FIFO`. 
- PRIORITY_ONLY was the default mode
- FIFO replaces the property fifo_scheduling_enabled and uses its logic
- BALANCED described bellow
The new mode (BALANCED) uses a formula that makes sure smaller jobs don't get starved by large jobs and also takes into account the time a job has been waiting in the queue. This mode also disregards the layer_limit feature for performance implications. The formula takes into account the number of required cores and the time the job has been waiting on queue.  
Formula: …
> Add balanced mode to dispatch query

- cuegui/cuegui/plugins/MonitorJobsPlugin.py
Simplifies check in _regex_loadJobsHandle, if substring is not None, then load current matching jobs.
> Swap RE with empty string in MonitorJobPlugin

- pycue/opencue/cuebot.py
Disabling Pylint to support machines running older Py versions which throw exceptions on string formatting.
> Cuebot setChannel log supports old Python versions

- cuegui/cuegui/JobMonitorTree.py
- cuegui/cuegui/MenuActions.py
- cuegui/cuegui/plugins/MonitorJobsPlugin.py
- cuegui/tests/MenuActions_tests.py
As per users' request, migrating a job grouping feature from the old cue. 
Kill dependent will suggest killing dependent job every time a job with dependencies gets killed. Group dependents adds a checkbox to cuetopia to allow grouping dependent jobs in the JobMonitor treeView.
> Add kill dependent and group dependent features

- cuebot/src/main/java/com/imageworks/spcue/util/JobLogUtil.java
- cuebot/src/main/resources/opencue.properties
- cuebot/src/test/java/com/imageworks/spcue/test/util/JobLogUtilTests.java
- cuebot/src/test/resources/opencue.properties
[Opencue should support different logging paths for Windows and Linux #1096](https://github.com/AcademySoftwareFoundation/OpenCue/issues/1096)
The logging paths now can be different based on OS. The path can be set up by creating a new env variable like this: `log.frame-log-root.[OS]` where `[OS]` is related to `str_os` on the job table. If no environment variable is set up, it will default to the path described in `
cuebot/src/main/resources/opencue.properties` 
This change will allow OpenCue to be more adaptable to any system
The change was tested using unit tests and by running docker image.
> Support different logging paths based on OS

- cuegui/cuegui/CueJobMonitorTree.py
Signed-off-by: Oblet Alexis <alexis@theyard-vfx.com>
- Fix regression on cue monitor view
```bash
Traceback (most recent call last):
File "/tmp/OpenCue/cuegui/cuegui/CueJobMonitorTree.py", line 562, in contextMenuEvent
self.__menuActions.jobs().addAction(menu, "setMinGpu")
File "/tmp/OpenCue/cuegui/cuegui/MenuActions.py", line 139, in addAction
info = getattr(self, "%s_info" % actionName)
AttributeError: 'JobActions' object has no attribute 'setMinGpu_info'
```
> [cuegui] fix cue monitor gpu min/max

- cuebot/src/main/java/com/imageworks/spcue/dao/postgres/WhiteboardDaoJdbc.java
LluTime field is missed In WhiteboardDaoJdbc.FRAME_MAPPER.
> Fix: missed LluTime in WhiteboardDaoJdbc.FRAME_MAPPER

- rqd/deploy/rqd3_init.d
- rqd/rqd/cuerqd.py
- rqd/rqd/rqconstants.py
- rqd/rqd/rqcore.py
- rqd/rqd/rqmachine.py
- rqd/rqd/rqnetwork.py
- rqd/rqd/rqnimby.py
The shutdown process was changed to cleanly stop the process when shutdown-now is requested.
Pynput is now the default mode for nimby checks and the factory builder returns NOP if the
library is not installed on the environment.
(cherry picked from commit 3389d0f219d599d336987ac589c9be4f0b945783)
With this fix, I have not being able to reproduce [#1118](https://github.com/AcademySoftwareFoundation/OpenCue/issues/1118)
> Rqd shutdown and nimby pynput as default

- cuegui/cuegui/Redirect.py
- cuegui/cuegui/Utils.py
Improve plugin's usability, as per users' requests for the following functionality:
- column sorting, new columns LLU and last log line, running cores for a job, increase ProcTime hours, safety checks prior to redirecting so not to kill target frames, indication of redirect completion, ability to select jobs to add to Job Monitor Tree, adding max core filter, show job's pending frames, added error handling. 
Refactored code to follow PEP 8, following predominate casing type and not use mixed casing.
> Add new features to Redirect plus revamp existing

- cuegui/cuegui/CueJobMonitorTree.py
- cuegui/cuegui/MenuActions.py
- cuegui/tests/MenuActions_tests.py
When moving a lot of jobs to a different cue group, the confirmation popup cuts off at the bottom, changed to an expandable dialog with a scrollbar to allow user to view large number of jobs.
> MonitorCue displays all jobs/groups to move

- cuegui/cuegui/FrameMonitorTree.py
- cuegui/cuegui/JobMonitorTree.py
- cuegui/cuegui/LayerMonitorTree.py
Motivation for disabling using local cores in cuetopia by default (i.e. artist desktops) from rendering was due to firstly, to mitigate slowness affecting artists due to system and network configurations for other services running on the desktop, historically the congestion caused slowness to the artist experience, and decided to avoid this chance for reintroducing congestion. Secondly, due to production management of render farm allocations per shows. Leaving the option to "opt in" and allow users to set the flag: `AllowDeeding=1` in the config file read by cuegui.
- Set AllowDeeding=1 in general config to be able to use local cores
- Use Local Cores option disabled by default
> Create feature flag to allow deeding

- cuegui/cuegui/JobMonitorTree.py
This line shouldn't have been included in #1115 and it fixes the issue mentioned in this comment:
https://github.com/AcademySoftwareFoundation/OpenCue/pull/1139#issuecomment-1116068586
> Remove invalid menu action

- cuegui/cuegui/JobMonitorTree.py
- cuegui/cuegui/plugins/MonitorJobsPlugin.py
- Fixes #1121
- Fixes #1122 
- Fixes #1123 
- Fix previous regressions
- Improve cuegui monitor filter job
- Allow regex usage in any case
- Clear all jobs before new job, this is what to expect when doing a new search
- Save LoadFinished setting in cuetopia preference file
> [cuegui] fix job monitor filter behavior

- cuegui/cuegui/Utils.py
We noticed that last Last Line column was broken on Frame Monitor when running on Python 3. The problem was that you cannot seek with negative integer when reading file default.
Instead of reading file in default manner, we now use binary mode which allows for negative seeking. This fixes reading the log file and hence fixes Last Line.
> Open log files in binary mode for Python 3 comp

- cuebot/src/main/java/com/imageworks/spcue/servant/ManageJob.java
- cuebot/src/main/java/com/imageworks/spcue/servant/ManageLayer.java
- cuebot/src/main/java/com/imageworks/spcue/servant/ServantUtil.java
- cuebot/src/main/resources/opencue.properties
Retrying a frame in a finished job will cause the frame to go back into the waiting state and the job will return to the cue. This even bypasses checks on duplicate job names, so two jobs with the same name can be running at the same time. Hence, it should be disallowed to retry frames on finished jobs, and the finished jobs should be read only.
Endpoints that edit layers or frames now check whether or not the job is finished. If it is finished, then an error is returned. This will make sure the job is readonly from cuebot side.
> cuebot: Make frames and layers readonly after job is done

- .gitignore
Signed-off-by: Mark Sisson <5761292+marksisson@users.noreply.github.com>
Fixes #1206
direnv (https://github.com/direnv/direnv) can be used for local developer workflow enhancements.  direnv uses .envrc file for configuration.  Because .envrc is usually specific to a developer workflow, it is generally not committed.
> add .envrc to .gitignore

- cuebot/src/main/java/com/imageworks/spcue/dao/postgres/ShowDaoJdbc.java
- cuebot/src/main/resources/opencue.properties
Fixes #1205 caused by #1151 
The recently introduced PR #1151 ended up changing the default behaviour of the system, where shows would only be marked as inactive manually. This PR keeps the functionally but adds a new property entry to set the number of days a show needs to be stale (No new jobs) to be marked as inactive and sets the default to -1, which deactivates the feature.
> Add a new property max_show_stale_days to control show expiration rule

- pycue/opencue/wrappers/host.py
When you attempt to change allocation of a hoist with running cores, cuebot will throw an error that is not handled properly on cuegui side. This will render the application unusable until you relaunch it. 
When we make a cuebot call, there is a second layer for exception that will take every possible exception. Just like with `CueException`, an error message will appear with explanaition and the user can continue using the application after pressing OK. This will make sure it takes into account any unexpected error thrown by cuebot.
> cuebot: Handle exceptions when moving hosts with running cores

- cuebot/src/main/java/com/imageworks/spcue/dao/postgres/DispatchQuery.java
- cuebot/src/main/java/com/imageworks/spcue/dao/postgres/FilterDaoJdbc.java
- cuebot/src/main/java/com/imageworks/spcue/dao/postgres/JobDaoJdbc.java
- cuebot/src/main/java/com/imageworks/spcue/dao/postgres/ShowDaoJdbc.java
- cuebot/src/test/java/com/imageworks/spcue/test/dao/postgres/LayerDaoTests.java
Fixes #1221
Some SQL query strings were missing spaces and, when appending the strings together, the resulting query had syntax issue.
The main issue was in `cuebot\src\main\java\com\imageworks\spcue\dao\postgres\JobDaoJdbc.java:948` where we had this code:
```java
"job_stat.int_waiting_count != 0" +
"AND " +
```
Which would result with that faulty string: `job_stat.int_waiting_count != 0AND`.
Then I searched in the code if there were other issues like this one and found a few.
See also this message in the mailing-list: https://lists.aswf.io/g/opencue-user/topic/95205474#494
> fix: some SQL queries were malformed

- ci/run_gui_test.sh
- ci/run_python_tests.sh
- cuegui/tests/MenuActions_tests.py
- cuegui/tests/Utils_tests.py
Recently CueGUI unit tests have been crashing intermittently on GitHub because of some issue during `xvfb-run` shutdown:
```
----------------------------------------------------------------------
Ran 209 tests in 4.394s
OK
<cuegui.MenuActions.JobActions object at 0x7f61ae684f70>
/usr/bin/xvfb-run: line 181:   259 Segmentation fault      (core dumped) DISPLAY=:$SERVERNUM XAUTHORITY=$AUTHFILE "$@" 2>&1
```
Unit tests are passing, but because of that segfault the whole pipeline is showing as failed.
I've tried to debug the segfault without any luck, so I'm resorting to creating a wrapper script that can handle this instead.
> Add wrapper script for cuegui tests.

- .github/workflows/packaging-pipeline.yml
- .github/workflows/release-pipeline.yml
- .github/workflows/sonar-cloud-pipeline.yml
- .github/workflows/testing-pipeline.yml
- cuebot/src/main/resources/conf/ddl/postgres/migrations/V15__Add_min_memory_increase_service.sql
CI pipelines are functioning but producing several warnings about deprecated features we're using.
* Upgrade to `actions/checkout@v3` which uses Node 16.
* Upgrade to `docker/build-push-action@v3`.
* Replace deprecated `set-output` with new `$GITHUB_OUTPUT` env var. This uses a new method for protecting multiline strings.
* Replace `jitterbit/get-changed-files@v1` with `tj-actions/changed-files@v35`.
> Replace deprecated CI actions.

- ci/run_python_tests.sh
- requirements.txt
Installing dependencies is currently failing for Python 2:
```
Collecting evdev>=1.3; "linux" in sys_platform
Downloading evdev-1.6.1.tar.gz (26 kB)
ERROR: Command errored out with exit status 1:
command: /usr/local/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-6TVjAa/evdev/setup.py'"'"'; __file__='"'"'/tmp/pip-install-6TVjAa/evdev/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-bH2XrD
cwd: /tmp/pip-install-6TVjAa/evdev/
Complete output (6 lines):
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/tmp/pip-install-6TVjAa/evdev/setup.py", line 103
cmd = …
```
> Lock evdev dependency for Python 2.

- rqd/rqd/rqnetwork.py
Currently if `CUEBOT_HOSTNAME` is empty, RQD fails with a non-obvious networking error.
If the env var is not set at all, RQD will use localhost. But it's possible to set the env var to an empty string, especially if you're using Docker, so we should handle this case.
> Raise exception during startup if CUEBOT_HOSTNAME is empty.

- samples/rqd/blender/Dockerfile
- samples/rqd/blender/blender2.79-docker/Dockerfile
PR related email thread linked [here](https://lists.aswf.io/g/opencue-dev/topic/blender_plugin_development/96778170?p=,,,20,0,0,0::recentpostdate/sticky,,,20,2,0,96778170,previd%3D1675788277614512701,nextid%3D1670450402484811691&previd=1675788277614512701&nextid=1670450402484811691).
Updates the Blender version in sample Dockerfile to latest LTS release: v3.3
This change was made to complement the upcoming OpenCue Blender addon. Related discussion: https://github.com/AcademySoftwareFoundation/OpenCue/issues/312
> Update blender version on sample Dockerfile

- cuebot/build.gradle
Our Docker images uses `gradle build --info` to build Cuebot and run tests. `--info` produces a lot of useful output, but by default it includes many `STANDARD_OUT` messages from various tests. These messages are not useful, and they clutter up the test logs making it hard to find test failures when they happen.
Define `testLogging` in `build.gradle` to only show failure message when using `--info`.
`--debug` will enable logging of all messages if this is needed for some reason.
> Configure test logging for gradle --info and --debug.

- cuesubmit/Dockerfile
- pyoutline/Dockerfile
> Remove obsolete pyoutline subdir from Dockerfiles.

- rqd/rqd/rqconstants.py
- rqd/rqd/rqcore.py
- rqd/tests/rqcore_tests.py
Some tools don't have timestamp intergrated into their logging format, which makes it hard to identify what steps on a process might be slower than normal. The simpler solution is to change the logging format on these tools, but that's not always possible. 
To overcome the challange mentioned above, a new feature was made available to automatically prepend a timestamp to every rqlog line. This feature can be turned on/off using the constant RQD_PREPEND_TIMESTAMP.
> Prepend every rqd log line with a timestamp 

- rqd/rqd/rqmachine.py
https://github.com/AcademySoftwareFoundation/OpenCue/issues/1307
Before, `Machine._getStatFields()` was always returning [None. None] as the first 2 values, which were used later for `statm_size` and `statm_rss` and would always fail.
> Fix reading stats from /proc/{pid}/statm

- cuegui/cuegui/AbstractTreeWidget.py
- cuegui/cuegui/JobMonitorTree.py
When the option group dependent is checked, jobs without dependency are being omitted.
> [cuegui] Bug fix missing jobs on MonitorJobs

- rqd/Dockerfile
- rqd/rqd/rqconstants.py
https://github.com/AcademySoftwareFoundation/OpenCue/issues/1301
Building and running RQD on docker results in a `ERROR:rqd.rqnimby:Failed to import pynput` caused by `ImportError: this platform is not supported`. 
This is caused by `pynput` expecting an X11 server for the GUI which docker does not have or require. 
Further details referenced in the pynput platform limitations [doc](https://pynput.readthedocs.io/en/latest/limitations.html).
This was resolved via the following steps:
1. Amend **rqconstants.py** to accept `USE_NIMBY_PYNPUT` changes via rqd.conf
2. Update the RQD Dockerfile to setup rqd.conf configuration during setup as described [here](https://www.opencue.io/docs/other-guides/configuring-openc …
> Fix pynput import error in RQD docker

- samples/rqd/blender/Dockerfile
Originally included in PR https://github.com/AcademySoftwareFoundation/OpenCue/pull/1311 then separated.
Adds the Blender install directory in Dockerfile to PATH environment variable for global accessibility.
> Add Blender install location to PATH env variable

- cuebot/src/main/java/com/imageworks/spcue/FrameInterface.java
- cuebot/src/main/java/com/imageworks/spcue/dao/FrameDao.java
- cuebot/src/main/java/com/imageworks/spcue/dao/HostDao.java
- cuebot/src/main/java/com/imageworks/spcue/dao/postgres/FrameDaoJdbc.java
- cuebot/src/main/java/com/imageworks/spcue/dao/postgres/HostDaoJdbc.java
- cuebot/src/main/java/com/imageworks/spcue/dao/postgres/ProcDaoJdbc.java
- cuebot/src/main/java/com/imageworks/spcue/dispatcher/DispatchSupport.java
- cuebot/src/main/java/com/imageworks/spcue/dispatcher/DispatchSupportService.java
- cuebot/src/main/java/com/imageworks/spcue/dispatcher/Dispatcher.java
- cuebot/src/main/java/com/imageworks/spcue/dispatcher/FrameCompleteHandler.java
- cuebot/src/main/java/com/imageworks/spcue/dispatcher/HostReportHandler.java
- cuebot/src/main/java/com/imageworks/spcue/dispatcher/commands/DispatchRqdKillFrameMemory.java
- cuebot/src/main/java/com/imageworks/spcue/service/HostManager.java
- cuebot/src/main/java/com/imageworks/spcue/service/HostManagerService.java
- cuebot/src/main/resources/conf/spring/applicationContext-service.xml
- cuebot/src/main/resources/opencue.properties
- cuebot/src/test/java/com/imageworks/spcue/test/dao/postgres/HostDaoTests.java
- cuebot/src/test/java/com/imageworks/spcue/test/dispatcher/FrameCompleteHandlerTests.java
- cuebot/src/test/java/com/imageworks/spcue/test/dispatcher/HostReportHandlerGpuTests.java
- cuebot/src/test/java/com/imageworks/spcue/test/dispatcher/HostReportHandlerTests.java
- cuebot/src/test/resources/conf/jobspec/jobspec_multiple_frames.xml
- cuebot/src/test/resources/opencue.properties
- rqd/rqd/rqdservicers.py
- rqd/rqd/rqnetwork.py
The current logic relies on hardcoded values which are not suitable for large hosts. The new logic takes into account the size of hosts and also tries to be more aggressive with misbehaving frames.
Prevent host from entering an OOM state where oom-killer might start killing important OS processes. The kill logic will kick in one of the following conditions is met:
- Host has less than `OOM_MEMORY_LEFT_THRESHOLD_PERCENT` memory available
- A frame is taking more than `OOM_FRAME_OVERBOARD_PERCENT` of what it had reserved For frames that are using more than they had reserved but not above the threshold, negotiate expanding the reservations with other frames on the same host.
Additional observations:
- Setting `OOM_FRAME_OVERBOARD_PERCENT` to -1 will turn off the frame overboard protection …
> Oom protection

- docs/conf.py
- docs/requirements.txt
- Update Sphinx version to 5.0.0 on docs/requirements.txt
- Change docs/conf.py to use language = 'en'
> Update Sphinx version

- cuegui/cuegui/JobMonitorTree.py
- cuegui/cuegui/plugins/MonitorJobsPlugin.py
- pycue/opencue/api.py
- Check if regex expression is empty before querying
- Fix JobMonitorTree getJobs call
> Fix GUI not updating bugs

- rqd/rqd/rqcore.py
Fixes https://github.com/AcademySoftwareFoundation/OpenCue/issues/1310
When running a `mayabatch.exe` command in RQD on Windows, the application errors out, saying it's unable to start correctly. It turns out `mayabatch.exe` requires the `SYSTEMDRIVE` environment variable to be set on Windows machines. After adding this env var manually, `mayabatch.exe` runs as expected.
This change will add `SYSTEMDRIVE` to the default list of environment variables that will be copied over to the subprocess on Windows RQD machines. This will also solve the problem of Maya Render jobs failing out of the box on Windows machines when launching from CueSubmit.
> [rqd] Add SYSTEMDRIVE to env var list for Windows machines

- cuebot/src/main/java/com/imageworks/spcue/dao/postgres/DispatchQuery.java
- Fix the where clause in the find_jobs_by_show queries (FIND_JOBS_BY_SHOW_PRIORITY_MODE and FIND_JOBS_BY_SHOW_BALANCED_MODE)
- Remove duplicate PK check "job_resource.pk_job = job.pk_job" that is the same as "job.pk_job = job_resource.pk_job"
> [cuebot] Fix queries find_jobs_by_show

- pycue/opencue/search.py
- pycue/tests/api_test.py
When using methods like opecue.api.getJobs and supplying wrong parameters such as ids instead of id, method returns all jobs on the farm. Instead, exception should be thrown in search.py::_setOptions to clearly state that the parameter supplied was wrong.
Raises error on pycue side (in search.py) when the parameter given is incorrect, i.e. ids instead of id. In case of empty criteria, use empty criteria. So in the case of searching for jobs with empty criteria, all jobs will be returned.
> pycue: Raise error if searching with incorrect parameter

- .gitignore
- cuegui/cuegui/Comments.py
- cuegui/cuegui/ServiceDialog.py
- cuegui/tests/Comments_tests.py
- cuesubmit/cuesubmit/ui/Widgets.py
- pycue/opencue/wrappers/service.py
- pycue/opencue/wrappers/show.py
Fix unit test issues caused by 65b74fee2702a57a8dd10fb563c007d3963d585e
> Fix comments ui unit tests

- samples/rqd/cuda/Dockerfile
Related to PR https://github.com/AcademySoftwareFoundation/OpenCue/pull/1309.
As discussed in the mail thread [Blender plugin development](https://lists.aswf.io/g/opencue-dev/message/527).
Adds a sample RQD Dockerfile with CUDA supported base image for GPU rendering. 
Tested with new derived RQD Blender image.
Works in combination with [Nvidia Container Toolkit](https://github.com/NVIDIA/nvidia-container-toolkit).
> Add sample RQD Dockerfile with CUDA base image

- cuebot/src/main/java/com/imageworks/spcue/dispatcher/HostReportHandler.java
**Issue**
Render host resources reported on opencue were not accurate with reality. 
Comparing with the cue3 version of HostReportHandler, the verifyRunningFrameInfo was supposed to update the list of frames to only keep what has been verified for the following steps. As grpc objects are immutable, the logic simple kept the full list of frames that may have been canceled, completed or migrated impacting the following calls.
> Fix bug with running frames not being updated

- cuesubmit/cuesubmit/Constants.py
- cuesubmit/cuesubmit/Submission.py
- cuesubmit/tests/Submission_tests.py
https://github.com/AcademySoftwareFoundation/OpenCue/issues/1334
https://github.com/AcademySoftwareFoundation/OpenCue/issues/1264
Adds frame range to the Blender render command in CueSubmit.
Required for when rendering animations.
Related Blender command linked [here](https://docs.blender.org/manual/en/latest/advanced/command_line/render.html#animation).
> Add frame range to Blender command in CueSubmit

- cuebot/src/main/java/com/imageworks/spcue/dispatcher/DispatchSupportService.java
Fixes #1129
Simple change to replace the "FRAME_END" variable, acknowledging the chunk size by selecting the minimum between the last frame and last frame in the chunk.
> Fix end frame replacement to acknowledge the chunk size.

- sandbox/flyway.Dockerfile
https://github.com/AcademySoftwareFoundation/OpenCue/issues/1340
GPG key issue while installing packages also results in `docker compose up` failing, leading to issues while developing integration tests https://github.com/AcademySoftwareFoundation/OpenCue/pull/1309#issuecomment-2145509478.
Updates base image to almalinux v9.
> Update flyway dockerfile base image

- cuebot/src/main/java/com/imageworks/spcue/dispatcher/AbstractDispatcher.java
- cuebot/src/main/java/com/imageworks/spcue/dispatcher/BookingQueue.java
- cuebot/src/main/java/com/imageworks/spcue/dispatcher/CoreUnitDispatcher.java
- cuebot/src/main/java/com/imageworks/spcue/dispatcher/DispatchSupport.java
- cuebot/src/main/java/com/imageworks/spcue/dispatcher/DispatchSupportService.java
- cuebot/src/main/java/com/imageworks/spcue/dispatcher/HealthyThreadPool.java
This change is an effort to increase dispatch throughput
By merging both actions into a single dispatcher function they get executed on the same transaction on the database.
> Merge startFrame and reserveProc in a single transaction

- cuebot/src/main/java/com/imageworks/spcue/dao/DispatcherDao.java
- cuebot/src/main/java/com/imageworks/spcue/dao/postgres/DispatcherDaoJdbc.java
- cuebot/src/main/java/com/imageworks/spcue/dispatcher/CoreUnitDispatcher.java
- cuebot/src/main/java/com/imageworks/spcue/dispatcher/DispatchSupport.java
- cuebot/src/main/java/com/imageworks/spcue/dispatcher/DispatchSupportService.java
- cuebot/src/test/java/com/imageworks/spcue/test/dao/postgres/DispatcherDaoFifoTests.java
- cuebot/src/test/java/com/imageworks/spcue/test/dao/postgres/DispatcherDaoTests.java
Changes made it so that dispatchJobs are saved as a List to ensure the order is kept on FIFO mode.
It was observed that using a List might have some performance implications. 
To avoid the risk of impacting performance a LinkedHashSet can be used as the implementation for Set to keep Set's
behaviour when it comes to performance and deduplication but also keeping the order of insertion.
> Partially revert changes on 686d55e1 to use Set

- cuebot/src/main/java/com/imageworks/spcue/dao/postgres/HostDaoJdbc.java
- cuebot/src/main/java/com/imageworks/spcue/dao/postgres/ProcDaoJdbc.java
- cuebot/src/main/java/com/imageworks/spcue/dispatcher/AbstractDispatcher.java
- cuebot/src/main/java/com/imageworks/spcue/dispatcher/CoreUnitDispatcher.java
- cuebot/src/main/java/com/imageworks/spcue/dispatcher/HostReportHandler.java
Reduce log level from `warn` to `info` to reduce the number of messages captured automatically by Sentry (PR coming soon) as Sentry automatically captures warnings. 
The log statements impacted by these changes are not warnings, but common behavior for alternative flows.
> Reduce warning logs

- cuebot/src/main/java/com/imageworks/spcue/service/JobSpec.java
When importing the changes for "add-outputs" I was missing the function to parse the output data from the jobspec.
Follow up to #1361
> Add missing determineOutputs in JobSpec.java

- cuegui/cuegui/MenuActions.py
- cuegui/tests/MenuActions_tests.py
- pycue/tests/wrappers/frame_test.py
Fixed MenuActions' frame.dropDepends bug which only dropped `FRAME_ON_FRAME` dependencies. The DependDoJdbc query only checks `pk_frame_depend_er` and returns empty list if none found, this does not drop any other types of dependencies. Users create complicated dependency types like `FRAME_ON_JOB`, `FRAME_ON_LAYER` etc. that don't always have FRAME_ON_FRAME, so this function failed to drop the dependencies and caused the frame to be "stuck" in Depend state because all depend types need to be satisfied before the frame is allowed to run. 
Changed loop over the different dependencies with `getWhatThisDependsOn()` and drop them one by one, allowing the frame to go in "Waiting" and ready to run.
> Frame dropDepends now drops all depend types

- cuebot/src/main/java/com/imageworks/spcue/dao/postgres/DispatchQuery.java
- cuebot/src/main/java/com/imageworks/spcue/dao/postgres/DispatcherDaoJdbc.java
Using `between 0 and 0` seems to impact which query plan the database is choosing, causing up to 4x speed decrease in the worst case. The current setup chooses which query/arguments to use based on the number of idleGpus so there's some room for improvements in the future here.
This change only impacts the BALANCED scheduling mode as it is the most db intensive mode and seems to be the only one affected.
> Revert booking balanced query for no-gpu

- cuebot/src/main/java/com/imageworks/spcue/dispatcher/Dispatcher.java
- cuebot/src/main/java/com/imageworks/spcue/service/JobSpec.java
If a job requests more memory than MEM_RESERVED_MAX it should be given the maximum amount of memory possible (`MEM_RESERVED_MAX`) and not `MEM_RESERVED_DEFAULT`.  This will give jobs the maximum possible memory if they request more than we can provide.
> Improve max reserved memory handling

- cuebot/src/main/java/com/imageworks/spcue/DispatchFrame.java
- cuebot/src/main/java/com/imageworks/spcue/VirtualProc.java
- cuebot/src/main/java/com/imageworks/spcue/dispatcher/CoreUnitDispatcher.java
- cuebot/src/test/java/com/imageworks/spcue/test/dao/postgres/ProcDaoTests.java
- cuebot/src/test/resources/opencue.properties
A selfish service makes sure its frames have all the host available cores reserved, ensuring this job will not be competing resources with other frames.
Selfish services can be configured on the `opencue.properties` file on `dispatcher.frame.selfish.services`.
> Feature - Selfish services

- cuebot/src/main/java/com/imageworks/spcue/dispatcher/HostReportHandler.java
The free temp logic is not working as intended on Windows, for now it is being disabled.
There is an action item being worked on to document the stage of feature parity between Linux and Windows hosts.
> Ignore Free Temp logic on Windows hosts

- cuebot/src/main/java/com/imageworks/spcue/dispatcher/AbstractDispatcher.java
- cuebot/src/main/java/com/imageworks/spcue/dispatcher/BookingQueue.java
- cuebot/src/main/java/com/imageworks/spcue/dispatcher/CoreUnitDispatcher.java
- cuebot/src/main/java/com/imageworks/spcue/dispatcher/DispatchSupport.java
Simplify docs to better explain what some methods on the dispatch logic do
> Improve docs for some methods

- .github/workflows/testing-pipeline.yml
This is to fix CI/CD checks when running in old images (based on centos 7)
Apparently node was recently forced to be version 20 (from version 16) which does not run on Centos 7.
This PR add an environment variable `ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true` to those checks.
> Fix CI/CD checks that uses old docker images

- cuebot/src/main/java/com/imageworks/spcue/servlet/HealthCheckServlet.java
The health check logic could fail when auto-wiring the environment bean doesn't complete successfully. To avoid relying on autowire, the logic now manually gets the environment bean.
> Fix nullpointer condition on healthcheck

- cuebot/build.gradle
- cuebot/src/main/java/com/imageworks/spcue/PrometheusMetricsCollector.java
- cuebot/src/main/java/com/imageworks/spcue/config/AppConfig.java
- cuebot/src/main/java/com/imageworks/spcue/dao/postgres/DispatcherDaoJdbc.java
- cuebot/src/main/java/com/imageworks/spcue/dispatcher/HostReportHandler.java
- cuebot/src/main/resources/conf/spring/applicationContext-dao-postgres.xml
- cuebot/src/main/resources/conf/spring/applicationContext-service.xml
- cuebot/src/main/resources/conf/webapp/web.xml
- cuebot/src/main/resources/opencue.properties
Adds a new optional module that runs every 60 seconds to collect metrics about the state of thread pools. Also, it collects basic time measurements and counts from dispatchDaoJdbc, which helps assess performance degradation on the system.
Metrics are exposed under /metrics for being collected by a Prometheus instance (the Prometheus server setup is not part of this PR).
A future PR is coming that will include Grafana charts to consume the exposed metrics.
Exposed metrics:
BookingQueue
- cue_booking_waiting_total: Booking Queue number of waiting tasks
- cue_booking_remaining_capacity_total: Booking Queue remaining capacity
- cue_booking_threads_total: Booking Queue number of active threads
- cue_booking_executed_total: Booking Queue number of executed tasks
- cue_booking_rejected_total: …
> Add prometheus metrics collecting

- cuebot/src/main/resources/conf/spring/applicationContext-service.xml
- cuebot/src/test/resources/opencue.properties
The property was repeated in both applicationContext-service.xml and opencue.properties. With this change opencue.properties now becomes the source of truth.
> Use opencue.properties for smtp host

- pycue/opencue/api.py
- pycue/opencue/search.py
- pycue/opencue/wrappers/frame.py
Quality of life changes on the pycue API. 
* [Add paginated search option to api](https://github.com/AcademySoftwareFoundation/OpenCue/commit/73506c9d9d07b17525e08ff651a1c694ce8d5732)
* [Accept wrapper frames on createDependencyOnFrame](https://github.com/AcademySoftwareFoundation/OpenCue/commit/d766af32b649f356a74b9ed87419812353ac0844) This makes it so that both the grpc frame object and the python wrapped object are accepted by the createDependencyOnFrame method.
* [Improve frameStateDisplayOverride function doc](https://github.com/AcademySoftwareFoundation/OpenCue/commit/86e0c68091756a9a11ab32eb85ae3d6076c05a6a)
* [Fix AllocSetBillable call and findAllocation](https://github.com/AcademySoftwareFoundation/OpenCue/commit/1f25f80cae1b58d5722065160d954d783d041e30) The allocation name …
> [pycue] Minor API improvements

- pycue/opencue/wrappers/host.py
New api functions can be used to interactively reboot hosts on the farm and monitor their state. New functions:
* `rebootFarmSafely`: uses the hostSearch module to find hosts and requests a reboot for each of them in groups defined by the arg `group_size`. If `start_time` is provided the function will only target hosts that have `boot_time` > `start_time`
* `monitorRebootFarm` Similar to rebootFarmSafely, but instead of requesting a reboot, it continuosly monitors reboot groups and only finishes when all the hosts on the query have been rebooted.
> [pycue] Add interactive functions to reboot hosts using the api

- cueadmin/cueadmin/common.py
- cueadmin/tests/common_tests.py
- cuegui/cuegui/MainWindow.py
- pycue/opencue/cuebot.py
- pycue/tests/cuebot_test.py
Improve the logic that connects to cuebot to only create the channel once. Previous logic would call setChannel at init and at setFacility.
> Avoid creating the cuebot connection twice

- pycue/opencue/search.py
Searching with criterion `gt` or `lt` returned `TypeError: No positional arguments allowed`. Grpc objects don't accept position arguments.
> [pycue] Fix typeError on criterion search

- cuegui/cuegui/CueJobMonitorTree.py
Fix "Monitor Cue" with incorrect column indexing for "Min" and "Max" columns
- Fix the column indexing on the "addColumn" of class CueJobMonitorTree.
- This bug was introduced after the merge from the pull request "Add multiple GPU support #760 (#924)" on 4/18/22 at 11:45 AM where the following new columns were introduced on the CueJobMonitorTree: "Gpus", "Min Gpus", "Max Gpus", "MaxGpuMem" and the indexing of the columns were wrongly defined.
> Fix "Monitor Cue" with incorrect column indexing

- rqd/rqd/__main__.py
This option was already present on rqd, but was a noop. With this option , the process will run in a new session with stdin reading from /dev/null and stdout and stderr writing to /dev/null with all other file descriptors closed. 
Resolves #153
> [rqd] Add an option to daemonize the process

- cuegui/cuegui/Cuedepend.py
Creating a frame_on_frame dependency from a layer wrapper object only takes one argument (See wrappers/layer.py)
> Remove incorrect parameter on frame_on_frame dependency

- rqd/rqd/rqnimby.py
When a server is marked with `OVERRIDE_NIMBY` but  doesn't have the libraries required to monitor user activity (select or pynput), it should be marked as locked by default. It is safer to assume that a host that was set with `OVERRIDE_NIMBY` is meant to be locked from the start than available to launch jobs.
> [rqd] Default to locked on override_nimby

- rqd/rqd/rqcore.py
The repeated call would cause the host to lock and unlock when rqd starts at desktop mode. 
`onNimbyLock` is already called as part of the `lockNimby` logic so it doesn't need to be called when the application starts.
> [rqd] Remove repeated call to onNimbyLock

- requirements.txt
- rqd/rqd.example.conf
- rqd/rqd/__main__.py
- rqd/rqd/rqconstants.py
Add sentry as an optional integration to collect events from the rqd module.
If SENTRY_DSN_PATH is configured on rqd.conf, a sentry collector will be initialized.
> [rqd] Add sentry support

- rqd/Dockerfile
Issue https://github.com/AcademySoftwareFoundation/OpenCue/issues/1438
Update the Dockerfile base image and perform related changes due to Centos 7 reaching [EOL](https://www.redhat.com/en/topics/linux/centos-linux-eol) on June 30th.
Encountered while updating packaging pipeline with integrations related to PR https://github.com/AcademySoftwareFoundation/OpenCue/pull/1309
> Update RQD Dockerfile to mitigate Centos 7 deprecation

- rqd/rqd/rqmachine.py
- Add the render host's total_mem, total_swap in the initMachineStats function.
- Specify file encoding when opening `/proc/meminfo`.
This logic was removed on 18/Dec/2018 at 11:04 in the pull request: Add build and packaging for RQD. (#48), cfd6e6b5
> [rqd] Fix swap memory on Linux

- cuegui/cuegui/FrameMonitor.py
When jobs have more then 1000 frames it fails to pagenate and throws this :
```python
Traceback (most recent call last):
File "/home/jimmy/repos/OpenCue/cuegui/cuegui/plugins/MonitorJobDetailsPlugin.py", line 96, in handleLayerFilter
self.__monitorFrames.filterLayersFromDoubleClick(names)
File "/home/jimmy/repos/OpenCue/cuegui/cuegui/FrameMonitor.py", line 116, in filterLayersFromDoubleClick
self._filterLayersHandleByLayer(layerNames)
File "/home/jimmy/repos/OpenCue/cuegui/cuegui/FrameMonitor.py", line 413, in _filterLayersHandleByLayer
self._updatePageButtonState()
File "/home/jimmy/repos/OpenCue/cuegui/cuegui/FrameMonitor.py", line 277, in _updatePageButtonState
temp_frames = job.getFrames(temp_search)
^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Job.getFrames() takes 1 positional argument but …
```
> Small fix for pagenation with jobs more than 1000 frames

- cuegui/cuegui/Constants.py
- cuegui/cuegui/FrameMonitorTree.py
- cuegui/cuegui/LayerMonitorTree.py
- cuegui/cuegui/MenuActions.py
- cuegui/cuegui/config/cuegui.yaml
The GUI currently allows editing frames and layers when the job state has completed. This change uses two configuration flags (`finished_jobs_readonly.frame`, `finished_jobs_readonly.layer`) to enable the behavior of making layers and frames readonly upon completion or cancelation. 
When the flags are set to `True` completed jobs can no longer have layers and frames retried, eaten and edited dependencies.
> [cuegui] Make frames and layers readonly when a job is finished

- cuegui/cuegui/Constants.py
- cuegui/cuegui/Main.py
- cuegui/cuegui/config/cuegui.yaml
If `sentry.dsn` is set on cuegui.yaml,  sentry_sdk becomes active and will capture exceptions.
> [cuegui] Add optional sentry support

- cuegui/cuegui/config/darkpalette.qss
Minor UI tweak on `QDoubleSpinBox` elements to avoid lines overlapping each other.
> [cuegui] Fix filter actions overlapping display

- cuegui/cuegui/plugins/LogViewPlugin.py
Logs should be decoded using utf-8 ignoring chars that are not valid. If the decoding process fails, the original content will be displayed
> [cuegui] Decode logs on LogViewPlugin

- rqd/rqd/rqconstants.py
- rqd/rqd/rqcore.py
- rqd/rqd/rqutil.py
When a user has to be created with `useradd`, the user should have the same `uid` and `gid` of the user who created the job. This ensures directories and files created during the job execution have the same permissions.
Not explicitly setting uid and gid causes problems for dockerized rqds trying to write to shared storage volumes mounted in bind mode.
- This PR also contains a minor change to allow overriding the value of `SP_OS` (Constant used to identify a host distro) using the config file.
> [rqd] Set uid and gid when creating user for a job

- cuegui/cuegui/FrameMonitor.py
- pycue/opencue/search.py
- pycue/tests/api_test.py
Reduce the limit of frames queried by FrameSearch by half. It was identified that the GUI becomes unusable with 1000 frames being displayed at the same time. 
FrameMonitor was also updated to stop using a hardcoded value for the limit and start reusing the same value from the API.
> [cuegui] Reduce page size for FrameSearch and reuse config on FrameMonitor widget

- cuegui/cuegui/JobMonitorTree.py
Items removed from the table were not being removed from the cache, causing items to reappear over certain circumstances.
> Fix the wrong call to getObjectKey when removing finished items

- cuegui/cuegui/plugins/StuckFramePlugin.py
- Fix Python2-3 compatibility issues
- Remove TODOs and commented out code
> [cuegui] Minor fixes on StuckFramePlugin

- cuegui/cuegui/LocalBooking.py
The memory sliders were created without a max value and the default was not big enough to represent regular render nodes.
> [cuegui] Set a reasonable max value on the memory slider for the LocalBookings plugin

- cuegui/cuegui/LayerDialog.py
Revert layout changes from #1055 that caused issues with the scroll functionality of the Layout 'dialog'.
> [cuegui] Fix LayerDialog layout scroll

- cuegui/cuegui/Constants.py
- cuegui/cuegui/FrameMonitorTree.py
- cuegui/cuegui/JobMonitorTree.py
- cuegui/cuegui/LayerMonitorTree.py
- cuegui/cuegui/MenuActions.py
- cuegui/cuegui/Utils.py
- cuegui/cuegui/config/cuegui.yaml
- cuegui/tests/Utils_tests.py
Add a right click menu option on Layers, Frames and Jobs to open outputs on a Viewer.
The feature requires setting the viewer command pattern and a regex to extract arguments from outputs. The config file has an example of how to use it for itView. 
```yaml
output_viewer:
action_text: "View Output in Itview"
extract_args_regex: '/shots/(?P<show>\w+)/(?P<shot>\w+)/.*'
cmd_pattern: "env SHOW={show} SHOT={shot} COLOR_IO=/{show}/home/colorspaces.xml OCIO=/{show}/home/config.ocio openrv {paths}"
stereo_modifiers: "_rt_,_lf_"
```
> [cuegui] Output viewer feature

- cuegui/cuegui/Constants.py
- cuegui/cuegui/CueJobMonitorTree.py
- cuegui/cuegui/JobMonitorTree.py
- cuegui/cuegui/MenuActions.py
- cuegui/cuegui/RequestCoresDialog.py
- cuegui/cuegui/config/cuegui.yaml
- cuegui/tests/Constants_tests.py
This new feature adds a new menu action that opens a new `dialog` to request more cores via email for a given job.
The `dialog` is an Email composed where the message is pre-populated with relevant data about the job. Fields, like `to`, `cc` and `bcc`, need to be filled manually. The content of the message is editable.
> [cuegui] Add Request Core Buttons to MenuActions

- cuegui/cuegui/JobMonitorTree.py
**Issue being fixed.**
When values on a columns being used for sorting repeat, jobs with similar values on the given column might change order (bounce) when the job data for other columns updates. 
This fix proposed and implemented by @Samer-sef appends the job `start_time` to the columns sorting key to ensure sorting keys are different enough to prevent bouncing.
> [cuegui] Fix issue with jobs changing order (bouncing) when ordered on the JobMonitor plugin

- cuegui/cuegui/Utils.py
The `findJob` function on Utils.py has to account for the format of jobIds saved on the .ini file which prepends "Job."  to the id.
> [cuegui] Extend jobId regex to accept format saved on user profile

- cuegui/cuegui/MainWindow.py
When starting cuegui with the environment variable CUEBOT_FACILITY set, the interface will select the correct facility if existing on the `Cuebot Facility` menu option.
> [cuegui] Allow pre-selecting CUEBOT_FACILITY with an environment variable

- cuegui/cuegui/ServiceDialog.py
The following separators can now be used to name services:
| / - _
> [cuegui] Enable some separator characters on service name

- cuegui/cuegui/Constants.py
- cuegui/cuegui/MainWindow.py
- cuegui/cuegui/MenuActions.py
- cuegui/cuegui/Utils.py
- cuegui/tests/MenuActions_tests.py
**Rationale**
Users shouldn't be allowed by default to execute destructive actions on jobs they don't own. For "superusers" there should be a simple way to toggle this behavior off. This preference should be saved on the user profile. 
**Implementation details**
This feature checks user permissions before allowing a user to "eat, kill, retry" jobs that they do not own. 
The behavior can be overwritten at: "File -> Enable Job Interaction". This gets saved to the config file and is disabled by
default.
> [cuegui] Limit user actions on alien jobs

- cuegui/cuegui/FrameMonitorTree.py
- cuegui/cuegui/Utils.py
Current logic would fail with `str has no attribute append` when a log editor is configured using cuegui.yaml
> Fix logviewer issue on invalid type

- cuebot/src/main/java/com/imageworks/spcue/dispatcher/DispatchSupportService.java
- cuebot/src/test/java/com/imageworks/spcue/test/util/FrameSetTests.java
#1129 
Fix the frame end resolution of a frame chunk used to fill the place holder `#FRAME_END#`.
The current behavior incorrectly returns the index of the last frame in the frame list instead of its value.
Leverage `FrameSet.get_chunk` method that is already doing all the legwork to get the last frame.
**Related topics**
- https://github.com/AcademySoftwareFoundation/OpenCue/pull/1320
- https://github.com/AcademySoftwareFoundation/OpenCue/pull/367
> [cuebot] fix dispatched frame chunk end frame number

- cuegui/cuegui/plugins/AllocationsPlugin.py
Currently, the Allocations plugin "Idle" cores column includes cores in hosts that are locked, down, or set to repair.
It would be preferable for those cores to be broken into their columns so that the number of cores available to be booked would be more accurate.
> [cuegui] Update AllocationsPlugin columns

- cuegui/cuegui/MenuActions.py
- cuegui/cuegui/Utils.py
The output cmd call was not handling well all types of cmd formats. The cmd string needs to be passed as an array to be properly interpreted by the subprocess.
> [cuegui] Fix output viewer cmd format

- cuegui/cuegui/HostMonitorTree.py
When new columns were added a while back, what used to be a progress bar for memory used ended up becoming just the value for memory used. This PR also renames some of the fields to disambiguate them.
> [cuegui] Fix the memory bar on MonitorHostTree

- cuegui/tests/Constants_tests.py
Remove the unit test `test__should_use_default_values` which is a recipe for problems when deploying cuegui. The test was supposed to confirm constants defaults are set properly, but the current implementation applies values from cuegui.yaml, which is supposed to be configured by users to match their local requirements. With this, running the unit test locally after configuring cuegui.yaml will always fail.
The test itself didn't accomplish much, so I suggest removing it altogether.
> [cuegui] Remove constants test that is not testing constants

- cuegui/cuegui/Constants.py
- cuegui/cuegui/config/cuegui.yaml
- cuegui/cuegui/plugins/MonitorJobsPlugin.py
- Add a new configuration option `search_jobs.append_results` in cuegui.yaml to control job search behaviour.
- If `search_jobs.append_results` is set to true, search results will be appended to the current list of monitored jobs.
- If `search_jobs.append_results` is set to false, the existing jobs will be cleared before displaying the search results.
- Updated Constants.py to include the new configuration parameter.
- Modified MonitorJobsPlugin.py to conditionally clear the job monitor based on the config setting.
> Add a flag to search job with appended results

- cuegui/cuegui/Constants.py
- cuegui/cuegui/MainWindow.py
- cuegui/cuegui/config/cuegui.yaml
- Implemented new configuration options in cuegui.yaml:
- `cuegui.use.custom.version`: Toggle between using VERSION.in or custom CueGUI version.
- `cuegui.custom.cmd.version.stable`: Command to fetch stable version (`setenv OPENCUE_BETA 0`)
- `cuegui.custom.cmd.version.beta`: Command to fetch beta version (`setenv OPENCUE_BETA 1`)
- Modified Constants.py to fetch version dynamically based on config.
- Updated MainWindows.py to display the correct version (stable or beta) in the About menu.
- Fallback to VERSION.in if custom version is disabled.
> [cuegui] Add dynamic version fetching for the CueGUI About menu

- pycue/opencue/wrappers/frame.py
- pycue/opencue/wrappers/job.py
- pycue/opencue/wrappers/layer.py
- pycue/tests/wrappers/frame_test.py
- pycue/tests/wrappers/job_test.py
- pycue/tests/wrappers/layer_test.py
- rqd/rqd/rqmachine.py
Fixes: https://github.com/AcademySoftwareFoundation/OpenCue/issues/1519
Use `platform.uname()` instead of `os.uname()`. They have the same result on Linux, but `os.uname()` is not available on Windows, making us unable to kill a job from this OS.
**Additional information.**
Linux (ubuntu 22.04.6): 
``` python
>>> os.uname()
posix.uname_result(sysname='Linux', nodename='titan', release='6.8.0-45-generic', version='#45~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Sep 11 15:25:05 UTC 2', machine='x86_64')
>>>platform.uname()
uname_result(system='Linux', node='titan', release='6.8.0-45-generic', version='#45~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Sep 11 15:25:05 UTC 2', machine='x86_64')
```
Windows (11): 
``` python …
```
> [cuegui] Kill a Job from Windows.

- rqd/rqd/rqcore.py
Fixes #420 
Removes hardcoded environment variables specific for SPI
If the variables are still needed, they can be exposed for the job again by adding them to the `[UseHostEnvVar]` section of `rqd.conf`
> [rqd] Remove hardcoded MAIL and HOME rqd environment variables

- cuebot/Dockerfile
The version of gradle was updated on https://github.com/AcademySoftwareFoundation/OpenCue/pull/1393 but the change didn't make it to the Dockerfile.
> [cuegot] Upgrade gradle version on dockerfile

- cuebot/build.gradle
* Upgrade `io.zonky.test.embedded-postgres` and add required package for building on MacOS environments
* Add `mainClassName` to solve issues on the newer version of gradle where the main class was not being found on the generated jar
> [cuebot] Fix integration pipeline

- requirements.txt
Python3.6 doesn't support packaging 24
> Make packaging pip package version specific

- cueadmin/Dockerfile
- cueadmin/tests/test_suite.py
- pycue/Dockerfile
- pycue/tests/test_suite.py
- pyoutline/Dockerfile
- pyoutline/tests/test_suite.py
Some packages require pycue to run their unit tests and this requirement wasn't being installed on the dockerfile.
A `test_suite.py` file was added with the rules for test discover to make sure all unit tests are executed on projects that are built with python3.9.
> Another attempt on fixing the packaging pipeline

- .gitignore
- rqd/rqd/rqcore.py
- rqd/rqd/rqmachine.py
- rqd/rqd/rqnetwork.py
Ensure frames are removed from the rqd cache when they fail to complete their report process
Co-authored-by: Ramon Figueired <rfigueiredo@spimageworks.com>
> [rqd] Fix rqd cache spill issue

- cuegui/cuegui/MenuActions.py
- cuegui/tests/MenuActions_tests.py
CommentListDialog expects a list of jobs and at some point the input got changed to the first job on the list.
Opening the comments dialog on the current version returns:
```
TypeError: 'Job' object is not iterable 
```
> [cuegui] Fix issue on opening job comments

- rqd/rqd/rqdservicers.py
When killing a frame on a rqd node that has restarted and lost track of its running frames, the request should return a status to be handled accordingly and trigger the lostProc logic. The current behavior leaves the frame stuck at RUNNING until the job itself is killed or eaten.
> [rqd] Fix issue on rqd when killing a frame that no longer exists

- ci/run_integration_test.sh
Logs are being piped into a file that cannot be accessed from the cicd pipeline, which makes it impossible to find issues that are specific to the cicd environment.
> Log integration tests to stdout

- cuegui/cuegui/Constants.py
- cuegui/cuegui/MainWindow.py
- Refactored version determination logic in `cuegui/cuegui/Constants.py` to avoid repetition and improve readability.
- Improved error handling in `__get_version_from_cmd` function.
- Fix errors in `cuegui/tests/Constants_tests.py` when `cuegui.use.custom.version` is True
- Updated `displayAbout` method in `MainWindow.py` to explicitly check for `OPENCUE_BETA` environment variable.
> [cuegui] Fix CueGUI version handling and improve error handling

- cuegui/cuegui/MenuActions.py
- Updated `viewComments` method in `MenuActions.py` to wrap single Job objects in a list.
- This prevents `TypeError` when attempting to iterate over a non-iterable Job object.
> [cuegui] Fix TypeError in Comment viewer: Handle job object as iterable

- ci/run_gui_test.sh
- ci/run_python_tests.sh
Have changed most tests to use `-m unittest discover` instead og `setup.py test`
The old `setup.py test` doesn't work in newer versions of python since it has been deprecated
> [tests] Change tests to not use setup.py, but use the unittest module directly

- rqd/rqd/rqcore.py
Deleting an item from the dict being iterated over on sanitizeFrames caused the error: "Dictionary changed size during iteration".
> [rqd] Avoid changing dict in place during iteration

- ci/build_sphinx_docs.sh
- ci/fix_compiled_proto.py
- ci/python_coverage_report.sh
- ci/run_python_lint.sh
- ci/run_python_tests.sh
- connectors/prometheus_metrics/Dockerfile
- cueadmin/Dockerfile
- cuegui/Dockerfile
- cuesubmit/Dockerfile
- proto/README.md
- pycue/Dockerfile
- pyoutline/Dockerfile
- requirements.txt
- rqd/Dockerfile
- sandbox/install-client-sources.sh
This is to fix #1555 
Replaces 2to3 with a simple script that adds "from ." in front of pb2 imports.
This is done to support newer versions of python where 2to3 has been removed.
> Add script for converting imports in grpc python modules and remove 2to3

- cuegui/cuegui/FrameMonitorTree.py
- cuegui/cuegui/JobMonitorTree.py
- cuegui/cuegui/config/cuegui.yaml
- cuegui/tests/FrameMonitorTree_tests.py
[cuegui] Cannot select and play multiple jobs and frames using viewers in OpenCue: https://github.com/AcademySoftwareFoundation/OpenCue/issues/1558
This fixes the changes in PR: https://github.com/AcademySoftwareFoundation/OpenCue/pull/1513
- Fix multiple jobs and frames visualization with different viewers
- Updated JobMonitorTree.py and FrameMonitorTree.py to enable select multiple jobs and multiple frames and play using the players (e.g., OpenRV, RV, Itview = SPI viewer) configured in `cuegui.yaml`, options `output_viewers` and `output_viewer_direct_cmd_call`
- Enhanced cuegui.yaml to include configuration for multiple viewers.
- Fix unit tests in `FrameMonitorTree_tests.py` > `test_rightClickItem()` to …
> [cuegui] Fix multiple jobs and frames visualization

- cuegui/cuegui/FrameMonitorTree.py
- cuegui/tests/FrameMonitorTree_tests.py
- Ensure the job attribute is set before triggering the context menu event.
- Mock the getLayers method to return an empty list to avoid NoneType errors.
> [cuegui] Fix FrameContextMenu and test_rightClickItem to handle NoneType job attribute

- rqd/rqd/rqcore.py
This fixes an bug introduced with #1554 
It fixes a small bug that hinders `rqd` to actually run any jobs. It probably didn't get chaught due to the unittests for rqd not working properly.
> [rqd] Fix `keys` not iterable since it's a built-in function.

- cuebot/src/main/java/com/imageworks/spcue/ServiceEntity.java
- cuebot/src/main/java/com/imageworks/spcue/VirtualProc.java
- cuebot/src/main/java/com/imageworks/spcue/dao/postgres/HostDaoJdbc.java
- cuebot/src/main/java/com/imageworks/spcue/dao/postgres/LayerDaoJdbc.java
- cuebot/src/main/java/com/imageworks/spcue/dao/postgres/ProcDaoJdbc.java
- cuebot/src/main/java/com/imageworks/spcue/dispatcher/CoreUnitDispatcher.java
- cuebot/src/main/java/com/imageworks/spcue/dispatcher/Dispatcher.java
- cuebot/src/main/java/com/imageworks/spcue/dispatcher/HostReportHandler.java
- cuebot/src/main/java/com/imageworks/spcue/dispatcher/LocalDispatcher.java
- cuebot/src/main/java/com/imageworks/spcue/dispatcher/commands/DispatchBookHost.java
- cuebot/src/main/java/com/imageworks/spcue/service/JobSpec.java
- cuebot/src/main/java/com/imageworks/spcue/util/CueUtil.java
- cuebot/src/main/resources/opencue.properties
- cuebot/src/test/java/com/imageworks/spcue/test/dao/postgres/HostDaoTests.java
- cuebot/src/test/java/com/imageworks/spcue/test/dao/postgres/LayerDaoTests.java
- cuebot/src/test/java/com/imageworks/spcue/test/dao/postgres/ProcDaoTests.java
- cuebot/src/test/java/com/imageworks/spcue/test/dao/postgres/WhiteboardDaoTests.java
- cuebot/src/test/java/com/imageworks/spcue/test/service/JobManagerTests.java
- cuebot/src/test/java/com/imageworks/spcue/test/util/CoreSpanTests.java
- cuebot/src/test/resources/opencue.properties
Memory properties constantly need to be tuned according to farm requirements, which makes it a good candidate for becoming a property instead of a hardcoded constant.
> [cuebot] Move dispatcher memory properties to opencue.properties

- cuegui/cuegui/Utils.py
This is a small fix to not lock the UI when using preview in cuegui when using software that does not detach itself from the console.
It changes it from using `subprocess.check_call` to `subprocess.Popen`
Fixes #1568
> [cuegui] Prevent UI freeze during file preview by implementing subprocess.Popen for non-forking viewer applications

- rqd/rqd/rqconstants.py
- rqd/rqd/rqcore.py
SPI's environment requires customized home and email directories that need to be set on the frame environment variable. This change allows it to be set on rqd.conf as `RQD_CUSTOM_HOME_PREFIX` and `RQD_CUSTOM_MAIL_PREFIX`
> [rqd] Allow customizing HOME and MAIL environments

- rest_gateway/opencue_gateway/main.go
- Added log messages for JWT validation, gRPC handler registration, and other rest_gateways logs
- Modified `jwtMiddleware` to log successful token validation and access requests
- Refactored gRPC handler registration into a centralized function
- Created `registerGRPCHandlers` function to streamline and consolidate the registration of multiple gRPC service handlers
- Simplified code structure by using a loop to register each handler, improving maintainability and readability
- Added logging for individual handler registration success and errors to facilitate debugging
> [rest_gateway] Enhanced logging and error handling for gRPC gateway initialization

- .dockerignore
- cueadmin/Dockerfile
- pycue/Dockerfile
- pyoutline/Dockerfile
- rqd/Dockerfile
Fixes #1582 
This copies in the `ci/fix_compiled_proto.py` script into the images which is needed to build them
> [docker] Fix building docker images without 2to3

- requirements.txt
- The `enum34` (https://pypi.org/project/enum34/) package backports the enum module for Python versions 2.4–3.3. Since our project uses Python 3.7+, where `enum` is part of the standard library, this dependency is no longer required.
- This change cleans up the `requirements.txt` file by removing `enum34==1.1.6`
> Remove enum34 dependency from requirements.txt

- README.md
- Added the ASWF YouTube link to the [OpenCue Playlist](https://www.youtube.com/playlist?list=PL9dZxafYCWmzSBEwVT2AQinmZolYqBzdp) in the Opencue README file for better accessibility to learning resources.
- Added the [Opencue Slack channel](https://academysoftwarefdn.slack.com/archives/CMFPXV39Q) to the README.md
- Added the [Zoom](https://www.google.com/url?q=https://zoom-lfx.platform.linuxfoundation.org/meeting/95509555934?password%3Da8d65f0e-c5f0-44fb-b362-d3ed0c22b7c1&sa=D&source=calendar&ust=1717863981078692&usg=AOvVaw1zRcYz7VPAwfwOXeBPpoM6) biweekly meeting link
> Add ASWF OpenCue Playlist, Opencue Slack channel, and Zoom biweekly meeting link in the README

- cuegui/Dockerfile
- cuesubmit/Dockerfile
- requirements.txt
Changes on requirements.txt were not compatible with the centos7 image being used on cuegui and cuesubmit release pipelines. The long term goal is to upgrade those images and drop centos7 compatibility.
> [cicd] Fix cuegui and cuesubmit dockerfiles

- requirements_gui.txt
For now, cuesubmit's release pipeline is still based on centos7 and python36. I'm limiting the NodeGraphQtPy dependency to python3.7 to avoid crashing the pipeline. Cuesubmit doesn't really depend on this package.
> [cicd] Limit dependency for pip package NodeGraphQtPy

- .github/workflows/release-pipeline.yml
This step has been failing with permission issues.
Commenting this out temporarily to unblock the release of v1.4
> [cicd] Remove dockerhub comments

- cuegui/cuegui/plugins/AttributesPlugin.py
- Added Max Threads and Memory Optimizer attributes to the Attributes plugin
- Enhances usability by providing key layer info when the Properties popup is unavailable
> [cuegui] Add Max Threads and Memory Optimizer to Attributes Plugin

- cuesubmit/README.md
- cuesubmit/plugins/maya/CueMayaSubmit.py
- cuesubmit/plugins/nuke/CueNukeSubmit.py
- cuesubmit/setup.py
https://github.com/AcademySoftwareFoundation/OpenCue/issues/1633
- Import statements updated to use `qtpy` instead of `PySide2`
- Documentation in `README.md` updated to reflect the change
- `setup.py` modified to include `qtpy` in the `install_requires` list instead of `PySide2`
This change aims to provide a more flexible abstraction layer for different Qt bindings, improving compatibility and maintainability.
> [cuesubmit] Replace PySide2 with qtpy in CueSubmit files

- requirements.txt
https://github.com/AcademySoftwareFoundation/OpenCue/issues/1635
- Updated `grpcio` from 1.53.2 to 1.69.0 for Python versions >= 3.7
- Updated `grpcio-tools` from 1.53.0 to 1.69.0 for Python versions >= 3.7
- Fixes the error encountered when running: `pip install -r requirements.txt -r requirements_gui.txt`
- This update reflects the tests conducted on a MacBook Pro with Apple M2 Max
> Update grpcio and grpcio-tools dependencies to version 1.69.0

- cueadmin/setup.py
- cuegui/setup.py
- cuesubmit/setup.py
- pycue/setup.py
- pyoutline/setup.py
- rqd/setup.py
https://github.com/AcademySoftwareFoundation/OpenCue/issues/1637
- Updated version file paths in setup scripts to use VERSION.in (correct file name in the Opencue project) instead of VERSION
- Fixes the error when running `sandbox/install-client-sources.sh`
- `sandbox/install-client-sources.sh` calls `pip install pycue/ pyoutline/ cueadmin/ cuesubmit/ cuegui/` and the `setup.py` in these directories should use `VERSION.in` not `VERSION`
> Update version file paths to use VERSION.in

- cuegui/cuegui/Redirect.py
Checking for if the source job has waiting frames makes no sense as the job is giving up its resources. This unnecessary check was preventing operations from redirecting resources from jobs that were fully booked but still running.
> [cuegui] Remove check for source waiting frames on redirect

- ci/run_python_tests.sh
- requirements.txt
- rqd/rqd.example.conf
- rqd/rqd/rqconstants.py
- rqd/rqd/rqcore.py
- rqd/rqd/rqdocker.py
- rqd/tests/rqcore_test.py
Docker features were spread between `rqconstants.py` and `rqcore.py` making it difficult to assess the impact of changes on the logic. Both configuring and using the Docker API have been moved to `rqdocker.py`.
- Add config attribute DOCKER_GPU_MODE to allow passing "gpu=all" when calling docker run.
- Add optional environment variable OVERRIDE_DOCKER_IMAGES
- Make docker and sentry python dependencies opt-in
> [rqd] Refactor runOnDocker and add gpu_mode 

- rqd/rqd/rqdocker.py
Found this error in the [rqd-python-v2](https://github.com/AcademySoftwareFoundation/OpenCue/pull/1654) testing PR
Adds a small import that fixes the type hinting that only works in python 3.9+
> [rqd] Fix for type hinting that doesn't work in python 3.8

- cuegui/cuegui/config/cuegui.yaml
- cuegui/tests/LayerDialog_tests.py
- cuegui/tests/Utils_tests.py
The limit was defined in an era when 32 cores were more than what people thought to be possible.
> [cuegui] Increase memory and core limits on the redirect widget

- cuegui/cuegui/LayerDialog.py
- cuegui/tests/LayerDialog_tests.py
Increasing the max_memory_limit on PR#1657 had a collateral effect on LayerDialog causing int overflows and slowness on the Layer dialog.
The proposed solution is to stop using kb as the granularity of the slider and start using MB. We lose precision, but I don't think people would be that precious about it.
> [cuegui] Fix slider performance issue on LayerDialog

- rqd/rqd/rqconstants.py
- rqd/rqd/rqcore.py
If the frame uid is outside of linux defined UID_MAX and UID_MIN fallback to the uid of the daemon user. Read https://www.man7.org/linux/man-pages/man5/login.defs.5.html for more information about uid limits. At this time, limits are hardcoded on rqconstants as the linux default values, which sounds reasonable as this default config limit is rarely modified.
> [rqd] Check if uid is valid before launching frame

- rqd/rqd/rqconstants.py
`SP_OS` needs to be updated according to the images configured on docker_agent
> [rqd] Ensure SP_OS gets updated properly on docker mode

- cuegui/cuegui/HostMonitorTree.py
- cuegui/cuegui/Utils.py
- cuegui/cuegui/plugins/AttributesPlugin.py
- Added "Boot Time" column to `HostMonitorTree` to display and sort by boot time
- Updated `AttributesPlugin.py` to include year in `bootTime` attribute
[#1663](https://github.com/AcademySoftwareFoundation/OpenCue/issues/1663)
Add a "Boot Time" column to the "Monitor Hosts" window to display and sort hosts by their boot time. This enhancement will make it easier to identify hosts that need a reboot by allowing users to sort the list of hosts by their boot time. 
- The "Boot Time" will be displayed in the format `dd/mm hh:mm` in the "Monitor Hosts" without the year to not use too much space in the data grip 
- The boot time will be displayed in the format `dd/mm/yyyy hh:mm` in the "Attributes Plugin"
> [cuegui] Add "Boot Time" column to HostMonitorTree and update AttributesPlugin to include boot time with year

- cuegui/cuegui/FrameMonitorTree.py
- cuegui/cuegui/JobMonitorTree.py
- cuegui/cuegui/LayerMonitorTree.py
All menu options for local booking had been made opt-in using .ini files on 34c2bded, this PR brings the option back to the default configuration. Studios that don't want the option enabled by default should add `DisableDeeding=1` to cuetopia.ini and cuecommander.ini.
> [cuegui] Make local booking action opt-out

- rqd/rqd/rqdocker.py
Docker requires that the source of a mounted volume exists prior to running the container. This change simply checks and creates the directory if absent.
> [rqd] Ensure source on docker mounted volumes exist

- cuegui/cuegui/__main__.py
- cuegui/setup.py
This changes are motivated by our studio use-case where we want to provide artist with the restricted `Cuetopia` view (job monitoring) but not the `CueCommander` one (hosts + opencue management).
Add 2 new separate entry points for `cuegui`:
* `cuetopia`: to open only Cuetopia
* `cuecommander`: alias to current `cuegui` (CueCommander)
> Add cuetopia entrypoint to cuegui.

- .github/workflows/testing-pipeline.yml
The action tj-actions/changed-files is compromissed and needs to be disabled as soon as possible.
https://github.com/tj-actions/changed-files/issues/2463
https://semgrep.dev/blog/2025/popular-github-action-tj-actionschanged-files-is-compromised/
Update:
Looks like the repo has been completely disabled now.
Will see if I can make a similar action, so we are not depending on a third party one.
> [URGENT] Disable compromised tj-actions/changed-files

- ci/run_python_tests.sh
- rqd/rqd/rqconstants.py
- rqd/rqd/rqcore.py
- rqd/rqd/rqmachine.py
- rqd/rqd/rqnimby.py
- rqd/tests/rqconstants_test.py
- rqd/tests/rqcore_test.py
- rqd/tests/rqmachine_test.py
- rqd/tests/rqnimby_test.py
The previous pynput based implementation was more complex than needed due to the effort to keep backwards compatibility with the previously implementation based on Select. This change removes support to the Select based implementation in favor of a simplified logic using pynput.
Given that the Select method was outdated and incompatible with modern versions of linux, supporting it is no longer necessary.
> [rqd] Rewrite rqnimby logic

- cuegui/cuegui/HostMonitor.py
- When the user clicked in the "Clear" option of the lock state filter the "self.hostMonitorTree.updateRequest()" where not called to update the items in the TreeWidget
[Fix 'Clear' option in the Lock State filter #1685](https://github.com/AcademySoftwareFoundation/OpenCue/issues/1685)
> [cuegui] Fix 'Clear' option in the Lock State filter

- cuegui/cuegui/JobMonitorTree.py
- Added getter methods for local plugin settings (num_frames, num_threads, num_gpus, num_mem, num_gpu_mem) with default fallback values to avoid errors when restoring plugin state.
[#1687](https://github.com/AcademySoftwareFoundation/OpenCue/issues/1687)
> [cuegui] Fix plugin state saving error in Monitor Jobs by adding default getters

- rqd/rqd/rqcore.py
If a frame fails to be initialized because its container is not available, mark the job with a statuscode that will get it back to waiting to be retried automatically.
```
EXITSTATUS_FOR_FAILED_LAUNCH = 256
```
> [rqd] Change exitstatus for failed frames on docker that should be retried

- cuegui/cuegui/ServiceDialog.py
- Guard against None in ServiceForm.setService() by showing a warning dialog and returning early.
- Add defensive check in ServiceManager.selected() to prevent calling setService() when service is None.
- These changes prevent AttributeError when service data fails to load.
Related error:
`AttributeError: 'NoneType' object has no attribute 'name'`
[#1698](https://github.com/AcademySoftwareFoundation/OpenCue/issues/1698)
> [cuegui] Add null checks to ServiceDialog to prevent crash on missing service

- rqd/rqd/__main__.py
- rqd/rqd/rqmachine.py
When a frame is still on the frame cache and its process has completed, it should be skipped from rssUpdate to avoid a key error. Crawling its children is not necessary as unfinished children will have been reparented.
> [rqd] Fix issue on rssUpdate

- cuegui/cuegui/LayerMonitorTree.py
- Changed behavior in LayerMonitorTree to emit filter and selection signals only when a layer row is double-clicked, instead of on single selection.
- When you click once the layer line, the frame filter should not change, only if you double-click or change in the frame filter.
- This is to make the filtering of the frames more deliberate as its current one-click autofilter takes away the option to still see all the job frames.
Notes:
- `self.itemSelectionChanged` is a Qt signal that is emitted when the selection in the QTreeWidget changes.
- `self.itemDoubleClicked` is a Qt signal that only fires when the user double-clicks a row.
This PR is related to the changes made on the PRs:
1) feat: Add job node graph plugin #888
https://github.com/AcademySoftwareFoundation/OpenCue/pull/888
2) …
> [cuegui] Apply layer filter in Frame Monitor only on double-click

- cuegui/cuegui/MainWindow.py
- Added a check in `__saveSettings` to ensure window open/close state is only saved when at least one window is still open.
- Prevents overwriting all window states with Open=false (.config/.cuecommander/config.ini and .config/.cuetopia/config.ini files) during shutdown (e.g., when exiting via File > Exit Application).
- Ensures accurate restoration of previously opened windows on next launch.
CueGUI overwrites window Open state as false when exiting CueGUI #1706
> [cuegui] Prevent window open state from being overwritten during shutdown

- cuegui/cuegui/MainWindow.py
This patch improves CueGUI behavior by ensuring the state of each window is correctly saved when the user closes it via the window's [X] button or right click in the "CueGUI icon > Close Windows" instead of the menu "File > Exit Application" or shortcut (Ctrl+Q).
Changes include:
- Introduced `self.__manual_closed` to distinguish between manual window closing and full app exit.
- Set `Open=false` for the closed window when manually closed.
- Modified `__windowCloseApplication` to mark all windows as not manually closed when quitting via menu "File > Exit Application" or "Ctrl+Q".
- Ensured the window name (`self.name`) is used when saving the window's Open state.
Note: The correct way to save the CueGUI windows state and windows that are opened is to use the menu: "File > Exit …
> [cuegui] Fix window state not saved when closing via [X] button

- cueadmin/cueadmin/common.py
- cuegui/cuegui/MenuActions.py
- cuegui/cuegui/UnbookDialog.py
- cuegui/cuegui/Utils.py
- pyoutline/outline/backend/cue.py
- pyoutline/outline/config.py
- pyoutline/outline/layer.py
- pyoutline/outline/loader.py
- rqd/rqd/rqconstants.py
- rqd/tests/rqconstants_test.py
- Remove the legacy `six` dependency across multiple OpenCue components in alignment with Python 3-only support.
1) cueadmin
- Removed `six` import from `common.py`
- Replaced `six.string_types` with native `str` checks
2) cuegui
- Removed `six` usage from:
- `MenuActions.py`
- `UnbookDialog.py`
- `Utils.py`
- Replaced `six.string_types` with `str`
3) pyoutline
- Removed all `six` and `six.moves` references from:
- `config.py`
- `cue.py`
- `layer.py`
- `loader.py`
- Replaced legacy type checks with native `str`
Cleaned up string handling and config parser logic
4) rqd
- Removed `six` from `rqconstants.py` and `rqconstants_test.py`
- Replaced `six.moves.configparser` with direct import of `configparser.RawConfigParser`
- Removed Python 2 conditionals and updated test logic
These changes …
> [cueadmin/cuegui/pyoutline/rqd] Remove `six` fependency from CueAdmin, CueGUI, PyOutline, and RQD modules

- cuegui/cuegui/Utils.py
- Extracts editor binary to avoid false matches (e.g. gvimrc triggering Vim detection)
- When the editor is vim/gvim/gview, opens it using:
xterm -e vim -u NONE -N <file>
- This avoids loading broken system/user .vimrc files on Rocky Linux
- Falls back to default editor behavior for all other cases
[cuegui] Vim crashes when opening frame logs on Rocky 9 due to incompatible configuration files #1729
> [cuegui] Fix log viewer crash on Rocky 9 by launching Vim in xterm with safe flags

- cuegui/cuegui/Utils.py
- cuegui/cuegui/config/gvimrc
- cuegui/cuegui/config/rqlog.vim
- Updated `gvimrc` to source `rqlog.vim` relative to the `gvimrc` path using `execute` and `expand('<sfile>:p:h')` to avoid E484 errors.
- Changed fallback source path from `./rqlog.vim` to relative gvimrc directory for better portability.
- Updated comments and default override paths in `rqlog.vim` to reference `~/.config/.cuetopia` instead of the old `~/.cuetopia`.
- Reverted popupView logic in Utils.py to restore compatibility with user-defined or default log editors (e.g., gview) in both CentOS and Rocky Linux.
This resolves `E890` and `E484` errors encountered when viewing `.rqlog` files with `gview` on Rocky 9.
[cuegui] Vim crashes when opening frame logs on Rocky 9 due to incompatible configuration files #1729
> [cuegui] Fix rqlog syntax highlighting compatibility on Rocky Linux

- cuegui/cuegui/DependWizard.py
- Job-on-Job (JOJ) has an enum value of 0, which previously evaluated as False in the `nextId` check: `if not self.wizard().dependType`
- This caused the wizard to incorrectly loop back to the initial page and block forward progress.
The condition was updated to explicitly check for `None` instead of falsiness.
[cuegui] Dependency Wizard "Job on Job" option do not advance in CueGUI #1733
Co-authored-by: Ramon Figueiredo <rfigueiredo@imageworks.com>
Co-authored-by: Buthaina Mahmoud <bmahmoud@imageworks.com>
> [cuegui] Fix Dependency Wizard navigation for Job-on-Job (JOJ) dependency type

- rqd/rqd/rqcore.py
- rqd/rqd/rqmachine.py
Partially revert changes from https://github.com/AcademySoftwareFoundation/OpenCue/pull/1689 and implement a different fix for the same problem based on sessionid.
The previous solution replaced a logic that traced lineage based on sessionid with a parentid based solution. This new solution uses sessionid but removes the session query loop from the main frame loop, reducing the complexity of the logic and improving its performance.
> [rqd] Rework rssUpdate based on sessionid

- rqd/rqd/rqcore.py
- rqd/rqd/rqnetwork.py
- rqd/rqd/rqnimby.py
* Clean up grpc fork warnings:  
> fork_posix.cc Other threads are currently calling into gRPC, skipping fork() handlers
* Clean up pynput warnings from nimby when nimby is inactive. This new logic prevents importing pynput when it is not necessary.
> [rqd] Remove grpc-fork and pynput warnings

- cuegui/cuegui/ServiceDialog.py
Replaced method calls with direct access to fields like `name`, `threadable`, `min_cores`, `max_cores`, `min_memory`, and `tags` to ensure compatibility with ServiceOverride objects.
[cuegui] ServiceDialog crashes when displaying ServiceOverride objects due to missing attribute methods #1739
> [cuegui] Fix ServiceDialog by using direct access to service fields

- cuegui/cuegui/DependWizard.py
- Restores functionality for the LOS (Layer on Simulation Frame) dependency type.
- Ensures the "Depend on Layer" list is correctly populated with simulation-related layers only.
- Adds proper validation for simulation services (e.g., "simulation", "houdini").
- Resolves issue where Next button on LOS (Layer on Simulation Frame) flow did not work as expected.
[cuegui] Fix "Layer on Simulation Frame" dependency type in DependWizard #1746
> [cuegui] Fix handling of "Layer on Simulation Frame" dependency in Depend Wizard

- sandbox/install-client-sources.sh
Replaces deprecated OPENCUE_PROTO_PACKAGE_PATH env check to align with new packaging structure introduced in #1681, where proto is now its own package (opencue_proto) and all packages are prefixed with "opencue_".
- Updated condition to use Bash idiomatic check for defined variables
- Adds `pip install proto/` to ensure the opencue_proto package is installed
- Removed legacy fallback install of cuebot source directory
- Ensures all package paths explicitly use trailing slashes (e.g., pycue/) to direct `pip` to local directories instead of fetching from PyPI
This ensures compatibility with the refactored pyproject.toml-based installation flow and enables support for Python 3.11+ environments.
> Fix client install script after packaging refactor (#1681)

- README.md
- cuesubmit/pyproject.toml
- requirements.txt
- sandbox/README.md
- sandbox/install-client-sources.sh
- Updated `sandbox/install-client-sources.sh` to:
- Add comments and safety checks
- Automatically tag the version based on VERSION.in
- Support local macOS builds using grpcio~=1.71.0 and grpcio-tools~=1.71.0
- Updated `cuesubmit/pyproject.toml` to fix script entry point via [project.scripts]
- Required to build cuesubmit and launch it via `cuesubmit &`
- Revised `requirements.txt` to use grpcio~=1.71.0 and grpcio-tools~=1.71.0 to fix RuntimeError
- grpc version 1.69.0 is too old; upgrade to grpcio~=1.71.0
- Fix RuntimeError: The grpc package installed is at version 1.69.0, but the generated code in `comment_pb2_grpc.py` depends on `grpcio>=1.71.0`
- Rewrote `sandbox/README.md` with clearer step-by-step setup instructions, including use of `sandbox/install-client-sources.sh`
- Updated …
> Improve sandbox install script, pyproject metadata, and update documentation

- .github/workflows/testing-pipeline.yml
- cuegui/cuegui/plugins/StuckFramePlugin.py
- pycue/pyproject.toml
- pyoutline/outline/io.py
- pyoutline/outline/loader.py
- pyoutline/outline/session.py
Upgraded PyYAML from 5.1 to 6.0.1 to ensure compatibility with newer features and security updates. This change aligns with best practices for dependency management.
Also added test for installing all packages in python 3.7
> Update PyYAML dependency to version 6.0.1

- rqd/rqd/rqconstants.py
N/A
After a healthy amount of head-banging I noticed that the value of `rqconstants.RQD_USE_ALL_HOST_ENV_VARS` was always `False` regardless of the overrides I had in my `rqd.conf`. 
It appears the variable `rqconstants.RQD_USE_HOST_ENV_VARS` (never used) was being updated instead of `rqconstants.RQD_USE_ALL_HOST_ENV_VARS`. 
`rqconstants.RQD_USE_ALL_HOST_ENV_VARS` is only ever used once throughout the codebase, in rqd/rqcore.py, so this change should be safe.
https://github.com/AcademySoftwareFoundation/OpenCue/blob/9b3e02abb3898ef77201d6d705ed18b4f85d5143/rqd/rqd/rqcore.py#L795
> [rqd] Fix typo that was causing rqconstants.RQD_USE_ALL_HOST_ENV_VARS to never get overriden by rqd.conf

- .github/workflows/rust.yml
- rust/Cargo.lock
- rust/config/rqd.fake_linux.yaml
- rust/config/rqd.yaml
- rust/crates/rqd/Cargo.toml
- rust/crates/rqd/resources/openrqd.service
- rust/crates/rqd/src/config/config.rs
- rust/crates/rqd/src/system/linux.rs
- rust/crates/rqd/src/system/machine.rs
- rust/crates/rqd/src/system/macos.rs
- rust/crates/rqd/src/system/manager.rs
- rust/crates/rqd/src/system/mod.rs
- rust/crates/rqd/src/system/nimby.rs
Implemented NIMBY (Not In My BackYard) logic in the new Rust-based RQD, replicating the behavior of the original Python implementation.
- Add NIMBY support to the Rust-based RQD system, preventing jobs from running when a user is actively using the machine.
- Add new `rust/crates/rqd/src/system/nimby.rs` module to detect mouse/keyboard activity using `device_query`
- NIMBY configurable via `rqd.yaml` (nimby_mode, idle_threshold, etc.)
- Dynamically sets `DISPLAY` and `XAUTHORITY` from a file
- Integrated with `MachineMonitor` to `lock/unlock` cores and update host state
- Graceful shutdown support with `broadcast::channel`
> [rust/rqd] Implement NIMBY logic

- rust/crates/opencue-proto/src/lib.rs
- rust/crates/rqd/src/frame/manager.rs
- rust/crates/rqd/src/system/linux.rs
- rust/crates/rqd/src/system/machine.rs
- rust/crates/rqd/src/system/macos.rs
- rust/crates/rqd/src/system/manager.rs
- rust/crates/rqd/src/system/mod.rs
- rust/crates/rqd/src/system/reservation.rs
Use a single source of truth for core reservations to avoid synchronization issues. The previous logic had some potential synchronization issues that could lead to resource leaking.
> [rust/rqd] Refactor core reservation logic

- cuebot/Dockerfile
Aligned the base image to bookworm for improved security updates and compatibility while maintaining OpenJDK 18.
This fixes #1777 
Updated to debian bookworm for cuebot docker image
> Update cuebot base image to OpenJDK 18 slim-bullseye

- .github/workflows/packaging-pipeline.yml
- .github/workflows/testing-pipeline.yml
This is to fix the release pipeline.
It takes the same parts of the testing pipeline to first build the python packages and use them for building the docker images.
I have tested the integration tests that seems to work, but I cannot test the other steps, which requires AWS credentials.
This is needed for #1779 to work properly and generally to allow the packaging to work again after the rework of the build setup for the python libraries.
> Add build pipeline for packaging all OpenCue modules in CI workflow

- cueadmin/cueadmin/__init__.py
Include the Copyright comments to the `cueadmin/cueadmin/__init__.py` file.
[cueadmin] Add missing copyright and contributor header to cueadmin/cueadmin/__init__.py #1786
> [cueadmin] Add Copyright Contributors to the OpenCue Project

- .github/workflows/packaging-pipeline.yml
This is to fix a conflicting step in the packaging pipeline
> [CI/CD] Remove redundant step for uploading opencue packages in CI workflow

- docs/_docs/getting-started/deploying-rqd.md
- docs/_docs/reference/rust-rqd.md
- Added new reference page: docs/_docs/reference/rust-rqd.md, including:
- Overview of Rust RQD and comparison with Python implementation
- Platform-specific build instructions using Cargo
- Running guidance for development and production environments
- Experimental Docker support notes
- Contribution guidelines (testing, linting, clippy usage)
- Performance benchmarks and migration tips
- Known limitations and future roadmap
- Updated docs/_docs/getting-started/deploying-rqd.md:
- Added new "Alternative: Rust RQD" section with reference link to Rust RQD docs
- https://github.com/AcademySoftwareFoundation/OpenCue/issues/1800
> [docs] Add documentation for Rust-based RQD implementation

- rust/Cargo.lock
- rust/crates/rqd/Cargo.toml
Rqd relies on having dummy cuebot built to run integration tests
> [rust/rqd] Add dummy-cuebot as a dev dependency for rqd

- docs/_docs/reference/index.md
- docs/_docs/reference/tools/cueman.md
- docs/_docs/reference/tools/index.md
- docs/_docs/tutorials/cueman-tutorial.md
- Update all references from "CueMan" to "Cueman" for consistency
- Affected files: tutorial, reference index, tools index, and cueman reference page
- Maintains consistent capitalization throughout the documentation
- Minor Cueman documentation improvements
- https://github.com/AcademySoftwareFoundation/OpenCue/issues/1800
> [docs] Standardize Cueman naming convention across documentation

- .github/workflows/docs.yml
- .gitignore
- docs/_config.yml
- docs/_includes/aux-nav.html
- docs/_includes/header_custom.html
- docs/_includes/page-metadata.html
- docs/_includes/sidebar-version-switcher.html
- docs/_includes/version-banner.html
- docs/_includes/version-switcher.html
- docs/_plugins/last_modified.rb
- docs/update_version.sh
- docs/versions.md
- Add version dropdown in sidebar navigation with independent v0.0.1 and main
- Implement Git-based last modified date extraction via Jekyll plugin
- Create page metadata component showing version info and last updated dates
- Add contextual version warning banners for non-main versions
- Enhance GitHub Actions workflow for multi-version documentation builds
- Add version overview page with independent version tracking
- Improve dark mode table contrast and styling
- Add gitignore for auto-generated version files
This enables users to:
- Switch between independent documentation versions
- See when each page was last updated via Git history
- Get contextual warnings when viewing older documentation versions
- Automatically maintain version info from single source (VERSION.in)
**Link the …
> [docs] Implement independent versioning system with automated metadata

- .gitignore
- rust/crates/rqd/src/frame/frame_cmd.rs
- rust/crates/rqd/src/frame/running_frame.rs
The trap/log logic is only useful when recovery mode is turned on, and only macos supports this feature at the moment. This PR simplify the wrapper script for linux environments.
> [rust/rqd] Remove complicated trap logic from frame cmd when not needed

- docs/index.md
- Remove trailing slashes from getting-started URLs to match actual page path.
- The links were incorrectly pointing to `/docs/getting-started/` instead of `/docs/getting-started`, causing 404 errors.
- #1800
> [docs] Fix broken Getting Started link in documentation homepage

- .github/workflows/packaging-pipeline.yml
Forgot that I had disabled integration testing in packaging workflow to speed up testing
This re-enabled it again.
> [CI/CD] Re-enable integration test script step in packaging pipeline

- docs/index.md
- Add comprehensive history section showcasing OpenCue's 30+ year evolution
- Include timeline from early SPI render tools through Academy Award recognition
- Feature card-based layout with key milestones from 1992 to present
- Embed Academy Sci-Tech Award video for Matt Chambers
- Add links to Sony Pictures Imageworks and ASWF throughout timeline
- #1800
> [docs] Add OpenCue History section with project timeline

- docs/_docs/index.md
- docs/index.md
- Remove trailing slash from `/docs/quick-starts/` to `/docs/quick-starts`
- Remove trailing slash from `/docs/concepts/` to `/docs/concepts`
- Remove trailing slash from `/docs/user-guides/` to `/docs/user-guides`
- Remove trailing slash from `/docs/reference/` to `/docs/reference`
- Remove trailing slash from `/docs/tutorials/` to `/docs/tutorials`
- Remove trailing slashes from all navigation links in `docs/_docs/index.md` to ensure consistent link behavior and proper navigation across the documentation site.
- Fix the links `news` and `releases` in `docs/_docs/index.md`
- #1800
> [docs] Fix documentation navigation links by removing trailing slashes

- docs/_docs/concepts/glossary.md
- docs/_docs/concepts/opencue-overview.md
- docs/_docs/concepts/spi-case-study.md
- docs/_docs/getting-started/installing-cuegui.md
- docs/_docs/other-guides/cueweb.md
- docs/_docs/other-guides/framelogging-with-loki.md
- docs/_docs/other-guides/monitoring-with-prometheus-loki-and-grafana.md
- docs/_docs/quick-starts/quick-start-linux.md
- docs/_docs/quick-starts/quick-start-mac.md
- docs/_docs/reference/CueGUI-app.md
- docs/_docs/user-guides/cuetopia-monitoring-guide.md
- docs/_docs/user-guides/monitoring-jobs.md
- docs/_docs/user-guides/submitting-jobs.md
- docs/news/2019-07-08-opencue-birds-of-a-feather-at-siggraph.md
- docs/news/2020-08-27-google-summer-of-code-20-cloud-plugin.md
- Updated all image references starting with `/OpenCue/assets/images/` to use `/assets/images/` instead for correct rendering in the documentation site.
- #1800
> [docs] Fix image paths to remove /OpenCue prefix

- README.md
- Updated the preview instructions to use the correct local address (http://localhost:4000) instead of the outdated http://localhost:4000/OpenCue/
- #1800
> [docs] Fix local documentation preview URL in README

- docs/_includes/header_custom.html
- docs/index.md
- Arrange Contributing Guide, Join Slack, and Report Issues buttons in single horizontal line
- Reduce button sizes for better visual balance while maintaining readability
- Update Contributing Guide to link to internal documentation page
- Decrease vertical spacing between community cards and action buttons
- Implement responsive design to maintain single-line layout across all screen sizes
- Optimize button spacing and padding for desktop, tablet, and mobile views
- #1800
> [docs] Redesign community section buttons for improved layout

- docs/_includes/header_custom.html
- docs/index.md
- Add Quick Starts button with green accent styling and bolt icon
- Optimize button sizing to fit all 4 buttons on single line
- Reduce button padding, font size, and minimum width for better layout
- Ensure consistent white text and icon colors across all hero buttons
- #1800
> [docs] Add `Quick Starts` button to homepage hero section

- cuegui/cuegui/DependDialog.py
- cuegui/cuegui/DependMonitorTree.py
- cuegui/cuegui/DependWizard.py
- Increase Dependency Wizard window size from 500x500 to 1200x800
- Increase Dependencies dialog window size from 1000x600 to 1200x800
- Configure dependency tree columns to auto-resize to content
- Resolves scrolling issues with long job names in dependency dialogs
- https://github.com/AcademySoftwareFoundation/OpenCue/issues/1852
> [cuegui] Fix dependency window sizing for better job name visibility

- cuegui/cuegui/JobMonitorTree.py
- cuegui/cuegui/plugins/MonitorJobsPlugin.py
- Disable UI updates during batch job loading to prevent redundant refreshes
- Implement batch fetching with 50-job chunks to avoid API timeouts
- Improve responsiveness when loading 5000+ jobs
Advantages of this approach:
- Reduces load time from 15-20 seconds to ~3 seconds for 5000+ jobs
- Prevents UI freezing during job loading operations
- Minimizes memory pressure by fetching jobs in smaller batches
- Maintains backward compatibility with existing functionality
- Simple implementation without complex threading or dependencies
This significantly improves user experience for facilities managing thousands/million of active jobs, making job monitoring and management more efficient.
Fixes issue with UI freezing when monitoring facilities with high job volumes.
**Link the Issue(s) this …
> [cuegui] Optimize CueGUI > Cuetopia > Monitor Jobs performance for large job lists

- rust/Cargo.lock
- rust/Cargo.toml
- rust/crates/rqd/Cargo.toml
- rust/crates/rqd/tests/rqd_integration_tests.rs
Integration tests are failing on some environment when the compilation order puts dummy-cuebot after rqd.
> [rust/rqd] Ensure dummy-cuebot is built before running rqd integration tests

- cuebot/src/main/resources/opencue.properties
The server has been reporting the warning bellow. This configuration change replaces `maxAge` with `max-lifetime`. 
Besides that, new attributes were added to handle idle connections, leaks and pool size.
```
HikariPool-1 - Failed to validate connection org.postgresql.jdbc.PgConnection@27e38df7 (This connection has been closed.). Possibly consider using a shorter maxLifetime value.
```
> [CueBot] Fix hitaki data-source outdated attributes

- rqd/rqd/rqconstants.py
- rqd/rqd/rqnetwork.py
- rqd/rqd/rqutil.py
- rust/Cargo.lock
- rust/config/rqd.yaml
- rust/crates/rqd/Cargo.toml
- rust/crates/rqd/src/config/mod.rs
- rust/crates/rqd/src/servant/mod.rs
- Introduced `RQD_NETWORK_INTERFACE` to allow specifying the network interface for binding the gRPC server.
- Added `getInterfaceIp` utility function to resolve the IP of a provided network interface.
- Updated several methods to respect the new configuration attribute.
This enables support for selecting which specific interface to listen on and also which ip to report cuebot server.
> [rqd] Add support for specifying network interface for rqd

- rust/config/rqd.yaml
- rust/crates/rqd/src/config/mod.rs
- rust/crates/rqd/src/report/report_client.rs
- rust/crates/rqd/src/report/retry/backoff_policy.rs
- rust/crates/rqd/src/report/retry/future.rs
* When rqd fails to connect, don't swallow the failure message.
* When on Retrying state, avoid cycling back to Initializing but start a new request immediatly and
transition to Cloning.
> [rust/rqd] Optimize retry mechanism and add logging info

- README.md
- Added "Contributors" section
- Fixed spelling and consistency issues.
- on-premisses -> on-premisses
- Updated Opencue to OpenCue in a few places to maintain consistency.
> [docs] Add "Contributors" section and fix spelling and consistency issues in README

- docs/_config.yml
- docs/_docs/getting-started/index.md
- docs/_docs/index.md
- docs/_includes/sidebar-version-switcher.html
- docs/update_version.sh
- docs/versions.md
- Set v1.11.66 as the default documentation version
- Configure both v1.11.66 and main to point to latest content
- Mark v1.11.66 as the current stable release in labels and structure
- Remove "under active development" notices
- Make version switcher logic generic using Jekyll config variables
- Remove hardcoded version references in JavaScript for maintainability
- Update _config.yml and related settings for new release
- The documentation (docs/) now follows the OpenCue software versioning (VERSION.in)
- Changed the label in the page metadata display from "Doc Version" to "Versions"
- #1800
> [docs] OpenCue documentation stable version - Update docs version to 1.11.66

- docs/news/2019-04-18-season-of-docs-2019.md
- docs/news/2019-07-08-opencue-birds-of-a-feather-at-siggraph.md
- docs/news/2019-07-22-opencue-steering-committee-at-siggraph.md
- docs/news/2019-09-20-opencue-at-siggraph-recording.md
- docs/news/2019-12-05-la-pipeline-developers-meetup.md
- docs/news/2019-12-18-sony-pictures-imageworks-case-study.md
- docs/news/2020-08-27-google-summer-of-code-20-cloud-plugin.md
- docs/news/2021-08-04-open-source-days-2021.md
- docs/news/2024-05-24-opencue-project-review-2024.md
- docs/news/2025-08-10-opencue-project-review-2025.md
- Add 2025 OpenCue Project Review 2025 (OpenCue Virtual Town Hall Series) with embedded video
- Include PDF slides link for 2025 presentation
- Include video (OpenCue Project Review 2024 - OpenCue Virtual Town Hall Series) in existing documentation
- Update navigation order for news pages
- #1800
> [docs] Add News: OpenCue Project Review 2025

- cuegui/pyproject.toml
Shorten cuegui package description from 574 to 490 characters to comply with PyPI's 512 character limit for summary/description field. This fixes test upload failures caused by descriptions being too long.
All 8 Python packages now have descriptions under the 512 character limit:
- cueadmin: 260 chars
- cuegui: 490 chars (previously 574)
- cueman: 237 chars
- cuesubmit: 223 chars
- proto: 99 chars
- pycue: 195 chars
- pyoutline: 233 chars
- rqd: 85 chars
- #1945
> [pypi] Fix Python package descriptions exceeding 512 character limit

- cueman/pyproject.toml
- cueman/tests/test_main.py
Create unit tests for the terminateJobs() function covering batch termination,
reason logging, and exception handling.
Tests added to /cueman/tests/test_main.py:
- Single and batch job termination with reason tracking
- Kill reason formatting with username from getpass.getuser()
- Empty job list handling
- Exception propagation during kill operations
- Logging output verification with proper logger mocking
- Termination across various job states (RUNNING, WAITING, DEAD, SUCCEEDED)
Implementation notes:
- Removed tests for non-existent confirm_termination function
- Removed tests for unsupported force parameter
- Updated all mocking to match actual terminateJobs implementation
- Mock job.kill(), getpass.getuser(), and logger for proper isolation
Add pytest to main dependencies for improved …
> [cueman] Add Comprehensive Unit Tests for Job Termination Logic in cueman

- cuegui/cuegui/FrameMonitorTree.py
- cuegui/cuegui/JobMonitorGraph.py
- cuegui/cuegui/LayerMonitorTree.py
- https://github.com/AcademySoftwareFoundation/OpenCue/issues/1958
- The "Use Local Cores" functionality only works correctly at the Job level due to cue booking logic that assigns frames in order. When used at Layer or Frame level, it causes confusion as frames are still booked in sequence regardless of selection, and currently throws errors about no pending frames meeting criteria.
- Keeping the option only at Job level where it functions as intended.
> [cuegui] Remove "Use Local Cores" option from Layer and Frame context menus

- cuegui/cuegui/AbstractTreeWidget.py
- cuegui/cuegui/JobMonitorTree.py
- #1975 
[cuegui] Fix AttributeError when clicking on GroupWidgetItem in JobMonitorTree
- Add hasattr checks before accessing rpcObject attribute
- GroupWidgetItem doesn't inherit from AbstractWidgetItem and lacks rpcObject
- Prevents errors when clicking on group headers in the job tree
> [cuegui] Fix AttributeError when clicking on GroupWidgetItem in JobMonitorTree

- cuegui/cuegui/AbstractTreeWidget.py
- cuegui/cuegui/JobMonitorTree.py
- https://github.com/AcademySoftwareFoundation/OpenCue/issues/1977
The "Unmonitor Finished" button was not working when jobs were grouped by "Show-Shot" or "Show-Shot-Username" because it only searched for finished jobs at the root level of the tree.
- Update `removeFinishedItems()` to search within group items
- Fix `_removeItem()` to properly handle parent-child relationships
- Clean up empty groups after removing their children
- Maintain compatibility with Clear and Dependent grouping modes
> [cuegui] Fix Unmonitor Finished feature for grouped job views

- cueadmin/pyproject.toml
- cuegui/pyproject.toml
- cueman/pyproject.toml
- https://github.com/AcademySoftwareFoundation/OpenCue/issues/1990
- Align mock version requirements to mock==2.0.0 across all packages
- Use pinned versions constraints of `cuegui` ("mock==2.0.0", "pyfakefs==5.2.3") in `cueman` and `cueadmin`
- Resolves pip installation conflicts in CI pipeline
> [CI/CD] Fix mock dependency conflicts across Python packages

- .github/workflows/docs-pipeline.yml
- cueman/README.md
- cueman/cueman/main.py
- cueman/cueman_tutorial.md
- cueman/tests/test_frame_operations.py
- docs/_docs/reference/tools/cueman.md
- docs/_docs/tutorials/cueman-tutorial.md
- https://github.com/AcademySoftwareFoundation/OpenCue/issues/1929
- #1800 
Summary:
Add comprehensive unit tests for frame-specific operations and implement input validation for stagger, reorder, and frame range operations. Updated documentation to reflect new validation requirements.
Changes:
1) Unit tests (`cueman/tests/test_frame_operations.py`)
Created comprehensive test suite covering:
- Frame eat/kill/retry operations with layer and range filters
- Frame state filtering (running, waiting, dead, succeeded)
- Frame range parsing and validation
- Mark done functionality
- Stagger operations with increment validation (positive integers only)
- Reorder operations with position validation (FIRST, LAST, …
> [cueman] Add unit tests and validation for frame operations

- .gitattributes
This is to force newline style for .sh files to Unix standard on Windows.
A user reported that the checked out bash scripts used in the flyway container had Windows newlines when checked out on Windows and caused issues with the flyway migration.
> [Windows] Force newline style

- cueadmin/tests/test_proc_commands.py
- https://github.com/AcademySoftwareFoundation/OpenCue/issues/1922
Implement comprehensive unit tests for process (proc) management commands including listing, killing, and unbooking running frames. Proc management is critical for production but previously lacked test coverage.
Test coverage includes:
- Listing running procs with filters (-lp)
- Listing frame log paths (-ll)
- Killing specific procs
- Unbooking procs from hosts
- Filtering by job, show, allocation, memory, and host
- Memory filter parsing (ranges, gt/lt operators, GB specifications)
- Duration filter for long-running frames (hours with fractional support)
- Result limiting
- Complex filtering scenarios with multiple filters
- Edge cases and …
> [cueadmin] Add unit tests for proc management commands

- cueadmin/cueadmin/common.py
- cueadmin/tests/test_action_util.py
- #1925
- Create comprehensive unit tests for cueadmin.common.ActionUtil class covering factory(), getValue(), and setValue() methods
- Add 42 test cases organized into three test classes:
* ActionUtilFactoryTests: Tests action creation with various types
* ActionUtilGetValueTests: Tests value extraction from actions
* ActionUtilSetValueTests: Tests value assignment to actions
* ActionUtilIntegrationTests: Tests method interactions and edge cases
- Test coverage includes:
* All action types (PAUSE_JOB, SET_JOB_PRIORITY, SET_JOB_MIN_CORES, etc.)
* Type conversions (string to int/float, int to float)
* Boundary values (zero, negative, large values)
* Error handling for invalid action types
* Multiple value …
> [cueadmin] Add unit tests for ActionUtil class and fix protobuf field names

- cueman/tests/test_filtering.py
- #1931 
Create comprehensive tests for memory and duration filtering logic including:
- Memory range parsing (1-4 GB, gt2, lt5)
- Duration range parsing (1.5-3.0 hours)
- Unit conversion (GB to KB, hours to seconds)
- Invalid range handling and error cases
- Boundary condition testing (zero values, large values, fractional values)
- Regex pattern matching for gt/lt operators
- Default value application (DEFAULT_MIN_MEMORY, DEFAULT_MIN_DURATION)
- Filter combination with other parameters
- Extensive testing of _get_proc_filters() function
- Integration tests for buildFrameSearch() with filters
Total of 48 new tests covering all edge cases and input formats for memory and duration filtering in cueman.
> [cueman] Add Unit Tests for Memory and Duration Filtering

- .github/workflows/testing-pipeline.yml
- https://github.com/AcademySoftwareFoundation/OpenCue/issues/2017
Add test_rest_gateway job to testing pipeline that:
- Installs Go 1.21 and protobuf compiler
- Generates gRPC gateway code from proto definitions
- Runs unit tests with coverage reporting
- Uploads coverage artifacts
- Fails pipeline on test failures
This ensures REST Gateway changes are automatically validated on every push and pull request, improving reliability and reducing regressions.
> [CI/CD] Add REST Gateway tests to CI/CD pipeline

- rqd/rqd/rqmachine.py
- rqd/tests/test_rqmachine.py
- https://github.com/AcademySoftwareFoundation/OpenCue/issues/2000
Fixes issue where RQD on macOS doesn't report temp directory stats, causing hosts to fail in repair state due to missing storage information.
Changes:
- Add macOS code path in `__initMachineStats()` to set total_mcp using os.statvfs()
- Add macOS code path in `updateMachineStats()` to set free_mcp using os.statvfs()
- Add comprehensive unit tests for macOS temp directory functionality
The fix uses os.statvfs() on macOS (same as Linux) to read filesystem statistics for the temp directory, allowing proper reporting to cuebot.
> [rqd] Add macOS support for temp directory stats reporting
