AcademySoftwareFoundation/OpenCue

- cuesubmit/cuesubmit/Submission.py
- pyoutline/src/outline/backend/cue.py
- pyoutline/src/outline/backend/local.py
- pyoutline/src/outline/cuerun.py
- pyoutline/src/outline/loader.py
- pyoutline/src/outline/session.py
Fixes Issue #140 . 
Pyoutline can now accept show, shot and user instead of only pulling it from the environment.
> Allow pyoutline to accept show, shot, and user values

- cuebot/src/main/java/com/imageworks/spcue/servant/ManageService.java
- cuegui/cuegui/ServiceDialog.py
- cuesubmit/cuesubmit/Util.py
- pycue/opencue/api.py
- pycue/opencue/wrappers/__init__.py
- pycue/opencue/wrappers/service.py
- pycue/tests/api_test.py
Fixes Issue #183 
* Adds a new service wrapper to opencue api.
* Adds api tests for service calls.
* Fixes bug where max_cores was not respected at service creation.
> Create a Service wrapper and hook it up to CueGUI 

- cuebot/src/main/java/com/imageworks/spcue/servant/ManageJob.java
- cuebot/src/main/resources/public/dtd/cjsl-1.5.dtd
- cuebot/src/main/resources/public/dtd/cjsl-1.6.dtd
- cuebot/src/main/resources/public/dtd/cjsl-1.7.dtd
- cuebot/src/main/resources/public/dtd/cjsl-1.8.dtd
- cuegui/cuegui/Cuedepend.py
- cuegui/cuegui/DependDialog.py
- cuegui/cuegui/DependMonitorTree.py
- cuegui/cuegui/DependWizard.py
- cuegui/cuegui/plugins/AttributesPlugin.py
- cuesubmit/cuesubmit/Submission.py
- cuesubmit/cuesubmit/ui/Job.py
- pycue/opencue/wrappers/frame.py
- pycue/opencue/wrappers/job.py
- pycue/opencue/wrappers/layer.py
- pyoutline/src/outline/depend.py
* Fixes Issue #192.
* Fixes problems with dependency enum keys.
* Fixes some problems with the CueGui dependency wizard view.
> Fix submitting dependent jobs

- pycue/FileSequence/FrameRange.py
- pycue/FileSequence/FrameSet.py
> adding indexing to FrameSet and FrameRange objects

- cuesubmit/cuesubmit/__main__.py
- cuesubmit/cuesubmit/ui/Style.py
- cuesubmit/cuesubmit/ui/Submit.py
- cuesubmit/plugins/maya/CueMayaSubmit.py
- cuesubmit/plugins/nuke/CueNukeSubmit.py
Fixes issue #205.
Adds a scrollarea to the main widget of cuesubmit.
> Make cuesubmit scrollable

- cuesubmit/cuesubmit/Validators.py
- cuesubmit/cuesubmit/ui/Submit.py
- cuesubmit/cuesubmit/ui/Widgets.py
* Run field validators at submission time
* Setup qsettings for storing the previously used field values and add them to completors
> Run field validators at submission time

- cuegui/cuegui/HostMonitor.py
- cuegui/cuegui/ProcMonitor.py
- cuegui/cuegui/ProcMonitorTree.py
- pycue/opencue/search.py
Fixing some bugs with host and proc filtering in CueGui. Similar to PR #204
> Fixing host and proc filtering

- cuegui/cuegui/Main.py
- cuegui/cuegui/config/cuecommander.ini
Use the config file path from the QSettings object as opposed to assuming it's path.
Update the default config file path to be readable by pyside2.
> CueGUI use the config file path from QSettings

- cuesubmit/cuesubmit/Validators.py
Fixes Issue #216.
Submission with periods in the name is legal and should be allowed.
> Cuesubmit - allow periods in no special character validator

- pycue/opencue/api.py
- pycue/tests/api_test.py
Adds tests for all missing API calls.
> Improve opencue.api unit test coverage.

- cuebot/src/main/java/com/imageworks/spcue/dao/oracle/NestedWhiteboardDaoJdbc.java
- cuebot/src/main/java/com/imageworks/spcue/dao/oracle/WhiteboardDaoJdbc.java
- cuebot/src/main/java/com/imageworks/spcue/dao/postgres/NestedWhiteboardDaoJdbc.java
- cuebot/src/main/java/com/imageworks/spcue/dao/postgres/WhiteboardDaoJdbc.java
- cuegui/cuegui/CueJobMonitorTree.py
- cuegui/cuegui/GroupDialog.py
- cuegui/cuegui/MenuActions.py
- cuegui/cuegui/plugins/ShowsPlugin.py
- proto/job.proto
- pycue/opencue/wrappers/group.py
Issue #234 
Jobs and subgroups now show up under the correct root group.
> Fixing subgroups for monitor cue plugin in cuegui

- cuebot/src/main/java/com/imageworks/spcue/dao/oracle/NestedWhiteboardDaoJdbc.java
- cuebot/src/main/java/com/imageworks/spcue/dao/postgres/NestedWhiteboardDaoJdbc.java
- cuegui/cuegui/CueJobMonitorTree.py
- cuegui/cuegui/GroupDialog.py
- cuegui/cuegui/MenuActions.py
- cuegui/cuegui/Utils.py
- cuegui/cuegui/plugins/AttributesPlugin.py
- pycue/opencue/wrappers/group.py
- pycue/opencue/wrappers/job.py
- pycue/opencue/wrappers/layer.py
`GetJobWhiteboard` was only returning the groups, but it should be returning the full group and job hierarchy. 
Also, update cuegui to fix various group actions on the monitor cue view.
Issue #227
> getJobWhiteboard should return full job/group hierarchy.

- pyoutline/bin/cuerunbase.py
- pyoutline/bin/pycuerun
- pyoutline/bin/util_qc_job_layer.py
- pyoutline/outline/backend/cue.py
- pyoutline/tutorials/hello/hellomodule.py
- pyoutline/tutorials/outlines/hello.outline
- pyoutline/tutorials/outlines/hello_frame.outline
- pyoutline/versions/main.py
- pyoutline/versions/session.py
Issue #246 
* When pycuerun submits an outline the full list of returned jobs is printed to the shell.
* cleanup
> Print list of submitted jobs in pycuerun and cleanup

- cuebot/src/main/resources/opencue.properties
> Allow for environment variable setting of log directory.

- cuebot/src/main/java/com/imageworks/spcue/dispatcher/CoreUnitDispatcher.java
- cuebot/src/main/resources/opencue.properties
- cuebot/src/test/resources/opencue.properties
Add dispatcher configuration values to opencue.properties file.
> Expose dispatcher control values as properties values. Issue #252

- README.md
Tiny spelling fix on process → processed
> Minor spelling tweak

- pycue/opencue/search.py
- pycue/opencue/wrappers/show.py
- pycue/tests/file_sequence.py
- pycue/tests/search_test.py
- pycue/tests/util_test.py
- pycue/tests/wrappers/__init__.py
- pycue/tests/wrappers/show_test.py
* Adding unittests for `opencue.wrappers.show`.
* Updating existing tests to use `assertEqual`
* Fixing bugs found from tests
> Pycue show wrappers unittests

- cuegui/cuegui/Utils.py
- cuesubmit/cuesubmit/Config.py
- pycue/opencue/cuebot.py
- pyoutline/outline/io.py
- pyoutline/outline/loader.py
- pyoutline/outline/session.py
- pyoutline/outline/versions/session.py
- requirements.txt
- rqd/rqd/rqmachine.py
Upgrade to pyyaml 5.1 and use safeloader where possible.
> Pyyaml upgrade

- rqd/deploy/install_and_run.sh
- rqd/rqd/rqcore.py
Fixes Issue #272.
Catch the SIGINT signal, cancel RQD threads and then exit.
> Stop RQD threads and exit on control-c

- cueadmin/cueadmin/__main__.py
- cueadmin/cueadmin/common.py
- cueadmin/cueadmin/format.py
- cueadmin/cueadmin/output.py
- cueadmin/setup.py
- cueadmin/tests/__init__.py
- cueadmin/tests/common_tests.py
- cueadmin/tests/output_tests.py
- proto/job.proto
Progresses https://github.com/imageworks/OpenCue/issues/61
Fixes https://github.com/imageworks/OpenCue/issues/270
Big cleanup of CueAdmin code and added a bunch of new tests.
This uncovered a few bugs, and brings test coverage 50% -> 85%.
> CueAdmin code cleanup and test coverage.

- cueadmin/Dockerfile
- cueadmin/cueadmin/__main__.py
- cueadmin/cueadmin/common.py
- cueadmin/cueadmin/format.py
- cueadmin/cueadmin/output.py
- cueadmin/cueadmin/util.py
- cueadmin/tests/__init__.py
- cueadmin/tests/common_tests.py
- cueadmin/tests/output_tests.py
Progresses https://github.com/imageworks/OpenCue/issues/61
> CueAdmin Python 3 support.

- pycue/opencue/util.py
- pycue/tests/util_test.py
Remove the need for the RepeatedCompositeContainer check and fix proxy method to work when passing in existing proto Messages.
fixes #304
> Fix proxy method

- pycue/opencue/wrappers/subscription.py
- pycue/opencue/wrappers/task.py
- pycue/opencue/wrappers/util.py
- pycue/tests/wrappers/subscription_test.py
- pycue/tests/wrappers/task_test.py
- pycue/tests/wrappers/util_test.py
Fixing bugs and adding wrapper unittests for
* subscription
* task
* wrapper/util
> Adding wrapper unittests for subscription, task, and util

- cuegui/cuegui/plugins/AttributesPlugin.py
- pycue/opencue/wrappers/layer.py
- pycue/tests/wrappers/layer_test.py
- pycue/tests/wrappers/proc_test.py
- pycue/tests/wrappers/service_test.py
Adding more wrapper unittests.
* layer
* proc
* service
> adding wrapper unittests for layer, proc, service

- pycue/opencue/wrappers/job.py
- pycue/tests/wrappers/job_test.py
Adding in unittests for `opencue.wrappers.job`.
> Tests for job wrappers

- pycue/opencue/wrappers/filter.py
- pycue/tests/wrappers/filter_test.py
- pycue/tests/wrappers/frame_test.py
Fixing a couple bugs in the filter wrapper and adding tests for frame and filter wrappers.
> Adding tests for frame and filter wrappers

- cuegui/cuegui/Constants.py
> Fix the "make a suggestion" CueGUI link.

- cuebot/src/main/java/com/imageworks/spcue/dao/oracle/NestedWhiteboardDaoJdbc.java
- cuebot/src/main/java/com/imageworks/spcue/dao/postgres/NestedWhiteboardDaoJdbc.java
Fixes #339.
Add missing columns from query to fix getHostWhiteboard call.
> Add missing columns from query to fix getHostWhiteboard call

- cuegui/cuegui/Constants.py
Update CueGUI constants for user guide, suggestions, and bugs.
> Update CueGUI Constants.py

- cuesubmit/cuesubmit/ui/Submit.py
Honor the user-specified 'Chunk Size' value #365
> Honor the user-specified 'Chunk Size' value #365

- cueadmin/Dockerfile
- cuegui/Dockerfile
- cuesubmit/Dockerfile
- jenkins/Jenkinsfile
- jenkins/extract_artifacts.sh
- jenkins/publish_artifacts.sh
- jenkins/release.py
- pycue/Dockerfile
- pyoutline/Dockerfile
- rqd/Dockerfile
> Include LICENSE file in all Python tarballs and publish it alongside the other build artifacts.

- .github/PULL_REQUEST_TEMPLATE.md
Fixes #328 
Help contributors to provide the needed info and guide them through how they can use the various Pull Request options.
Markdown is bit weird here because the "raw" version is the default view when you create a new PR, so I did my maximize readability in both the "Write" and "Preview" tabs.
> Add a Github Pull Request template.

- tsc/meetings/2019-07-17.md
> Meeting notes from July 17 meeting.

- tsc/meetings/2019-07-31.md
As this meeting will be more public than usual, I wanted to check this in now. We can amend it as needed, and anyone can suggest new items via PR now or in person when the meeting happens.
I'll update this file after the meeting with notes.
> Check in initial meeting agenda for July 31 meeting.

- SECURITY.md
Per https://help.github.com/en/articles/adding-a-security-policy-to-your-repository
> Add a security policy.

- pycue/opencue/api.py
- pycue/opencue/wrappers/depend.py
- pycue/opencue/wrappers/filter.py
- pycue/opencue/wrappers/frame.py
- pycue/opencue/wrappers/host.py
- pycue/opencue/wrappers/job.py
- pycue/opencue/wrappers/layer.py
- pycue/opencue/wrappers/proc.py
- pycue/tests/wrappers/depend_test.py
- pycue/tests/wrappers/filter_test.py
- pycue/tests/wrappers/frame_test.py
- pycue/tests/wrappers/host_test.py
- pycue/tests/wrappers/job_test.py
- pycue/tests/wrappers/layer_test.py
- pycue/tests/wrappers/proc_test.py
Fixes #389
Expose the proto enums as python Enums in the appropriate wrapper objects.
> Add enums to appropriate wrappers. 

- cuegui/Dockerfile
- cuegui/cuegui/MenuActions.py
- cuegui/setup.py
- cuegui/tests/MenuActions_tests.py
- cuegui/tests/__init__.py
#396 
Some initial CueGUI tests.
> Add tests for JobActions and LayerActions.

- cuegui/cuegui/MenuActions.py
- cuegui/tests/MenuActions_tests.py
- proto/job.proto
- pycue/opencue/wrappers/filter.py
- pycue/opencue/wrappers/frame.py
- pycue/opencue/wrappers/group.py
- pycue/opencue/wrappers/host.py
- pycue/opencue/wrappers/layer.py
- pycue/opencue/wrappers/proc.py
- pycue/opencue/wrappers/show.py
#396 
- Add tests for the FrameActions class.
- Make some changes to the previously-added JobActions and LayerActions tests to improve them.
> Add more MenuActions tests.

- rqd/rqd/rqcore.py
- rqd/rqd/rqnimby.py
- rqd/tests/rqcore_tests.py
> Add an initial round of RqCore tests.

- rqd/rqd/rqcore.py
- rqd/tests/rqcore_tests.py
#396 
This should bring us up to pretty near full coverage on the main RqCore class. There are a few other classes in that file (file coverage only up to about ~55%) but I'll address those in followup changes.
> Add more RqCore unit tests.

- cuegui/cuegui/FrameMonitorTree.py
Fixes #451 
Remove unnecessary call that was causing segfault.
> remove unnecessary exec_ that was causing crash.

- cuegui/cuegui/Main.py
- cuegui/cuegui/PreviewWidget.py
- cuegui/cuegui/ThreadPool.py
- cuegui/cuegui/Utils.py
Fixes #372 
Keep track of and close all `WorkerThreads` created by cuegui.
> shutdown QThreads on application close.

- tsc/meetings/2019-09-18.md
> Check in notes from Sep 18 TSC meeting.

- cuegui/cuegui/FrameMonitorTree.py
Fixes #477 
Ensure that all sortable columns have valid sort functions in the FrameMonitorTree.
> Make sure all columns have valid sort functions

- rqd/rqd/rqnimby.py
- rqd/tests/rqnimby_tests.py
#396 
Brings file coverage to 87%, RQD coverage to 72%.
> Add unit tests for Nimby.

- cuegui/cuegui/Comments.py
Signal name has been changed. Use text variant.
Closes https://github.com/AcademySoftwareFoundation/OpenCue/issues/507
> Fix comment dropdown for pyside 2

- cuegui/cuegui/ProcMonitorTree.py
- cuegui/cuegui/plugins/MonitorJobsPlugin.py
Closes https://github.com/AcademySoftwareFoundation/OpenCue/issues/515
When double-clicking a frame in the proc view add the job to the
monitoring widget.
> Add double click to proc view

- cuegui/cuegui/plugins/LogViewPlugin.py
- cuegui/tests/FrameMonitorTree_tests.py
- cuegui/tests/plugins/LogViewPlugin_tests.py
- cuegui/tests/plugins/__init__.py
- cuegui/tests/test_utils.py
#396 
Brings file coverage to 81%, CueGUI coverage up to 28%.
> Add unit tests for the log viewer plugin.

- pycue/opencue/wrappers/layer.py
Closes https://github.com/AcademySoftwareFoundation/OpenCue/issues/429
Add ChunkSize function. reduce the reliance on `.data.` values being called directly.
> Add wrapper function for chunk size on layer.

- cuegui/cuegui/MenuActions.py
- cuegui/tests/MenuActions_tests.py
- pycue/opencue/wrappers/layer.py
Closes https://github.com/AcademySoftwareFoundation/OpenCue/issues/513
Create a function to return the parent job.
> fix retry all dead frames on a layer

- cuegui/cuegui/CueJobMonitorTree.py
- cuegui/cuegui/Utils.py
Closes https://github.com/AcademySoftwareFoundation/OpenCue/issues/511
Pyside 2 has changed the way it uses stream.
Changed method of reparenting. I was having an issue using the proxy items.
> Fix drag and drop in the cue job monitor

- tsc/meetings/2019-11-13.md
> Notes from TSC meeting Nov 13.

- cuegui/cuegui/plugins/AttributesPlugin.py
Fixes #524 
Copies attribute value to clipboard when selected.
> feat: Copy attribute value to clipboard on selecting

- cuesubmit/Dockerfile
- cuesubmit/cuesubmit/Config.py
- cuesubmit/cuesubmit/Constants.py
- cuesubmit/cuesubmit/JobTypes.py
- cuesubmit/cuesubmit/Layer.py
- cuesubmit/cuesubmit/Submission.py
- cuesubmit/cuesubmit/Util.py
- cuesubmit/cuesubmit/Validators.py
- cuesubmit/cuesubmit/__main__.py
- cuesubmit/cuesubmit/ui/Command.py
- cuesubmit/cuesubmit/ui/Frame.py
- cuesubmit/cuesubmit/ui/Job.py
- cuesubmit/cuesubmit/ui/SettingsWidgets.py
- cuesubmit/cuesubmit/ui/Style.py
- cuesubmit/cuesubmit/ui/Submit.py
- cuesubmit/cuesubmit/ui/Widgets.py
- cuesubmit/tests/Config_tests.py
- cuesubmit/tests/Layer_tests.py
- cuesubmit/tests/Submission_tests.py
#557 
Very few changes needed here -- basically just bringing the imports to the same standard used elsewhere and running the unit tests under both python versions.
> CueSubmit Python 3 support.

- cuebot/src/main/java/com/imageworks/spcue/rqd/RqdClientGrpc.java
- proto/rqd.proto
- rqd/rqd/rqdservicers.py
Closes https://github.com/AcademySoftwareFoundation/OpenCue/issues/539
In RQD the kill message reported if passed in.
Pass the reason for killing the frame along so it shows in the logs.
> Fix passing message to kill frame

- tsc/ccla.md
- tsc/icla.md
Signed-off-by: John Mertic <jmertic@linuxfoundation.org>
> Add CCLA and ICLA text

- cuebot/src/main/resources/conf/ddl/postgres/migrations/V3__Increase_show_length.sql
Closes https://github.com/AcademySoftwareFoundation/OpenCue/issues/518
Increase the length of show names to 512.
Update the size by altering the Postgres pg_attribute for the relevant views.
> Alter table to increase show lengh

- pycue/opencue/api.py
Fixes https://github.com/AcademySoftwareFoundation/OpenCue/issues/555
Fix some incorrect Python Docstrings in pycue/opencue/api.py
> Fix pycue/opencue/api.py doc strings

- CODEOWNERS
Approved by the TSC as new project committers.
> Add Christian and Lars to CODEOWNERS.

- tsc/meetings/2020-01-08.md
> TSC notes from Jan 8 meeting.

- ci/testing-pipeline.yml
> CY2020 images have been promoted to prod now.

- cuebot/src/main/java/com/imageworks/spcue/service/JobLauncher.java
- cuesubmit/cuesubmit/ui/Submit.py
- cuesubmit/cuesubmit/ui/Widgets.py
#343
Added dummy label 'no-show-exists' instead of completely empty list when no shows are present in DB to limit 'out of range' error.
> Add dummy label to cuesubmit when no shows to solve #343

- cuebot/src/main/java/com/imageworks/spcue/dispatcher/HostReportHandler.java
Closes https://github.com/AcademySoftwareFoundation/OpenCue/issues/530
Don't Change Lock state when receiving a host report. This is an explicit
action.
> Remove change to Lock state on startup

- tsc/meetings/2020-02-19.md
> Meeting notes from Feb 19 TSC meeting.

- cuebot/src/main/java/com/imageworks/spcue/servant/ManageAction.java
- cuegui/cuegui/AbstractWidgetItem.py
- cuegui/cuegui/FilterDialog.py
- cuegui/cuegui/Utils.py
- pycue/opencue/wrappers/filter.py
- pycue/opencue/wrappers/group.py
- pycue/tests/wrappers/filter_test.py
Fixes #623 
- Fix backend code for modifying actions -- the servant was trying to operate on objects without IDs populated, which caused it to fail silently.
- Fix various uses of enum values in the filters dialog.
- Fix filter ordering (actually a fix for ordering in lots of widgets -- problem was in a base class).
- Don't reorder filters until changes have been processed, to make sure we're sorting on the latest data.
> Batch of fixes for filters, matchers, and actions.

- cuesubmit/cuesubmit/__main__.py
https://github.com/AcademySoftwareFoundation/OpenCue/issues/649
Changed the resize dimensions, should make the default size of the CueSubmit window large enough to avoid scrolling.
> Changed resize for issue #649

- tsc/meetings/2020-03-04.md
> Notes from March 4 TSC meeting.

- README.md
N/A
It's a simple spelling mistake in the README.md file, change has been done is from procs to processes.
It's also helpful to describe **why** you're making this change.
> Spelling mistake procs to processes

- cuegui/cuegui/FilterDialog.py
- cuegui/tests/FilterDialog_tests.py
- pycue/opencue/wrappers/filter.py
#396 
Tests for a few of the UI components contained in FilterDialog. Brings file coverage to 64%.
We can get coverage higher here by testing the other UI components, but this PR is getting large enough as is.
> First round of unit tests for FilterDialog.

- cuegui/cuegui/Constants.py
- rqd/rqd/cuerqd.py
Issue #641  
Automatically pull the version number from VERSION.in file.
Default value is set to 'UNKNOWN'.
> Version number pulled from version.in file to constant.py

- CONTRIBUTING.md
Folks have reported that the actual CLA text is hard to find.
> Link to the CLAs in CONTRIBUTING.

- tsc/meetings/2020-04-29.md
> Meetings notes from Apr 29 TSC meeting.

- tsc/meetings/2020-05-27.md
> Notes from May 27 TSC meeting.

- CODEOWNERS
- tsc/gsoc/2020-06-01.md
This also adds Shiva as a codeowner for the `tsc/gsoc/` directory, to ensure he gets review requests for GSoC-related PRs.
> Notes from June 1 GSoC meeting.

- CODEOWNERS
- tsc/gsoc/2020-06-08.md
> Notes from June 8 GSoC meeting.

- rqd/rqd/rqmachine.py
Signed-off-by: John Mertic <jmertic@linuxfoundation.org>
One line for each Issue. If merging this Pull Request should auto-close the Issue on that line,
preface the Issue URL/Number with "Fixes". Every Pull Request should have at least one Issue
linked.
If it's a simple change, a sentence or two is probably sufficient. If it's a complex change,
adding a list of the three or four main points can be helpful.
It's also helpful to describe **why** you're making this change.
> Move from whitelist to acceptlist

- cuegui/cuegui/ProgressDialog.py
https://sonarcloud.io/project/issues?id=AcademySoftwareFoundation_OpenCue&issues=AW6ALwuZqVEDTlK2PrkA&open=AW6ALwuZqVEDTlK2PrkA
Update the function call to match the name which it's imported under. This was flagged as a bug by SonarCloud (see link above).
> Fix function call to match imported namespace.

- tsc/meetings/2020-06-10.md
> Notes from June 10 TSC meeting.

- .github/workflows/release-pipeline.yml
#715 
Fix the var name, and pull the full Git history as elsewhere.
> Fix variable name in the release pipeline.

- tsc/gsoc/2020-06-22.md
> Notes from June 22 GSoC meeting.

- tsc/meetings/2020-06-24.md
> Notes from June 24 TSC meeting.

- rqd/rqd/rqcore.py
Windows might fail while trying to rotate logs for checking if file is being used by another process. The frame execution doesn't need to be halted for this, for windows the system should just log the error and move on.
Besides that, also keep Windows rqd's from calling `os.getuid()` which is not available on Windows environments
> Skip error rotating logs on windows

- tsc/gsoc/2020-07-20.md
> Notes from July 20 GSoC meeting.

- cuegui/cuegui/FilterDialog.py
Fixes issue #636 
Fixes loosing selection issue on filter dialog
> Fix loosing selection issue on filter dialog

- CODEOWNERS
As approved during the last TSC meeting.
> Add Diego to CODEOWNERS.

- cuebot/src/main/java/com/imageworks/spcue/util/FrameRange.java
#790 
This resolves the compiler warning about "unchecked conversion required".
> Use typesafe method to generate inverted stepped frame range.

- cuebot/src/test/java/com/imageworks/spcue/test/dispatcher/RedirectManagerTests.java
#790 
Resolves a compiler warning about using deprecated methods.
> Use non-deprecated method for asserting non empty string.

- cuebot/build.gradle
- cuebot/src/main/java/com/imageworks/spcue/dao/oracle/HostDaoJdbc.java
- cuebot/src/main/java/com/imageworks/spcue/dao/oracle/RedirectDaoJdbc.java
- cuebot/src/main/java/com/imageworks/spcue/dao/postgres/HostDaoJdbc.java
- cuebot/src/main/java/com/imageworks/spcue/dao/postgres/RedirectDaoJdbc.java
- cuebot/src/main/java/com/imageworks/spcue/dispatcher/HostReportHandler.java
#790 
Existing generated Java code contains many usages of deprecated APIs, this upgrade fixes that.
After upgrading, I've also fixed deprecated usages of these classes within our own code.
> Upgrade protoc java compiler to 3.13.0.

- cuebot/src/main/java/com/imageworks/spcue/config/AppConfig.java
#790 
This fixes an `unchecked` warning from the Java compiler, and in my testing has no effect on the app's serving of the job submission endpoint.
> Specify a type for jobLaunchServlet().

- cuegui/cuegui/CueJobMonitorTree.py
- cuegui/cuegui/JobMonitorTree.py
Fixes issue preventing the middle-click copy feature from working on JobTree widgets
> Fix middle-click copy

- pycue/opencue/wrappers/frame.py
Feature was implemented on the backend but missing in the API
> Add setCheckpointState method to api

- cuegui/cuegui/CueJobMonitorTree.py
The Api expects a list group ids strs not type Group
> bugfix DropEvent

- cuebot/src/main/java/com/imageworks/spcue/rqd/RqdClientGrpc.java
#790 
See https://stackoverflow.com/questions/4337313/why-is-class-preferred-to-class for why this is preferred.
> Fix rawtypes warning on ManagedChannelBuilder.

- cuebot/src/test/java/com/imageworks/spcue/test/dao/oracle/ActionDaoTests.java
- cuebot/src/test/java/com/imageworks/spcue/test/dao/postgres/ActionDaoTests.java
#790 
The `import` at the top of the file is enough, this instance isn't needed. This resolves `static` lint warnings.
> Do not access ActionType values via instance.

- cuegui/cuegui/ItemDelegate.py
- cuegui/cuegui/LayerMonitorTree.py
Add progress bar calculated based on layer completion status.
Closes #769
> Add progress status for layers

- .github/workflows/sonar-cloud-pipeline.yml
- cuebot/build.gradle
#801 
Some rules aren't useful to us, this sets up some config for disabling them based on code location.
> Set up config for disabling SonarCloud rules in Cuebot analysis.

- cuegui/cuegui/MenuActions.py
- cuegui/cuegui/ServiceDialog.py
- pycue/opencue/wrappers/show.py
Creating Service at a show level was failing due to errors on the ServiceDialog implementation
> bug fixes for creating Service at show level

- cuegui/cuegui/FilterDialog.py
Increased max action memory size on FilterDialog
> Increase max render memory on 

- .github/PULL_REQUEST_TEMPLATE.md
Fixes #800
This resolves a CII badge item about documenting our policy on adding new tests.
> Add note to PR template on adding tests for new code.

- cuebot/build.gradle
- cuebot/src/main/java/com/imageworks/spcue/Entity.java
- cuebot/src/main/java/com/imageworks/spcue/SortableShow.java
- cuebot/src/main/java/com/imageworks/spcue/service/DepartmentManagerService.java
#801 
Some minor changes to resolve SonarCloud warnings.
> Fix or ignore a few issues flagged by SonarCloud.

- pycue/opencue/wrappers/host.py
To read `os` value from RQD hosts.
> Add Host.os to pycue wrapper

- connectors/prometheus_metrics/Dockerfile
- connectors/prometheus_metrics/metrics
- connectors/prometheus_metrics/requirements_metrics.txt
- sandbox/docker-compose.yml
Export cuebot metric's into a Prometheus format.
Closes #843
> Example of exporting cuebot metric's

- cuebot/src/main/java/com/imageworks/spcue/dispatcher/commands/DispatchBookHost.java
- cuebot/src/main/java/com/imageworks/spcue/service/RedirectService.java
- cuebot/src/main/java/com/imageworks/spcue/servlet/JobLaunchServlet.java
#801 
A few more places where NPE can be thrown -- work around it when we can and throw exceptions otherwise.
> Fix another few potential NullPointerExceptions.

- cuebot/src/main/java/com/imageworks/spcue/SortableShow.java
- cuebot/src/main/java/com/imageworks/spcue/dispatcher/commands/DispatchBookHost.java
#801 
The convention is to check type explicitly instead of our existing approach of blindly cast then check for `ClassCastException`.
> Add type tests to equals() before casting.

- CODEOWNERS
As discussed during the last meeting, Add IdrisMiles to code owners.
> Add IdrisMiles to code owners

- cuegui/cuegui/CueJobMonitorTree.py
Increment the column id's.
Add extra empty column value for group and root group types
Closes #885
> Fix column id count

- ci/pylintrc_test
- ci/run_python_tests.sh
- cueadmin/cueadmin/__main__.py
- cueadmin/cueadmin/common.py
- cueadmin/cueadmin/format.py
- cueadmin/cueadmin/output.py
- cueadmin/cueadmin/util.py
- cueadmin/tests/common_tests.py
- cueadmin/tests/output_tests.py
#78 
Configure lint to run for CueAdmin and make many minor changes to satisfy the lint checks.
> Lint the CueAdmin code.

- rqd/rqd/rqconstants.py
- rqd/rqd/rqmachine.py
- rqd/tests/rqmachine_tests.py
> Remove ptree feature

- ci/run_python_tests.sh
- cuesubmit/cuesubmit/Config.py
- cuesubmit/cuesubmit/Constants.py
- cuesubmit/cuesubmit/JobTypes.py
- cuesubmit/cuesubmit/Layer.py
- cuesubmit/cuesubmit/Submission.py
- cuesubmit/cuesubmit/Util.py
- cuesubmit/cuesubmit/Validators.py
- cuesubmit/cuesubmit/__main__.py
- cuesubmit/cuesubmit/ui/Command.py
- cuesubmit/cuesubmit/ui/Frame.py
- cuesubmit/cuesubmit/ui/Job.py
- cuesubmit/cuesubmit/ui/SettingsWidgets.py
- cuesubmit/cuesubmit/ui/Style.py
- cuesubmit/cuesubmit/ui/Submit.py
- cuesubmit/cuesubmit/ui/Widgets.py
- cuesubmit/cuesubmit/ui/__init__.py
- cuesubmit/tests/Config_tests.py
- cuesubmit/tests/Layer_tests.py
- cuesubmit/tests/Submission_tests.py
- cuesubmit/tests/Validators_tests.py
#78 
Configure linting for the CueSubmit and make many minor changes to get lint checks to pass.
> Lint CueSubmit code.

- ci/run_python_tests.sh
- rqd/rqd/__main__.py
- rqd/rqd/cuerqd.py
- rqd/rqd/rqconstants.py
- rqd/rqd/rqcore.py
- rqd/rqd/rqdservicers.py
- rqd/rqd/rqexceptions.py
- rqd/rqd/rqmachine.py
- rqd/rqd/rqnetwork.py
- rqd/rqd/rqnimby.py
- rqd/rqd/rqswap.py
- rqd/rqd/rqutil.py
- rqd/tests/cuerqd_tests.py
- rqd/tests/rqconstants_tests.py
- rqd/tests/rqcore_tests.py
- rqd/tests/rqmachine_tests.py
- rqd/tests/rqnimby_tests.py
- rqd/tests/test_cuebot_listener.py
#78 
Configure linting for RQD main and test code. Make many minor changes to get lint checks to pass.
> Lint RQD code.

- ci/pylintrc_test
- cuegui/cuegui/LayerDialog.py
- cuegui/tests/LayerDialog_tests.py
#396 
Add unit tests for the LayerDialog widget. This brings file coverage up to 91%.
> Add unit tests for LayerDialog.

- pyoutline/outline/depend.py
- pyoutline/outline/event.py
- pyoutline/outline/io.py
- pyoutline/outline/layer.py
- pyoutline/tests/layer_test.py
#396 
Add more unit tests for the `outline.layer` module. This brings file coverage up to 89%.
> Add unit tests for outline.layer.

- cuegui/cuegui/ServiceDialog.py
1. Select 'shell'
2. Check 'Threadable'
3. Uncheck 'util' tag
4. 'Save'
5. 'Yes'
6. Everything back to previous state.
https://user-images.githubusercontent.com/81904/111885123-fa1eac00-8982-11eb-94fc-869747629a86.mov
Update `__service` with selected service. (It used to be never updated.)
> Fix serivce update

- tsc/meetings/2021-02-17.md
- tsc/meetings/2021-03-03.md
- tsc/meetings/2021-03-31.md
> Notes from last three TSC meetings.

- cuebot/src/main/java/com/imageworks/spcue/servant/ManageAllocation.java
- cuebot/src/test/java/com/imageworks/spcue/test/servant/FakeStreamObserver.java
- cuebot/src/test/java/com/imageworks/spcue/test/servant/ManageAllocationTests.java
Most of the logic expects < facility >.< name > format but gRPC message handler doesn't take care of it.
> Fix manage allocation

- cuebot/src/main/java/com/imageworks/spcue/dao/postgres/JobDaoJdbc.java
- cuebot/src/test/java/com/imageworks/spcue/test/dao/postgres/JobDaoTests.java
`job.facilityId` should be `pk_facility`.
> Fix JobDetail mapper

- pycue/opencue/cuebot.py
Fix a few lint warnings introduced into `master` recently.
> Fix lint warnings.

- cuegui/Dockerfile
Upgraded PySide has some new requirements when creating X windows.
> Fix X window issues in the Docker image.

- sandbox/README.md
The information here has been merged into a guide page with much more detail.
> Update sandbox README to point to the user guide.

- rqd/rqd/rqmachine.py
`nvidia-smi` just works on Windows as well as Linux for NVIDIA GPU with Path `C:\Program Files\NVIDIA Corporation\NVSMI`.
> Support GPU for Windows

- docs/conf.py
- docs/requirements.txt
Fixes #1065
* Per https://github.com/sphinx-doc/sphinx/issues/9841, upgrade Sphinx to resolve an issue with an upstream dependency.
* Upgrade our Sphinx theme as well, to a version that supports the latest Sphinx version.
* Replace the theme's `canonical_url` setting with the Sphinx-level `html_baseurl`, as described by https://sphinx-rtd-theme.readthedocs.io/en/stable/configuring.html#confval-canonical_url.
> Upgrade Sphinx and theme to fix dependency issue.

- cuegui/cuegui/CueJobMonitorTree.py
Users noticed a lag with the cue monitor job tree with many jobs (multiple folders with +200-500 jobs). The processUpdate function loops over all jobs for each group and each time makes an expensive API/db call, change code to only make one extensive api call per group job ids.
> Optimize CueMoniterTree processUpdate API call

- connectors/prometheus_metrics/metrics
Visualize gloval licensing limits usage:
- Limits per show summing frames by status
- Limit global capacity (percent)
> [metrics] add limits

- cuebot/src/main/java/com/imageworks/spcue/dao/DispatcherDao.java
- cuebot/src/main/java/com/imageworks/spcue/dao/postgres/DispatcherDaoJdbc.java
- cuebot/src/main/java/com/imageworks/spcue/dispatcher/CoreUnitDispatcher.java
- cuebot/src/main/java/com/imageworks/spcue/dispatcher/DispatchSupport.java
- cuebot/src/main/java/com/imageworks/spcue/dispatcher/DispatchSupportService.java
I have found the issue with building the docker image of cuebot on linux, some tests was failed although they was not failed during local build. After investigating I have reached problem is in "ShowCache" of "DispatcherDaoJdbc" class. I think one of test put empty value in cache and it doesn't expire during build in docker, but in during local it does.
I have added the flag "testMode" and method for set it and clear cache. In my opinion it will help tests to be more indepentent.
Failed tests:
```
> Task :test
com.imageworks.spcue.test.dispatcher.CoreUnitDispatcherTests > testDispatchHostToShowNoPrefer FAILED
java.lang.AssertionError at CoreUnitDispatcherTests.java:191
com.imageworks.spcue.test.dispatcher.CoreUnitDispatcherTests > testDispatchHost FAILED
java.lang.AssertionError at …
```
> Fix: Failed tests due to cache

- cuebot/src/main/java/com/imageworks/spcue/dispatcher/HostReportHandler.java
When a host marked as REBOOT_WHEN_IDLE was still reporting a running frame, it would
automatically revert the host's status to UP. The logic has been fixed to only trigger
the status update on boot reports.
> Fix bug affecting REBOOT_WHEN_IDLE hosts

- cuegui/cuegui/ServiceDialog.py
Allow setting minimum memory increase in Cuecommander Service Properties menu
> Add OOM Increase field to Service Properties

- rqd/rqd/rqmachine.py
Fixes #1189.
Problem is described in #1189 and the comment in the code below explains the change.
> Reduce the log level when failing to read a stat file.

- rqd/rqd/rqcore.py
- rqd/rqd/rqmachine.py
Hello !
Here are the changes I needed to make RQD work for our usage on Windows.
Let me know if I need to change anything.
RQD Fixes for Windows:
* Use environment with `subprocess.Popen` on Windows (`runWindows`)
* Fix environment for Windows (add `PATH`, remove `MAIL` and `HOME`)
* Escape some characters in the .bat file
RQD Fix for all platforms:
* Don't replace the `PATH` variable but extend it instead (it was required for some of my usage on Windows)
Issues:
- https://github.com/AcademySoftwareFoundation/OpenCue/issues/1211
- https://github.com/AcademySoftwareFoundation/OpenCue/issues/1181
> RQD: fixes for runWindows

- requirements.txt
From #1249, which seems to be stuck due to branch protections.
> Upgrade future to 0.18.3.

- ci/run_integration_test.sh
https://github.com/AcademySoftwareFoundation/OpenCue/issues/1374
Integration script issue also results in packaging pipeline workflow failing, leading to issues while developing integration tests https://github.com/AcademySoftwareFoundation/OpenCue/pull/1309#issuecomment-2145509478.
Update `jq` commands in the script to support new changes to the `docker compose` commands.
> Fix jq commands in integration test script

- .gitignore
Simply add .eggs dir to .gitignore
> Add .eggs to gitignore

- cuebot/src/main/java/com/imageworks/spcue/servant/ManageProc.java
Fix two issues on the ManageProc logic.
1- When a proc no longer exists and the jdbc query throws an unhandled EmptyResultDataAccess exception instead of returning a proper status to the requester. 
2- Use the correct Id when redirecting a proc to a group.
> ManageProc bugfix

- pycue/FileSequence/FileSequence.py
- pycue/FileSequence/__init__.py
- pycue/tests/file_sequence.py
- pyoutline/tests/layer_test.py
This fixes https://github.com/AcademySoftwareFoundation/OpenCue/issues/242
Added `FileSequence.FileSequence` class to parse filepaths. It is needed to properly support `io.FileSpec`
> Add FileSequence

- cuegui/cuegui/Main.py
- cuegui/cuegui/Plugins.py
This fixes reading the window states from config and fixes loading single widget windows from the config file.
> Fix reading CUEGUI window states in config file

- cuegui/cuegui/plugins/MonitorJobsPlugin.py
Fix typo `ff` and improve the comments on the logic responsible for parsing user input when loading jobs.
> Fix minor typo and improve comments

- samples/rqd/blender/Dockerfile
Supports updates made in PR https://github.com/AcademySoftwareFoundation/OpenCue/pull/1440
Fixes issues in Blender Dockerfile to support Rockylinux base image updates.
> [RQD] Fix build issues with Blender dockerfile

- cuegui/cuegui/FrameMonitor.py
Fix issue preventing pagination buttons from working properly on the Frame Monitor plugin as reported by #1482
Fixes #1482
> Frame Monitor minor pagination GUI fixes

- cuegui/cuegui/Main.py
- cuegui/cuegui/MainWindow.py
- cuegui/cuegui/plugins/LogViewPlugin.py
When the application is closed or killed, an exit_handler is triggered to save the state on a qt settings file.
> [cuegui] Add exit handler to save state

- cuebot/src/main/java/com/imageworks/spcue/dispatcher/FrameCompleteHandler.java
Auto-retrying frames killed automatically by the OOM-kill logic was not working as expected. RQD is currently not able to report exit_signal=9 when a frame is killed by the OOM logic. The current solution sets exitStatus to Dispatcher.EXIT_STATUS_MEMORY_FAILURE before killing the frame, this enables auto-retrying frames affected by the logic when they report with a frameCompleteReport.
> [cuebot] Fix the issue with auto-retrying killed frames

- rqd/rqd/__main__.py
- rqd/rqd/rqconstants.py
Logging was not following the configured constants. Now there's also a way to deactivate file logging by not setting a level on the config file (rqd.conf)
> [rqd] Refactor rqd logging

- cuegui/cuegui/Constants.py
Improve handling of VERSION.in file with specific error handling and code cleanup
> Refactor VERSION.in file handling

- cuegui/cuegui/config/cuegui.yaml
- Add `rocky9` log root to `render_logs.root` in `cuegui.yaml`
> [cuegui] Add Rocky 9 log root in cuegui.yaml

- cuebot/src/main/java/com/imageworks/spcue/dispatcher/FrameCompleteHandler.java
- cuebot/src/main/java/com/imageworks/spcue/dispatcher/HostReportHandler.java
- cuebot/src/main/java/com/imageworks/spcue/dispatcher/RedirectManager.java
- cuebot/src/main/java/com/imageworks/spcue/dispatcher/commands/DispatchBookHost.java
- cuebot/src/test/java/com/imageworks/spcue/test/dispatcher/TestBookingQueue.java
Changes added on https://github.com/AcademySoftwareFoundation/OpenCue/pull/1570 caused a NullPointerException due to an incorrect @Autowire property.
Fixes #1572
> [cuebot] Fix issue #1572

- rest_gateway/opencue_gateway/main.go
- Added log messages for JWT validation, gRPC handler registration, and other rest_gateways logs
- Modified `jwtMiddleware` to log successful token validation and access requests
- Refactored gRPC handler registration into a centralized function
- Created `registerGRPCHandlers` function to streamline and consolidate the registration of multiple gRPC service handlers
- Simplified code structure by using a loop to register each handler, improving maintainability and readability
- Added logging for individual handler registration success and errors to facilitate debugging
> [rest_gateway] Enhanced logging and error handling for gRPC gateway initialization

- cuebot/src/main/java/com/imageworks/spcue/dao/postgres/DispatchQuery.java
- cuebot/src/main/java/com/imageworks/spcue/dao/postgres/FrameDaoJdbc.java
- cuebot/src/main/java/com/imageworks/spcue/dao/postgres/NestedWhiteboardDaoJdbc.java
- cuebot/src/main/java/com/imageworks/spcue/dao/postgres/ProcDaoJdbc.java
#1591  
This is a different take on the MR #1594 which only changes the SQL queries instead of the Java code.
> [cuebot] Convert null value from job.str_os to empty string in SQL

- rqd/rqd/rqcore.py
- Fix Lint error included in the PR https://github.com/AcademySoftwareFoundation/OpenCue/pull/1649
> [rqd] Fix Lint error in the rqcore.py

- api_docs/conf.py
- api_docs/requirements.txt
- ci/build_sphinx_docs.sh
Small fix for new path of the api docs
Update sphinx to 8.1.3 and sphinx-rtd-theme to 3.0.2
> Small fix for building docs in CI/CD and update sphinx

- cuegui/cuegui/Main.py
- Enhanced the __setup_sentry() function to log an info message if Sentry is disabled due to missing DSN.
- Replaced warning on ImportError with a more informative info log when sentry_sdk is not installed but DSN is set.
- Added a catch-all exception to log unexpected errors during Sentry initialization.
- Avoids misleading warning logs when Sentry is not intended to be used.
Previous message:
logger.warning('Failed to import Sentry')
New message:
logger.info('Sentry DSN is set but sentry_sdk is not installed.')
#1700
> [cuegui] Improve Sentry setup to log clearer messages and handle optional import

- rqd/rqd/rqmachine.py
Fixes a possible error when a child doesn't have a session when collecting sessions on rssUpdate
> [rqd] Fix session keyError

- .github/workflows/rust.yml
- .gitignore
- rust/crates/dummy-cuebot/src/main.rs
- rust/crates/dummy-cuebot/src/rqd_client.rs
- rust/crates/opencue-proto/build.rs
- rust/crates/opencue-proto/src/lib.rs
- rust/crates/rqd/src/config/config.rs
- rust/crates/rqd/src/config/mod.rs
- rust/crates/rqd/src/frame/cache.rs
- rust/crates/rqd/src/frame/frame_cmd.rs
- rust/crates/rqd/src/frame/logging.rs
- rust/crates/rqd/src/frame/manager.rs
- rust/crates/rqd/src/frame/running_frame.rs
- rust/crates/rqd/src/main.rs
- rust/crates/rqd/src/report/report_client.rs
- rust/crates/rqd/src/servant/mod.rs
- rust/crates/rqd/src/servant/rqd_servant.rs
- rust/crates/rqd/src/servant/running_frame_servant.rs
- rust/crates/rqd/src/system/linux.rs
- rust/crates/rqd/src/system/machine.rs
- rust/crates/rqd/src/system/macos.rs
- rust/crates/rqd/src/system/manager.rs
- rust/crates/rqd/src/system/nimby.rs
Clippy provides additional safety checks to rust projects and having it as part of the CICD is a good practice.
All suggestions have been applied
> [rust/rqd] Add clippy check to rust project

- .github/workflows/packaging-pipeline.yml
- .github/workflows/release-pipeline.yml
- Added tag name verification to ensure code version matches tag.
- Updated packaging outputs to include `cueman` and `cuegui`.
- Removed unused Docker image build steps.
> [CI/CD] Refactor release pipeline: verify tags and streamline outputs

- .github/workflows/packaging-pipeline.yml
- .github/workflows/release-pipeline.yml
This re-enables the rqd docker image in master and release pipelines
> [CI] reenable rqd docker image

- cueadmin/pyproject.toml
- cuegui/pyproject.toml
- cueman/pyproject.toml
- cuesubmit/pyproject.toml
- proto/pyproject.toml
- pycue/pyproject.toml
- pyoutline/pyproject.toml
- rqd/pyproject.toml
* Set Python requirements, descriptions, and README references for all Python projects in `pyproject.toml`.
Fixes #1883 
Co-authored-by: Jimmy Christensen <Lithorus@gmail.com>
Co-authored-by: Ramon Figueiredo <rfigueiredo@imageworks.com>
> [pypi] Update pyproject.toml files with descriptions and README files

- docker-compose.yml
- docs/_docs/developer-guide/rest-gateway-development.md
- docs/_docs/getting-started/deploying-rest-gateway.md
- docs/_docs/other-guides/deploying-rest-gateway.md
- docs/_docs/reference/rest-api-reference.md
- docs/_docs/tutorials/rest-api-tutorial.md
- docs/_docs/user-guides/using-rest-api.md
- rest_gateway/.gitignore
- rest_gateway/Dockerfile
- rest_gateway/README.md
- rest_gateway/opencue_gateway/gateway.go
- rest_gateway/opencue_gateway/main.go
- rest_gateway/opencue_gateway/main_test.go
- rest_gateway/opencue_gateway/test_endpoints.sh
- rest_gateway/test_docker_gateway.sh
- rest_gateway/test_gateway.sh
- rest_gateway/test_live_cuebot.sh
- rest_gateway/test_rest_gateway_docker_compose.sh
Major additions and improvements:
- Create complete OpenCue REST Gateway documentation suite
- Create comprehensive REST Gateway test scripts and validation tools
- Full integration with OpenCue docs structure across all guide categories
- Normalize JWT configuration to use JWT_SECRET consistently
- Remove incorrect /health endpoint references throughout
- Fix deprecated datetime usage with timezone-aware implementations
- Add testing workflows
Core code changes:
- `main.go`: Normalize JWT_SECRET environment variable usage
- `main_test.go`: Add comprehensive endpoint testing for all interfaces
- `Dockerfile`: Update JWT environment variable and Rocky Linux base
- `.gitignore`: Add coverage files and test artifacts exclusions
- Update `README.md`
OpenCue docs integration (docs/_docs/):
- …
> [rest_gateway] Add comprehensive OpenCue REST Gateway documentation and testing infrastructure

- docs/releases/announcing-the-release-of-opencue-v1.11.66.md
- Document major features including Rust RQD implementation, Loki integration, and Cueman CLI
- Add notable improvements and complete changelog
- Include PyPI package installation instructions
- https://github.com/AcademySoftwareFoundation/OpenCue/issues/1800
> [docs] Add v1.11.66 release notes documentation

- cueadmin/README.md
- cuegui/README.md
- cueman/README.md
- cuesubmit/README.md
- proto/README.md
- pycue/README.md
- pyoutline/README.md
- rqd/README.md
- README files updated: cueadmin, cuegui, cueman, cuesubmit, proto (new), pycue, pyoutline, rqd
- The new descriptions follow the pyproject.toml files descriptions
- https://github.com/AcademySoftwareFoundation/OpenCue/issues/1889
> Update the description of the Opencue modules' README files.

- cueadmin/tests/test_util.py
- https://github.com/AcademySoftwareFoundation/OpenCue/issues/1923
Create comprehensive test coverage for util.py including:
- enableDebugLogging() logger configuration tests
- promptYesNo() input validation and force flag tests
- waitOnJobName() job monitoring, timeouts, and exception handling tests
All tests use mocked user input and time.sleep for efficient execution.
> [cueadmin] Add unit tests for utility functions
